version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/apps/web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitejs/plugin-react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jsdom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/apps/mobile"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "expo-camera"
        update-types: ["version-update:semver-major"]
      - dependency-name: "expo-sqlite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/packages/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: gomod
    directory: "/apps/api"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: "/packages/business-logic"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5