// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alerts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :exec
UPDATE alerts SET
    is_acknowledged = true, acknowledged_by = $1, acknowledged_at = now()
WHERE id = $2 AND org_id = $3
`

type AcknowledgeAlertParams struct {
	AcknowledgedBy sql.NullString `json:"acknowledged_by"`
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) error {
	_, err := q.exec(ctx, q.acknowledgeAlertStmt, acknowledgeAlert, arg.AcknowledgedBy, arg.ID, arg.OrgID)
	return err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (org_id, alert_config_id, alert_type, severity, title, message, product_id, warehouse_id, batch_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, alert_config_id, alert_type, severity, title, message, product_id, warehouse_id, batch_id, is_read, is_acknowledged, acknowledged_by, acknowledged_at, resolved_at, created_at
`

type CreateAlertParams struct {
	OrgID         string         `json:"org_id"`
	AlertConfigID uuid.NullUUID  `json:"alert_config_id"`
	AlertType     string         `json:"alert_type"`
	Severity      sql.NullString `json:"severity"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	ProductID     uuid.NullUUID  `json:"product_id"`
	WarehouseID   uuid.NullUUID  `json:"warehouse_id"`
	BatchID       uuid.NullUUID  `json:"batch_id"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.queryRow(ctx, q.createAlertStmt, createAlert,
		arg.OrgID,
		arg.AlertConfigID,
		arg.AlertType,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AlertConfigID,
		&i.AlertType,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.ProductID,
		&i.WarehouseID,
		&i.BatchID,
		&i.IsRead,
		&i.IsAcknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertConfiguration = `-- name: CreateAlertConfiguration :one
INSERT INTO alert_configurations (org_id, alert_type, name, description, threshold_type, threshold_value, enabled, notification_channels, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, alert_type, name, description, threshold_type, threshold_value, enabled, notification_channels, created_by, updated_by, created_at, updated_at
`

type CreateAlertConfigurationParams struct {
	OrgID                string         `json:"org_id"`
	AlertType            string         `json:"alert_type"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	ThresholdType        sql.NullString `json:"threshold_type"`
	ThresholdValue       string         `json:"threshold_value"`
	Enabled              bool           `json:"enabled"`
	NotificationChannels string         `json:"notification_channels"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateAlertConfiguration(ctx context.Context, arg CreateAlertConfigurationParams) (AlertConfiguration, error) {
	row := q.queryRow(ctx, q.createAlertConfigurationStmt, createAlertConfiguration,
		arg.OrgID,
		arg.AlertType,
		arg.Name,
		arg.Description,
		arg.ThresholdType,
		arg.ThresholdValue,
		arg.Enabled,
		arg.NotificationChannels,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AlertConfiguration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AlertType,
		&i.Name,
		&i.Description,
		&i.ThresholdType,
		&i.ThresholdValue,
		&i.Enabled,
		&i.NotificationChannels,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAlerts = `-- name: GetActiveAlerts :many
SELECT a.id, a.org_id, a.alert_config_id, a.alert_type, a.severity, a.title, a.message, a.product_id, a.warehouse_id, a.batch_id, a.is_read, a.is_acknowledged, a.acknowledged_by, a.acknowledged_at, a.resolved_at, a.created_at, p.name as product_name, w.name as warehouse_name
FROM alerts a
LEFT JOIN products p ON a.product_id = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
WHERE a.org_id = $1 AND a.resolved_at IS NULL
ORDER BY a.created_at DESC
`

type GetActiveAlertsRow struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	AlertConfigID  uuid.NullUUID  `json:"alert_config_id"`
	AlertType      string         `json:"alert_type"`
	Severity       sql.NullString `json:"severity"`
	Title          string         `json:"title"`
	Message        string         `json:"message"`
	ProductID      uuid.NullUUID  `json:"product_id"`
	WarehouseID    uuid.NullUUID  `json:"warehouse_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	IsRead         bool           `json:"is_read"`
	IsAcknowledged bool           `json:"is_acknowledged"`
	AcknowledgedBy sql.NullString `json:"acknowledged_by"`
	AcknowledgedAt sql.NullTime   `json:"acknowledged_at"`
	ResolvedAt     sql.NullTime   `json:"resolved_at"`
	CreatedAt      time.Time      `json:"created_at"`
	ProductName    sql.NullString `json:"product_name"`
	WarehouseName  sql.NullString `json:"warehouse_name"`
}

func (q *Queries) GetActiveAlerts(ctx context.Context, orgID string) ([]GetActiveAlertsRow, error) {
	rows, err := q.query(ctx, q.getActiveAlertsStmt, getActiveAlerts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveAlertsRow{}
	for rows.Next() {
		var i GetActiveAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AlertConfigID,
			&i.AlertType,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.ProductID,
			&i.WarehouseID,
			&i.BatchID,
			&i.IsRead,
			&i.IsAcknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ProductName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertConfigurations = `-- name: ListAlertConfigurations :many
SELECT id, org_id, alert_type, name, description, threshold_type, threshold_value, enabled, notification_channels, created_by, updated_by, created_at, updated_at FROM alert_configurations
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListAlertConfigurations(ctx context.Context, orgID string) ([]AlertConfiguration, error) {
	rows, err := q.query(ctx, q.listAlertConfigurationsStmt, listAlertConfigurations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertConfiguration{}
	for rows.Next() {
		var i AlertConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AlertType,
			&i.Name,
			&i.Description,
			&i.ThresholdType,
			&i.ThresholdValue,
			&i.Enabled,
			&i.NotificationChannels,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.org_id, a.alert_config_id, a.alert_type, a.severity, a.title, a.message, a.product_id, a.warehouse_id, a.batch_id, a.is_read, a.is_acknowledged, a.acknowledged_by, a.acknowledged_at, a.resolved_at, a.created_at, p.name as product_name, w.name as warehouse_name
FROM alerts a
LEFT JOIN products p ON a.product_id = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
WHERE a.org_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAlertsRow struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	AlertConfigID  uuid.NullUUID  `json:"alert_config_id"`
	AlertType      string         `json:"alert_type"`
	Severity       sql.NullString `json:"severity"`
	Title          string         `json:"title"`
	Message        string         `json:"message"`
	ProductID      uuid.NullUUID  `json:"product_id"`
	WarehouseID    uuid.NullUUID  `json:"warehouse_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	IsRead         bool           `json:"is_read"`
	IsAcknowledged bool           `json:"is_acknowledged"`
	AcknowledgedBy sql.NullString `json:"acknowledged_by"`
	AcknowledgedAt sql.NullTime   `json:"acknowledged_at"`
	ResolvedAt     sql.NullTime   `json:"resolved_at"`
	CreatedAt      time.Time      `json:"created_at"`
	ProductName    sql.NullString `json:"product_name"`
	WarehouseName  sql.NullString `json:"warehouse_name"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.query(ctx, q.listAlertsStmt, listAlerts, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AlertConfigID,
			&i.AlertType,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.ProductID,
			&i.WarehouseID,
			&i.BatchID,
			&i.IsRead,
			&i.IsAcknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ProductName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE alerts SET
    resolved_at = now()
WHERE id = $1 AND org_id = $2
`

type ResolveAlertParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) ResolveAlert(ctx context.Context, arg ResolveAlertParams) error {
	_, err := q.exec(ctx, q.resolveAlertStmt, resolveAlert, arg.ID, arg.OrgID)
	return err
}
