// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assets.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addCustodyChange = `-- name: AddCustodyChange :one
INSERT INTO asset_custody_changes (asset_id, from_user_id, to_user_id, changed_by)
VALUES ($1, $2, $3, $4)
RETURNING id, asset_id, from_user_id, to_user_id, changed_by, changed_at
`

type AddCustodyChangeParams struct {
	AssetID    string         `json:"asset_id"`
	FromUserID uuid.NullUUID  `json:"from_user_id"`
	ToUserID   uuid.NullUUID  `json:"to_user_id"`
	ChangedBy  sql.NullString `json:"changed_by"`
}

func (q *Queries) AddCustodyChange(ctx context.Context, arg AddCustodyChangeParams) (AssetCustodyChange, error) {
	row := q.queryRow(ctx, q.addCustodyChangeStmt, addCustodyChange,
		arg.AssetID,
		arg.FromUserID,
		arg.ToUserID,
		arg.ChangedBy,
	)
	var i AssetCustodyChange
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const addMaintenanceRecord = `-- name: AddMaintenanceRecord :one
INSERT INTO asset_maintenance (asset_id, maintenance_date, description, cost, performed_by, next_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, asset_id, maintenance_date, description, cost, performed_by, next_date, created_at
`

type AddMaintenanceRecordParams struct {
	AssetID         string         `json:"asset_id"`
	MaintenanceDate time.Time      `json:"maintenance_date"`
	Description     sql.NullString `json:"description"`
	Cost            sql.NullString `json:"cost"`
	PerformedBy     sql.NullString `json:"performed_by"`
	NextDate        sql.NullTime   `json:"next_date"`
}

func (q *Queries) AddMaintenanceRecord(ctx context.Context, arg AddMaintenanceRecordParams) (AssetMaintenance, error) {
	row := q.queryRow(ctx, q.addMaintenanceRecordStmt, addMaintenanceRecord,
		arg.AssetID,
		arg.MaintenanceDate,
		arg.Description,
		arg.Cost,
		arg.PerformedBy,
		arg.NextDate,
	)
	var i AssetMaintenance
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.MaintenanceDate,
		&i.Description,
		&i.Cost,
		&i.PerformedBy,
		&i.NextDate,
		&i.CreatedAt,
	)
	return i, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (org_id, asset_tag, name, description, product_id, serial_number, custodian_id, location_id, acquisition_date, purchase_cost, current_value, depreciation_method, useful_life_years, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, org_id, asset_tag, name, description, product_id, serial_number, custodian_id, location_id, acquisition_date, purchase_cost, current_value, depreciation_method, useful_life_years, status, created_by, updated_by, created_at, updated_at
`

type CreateAssetParams struct {
	OrgID              string         `json:"org_id"`
	AssetTag           string         `json:"asset_tag"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	SerialNumber       sql.NullString `json:"serial_number"`
	CustodianID        uuid.NullUUID  `json:"custodian_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	AcquisitionDate    sql.NullTime   `json:"acquisition_date"`
	PurchaseCost       sql.NullString `json:"purchase_cost"`
	CurrentValue       sql.NullString `json:"current_value"`
	DepreciationMethod sql.NullString `json:"depreciation_method"`
	UsefulLifeYears    sql.NullInt32  `json:"useful_life_years"`
	Status             string         `json:"status"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.queryRow(ctx, q.createAssetStmt, createAsset,
		arg.OrgID,
		arg.AssetTag,
		arg.Name,
		arg.Description,
		arg.ProductID,
		arg.SerialNumber,
		arg.CustodianID,
		arg.LocationID,
		arg.AcquisitionDate,
		arg.PurchaseCost,
		arg.CurrentValue,
		arg.DepreciationMethod,
		arg.UsefulLifeYears,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetTag,
		&i.Name,
		&i.Description,
		&i.ProductID,
		&i.SerialNumber,
		&i.CustodianID,
		&i.LocationID,
		&i.AcquisitionDate,
		&i.PurchaseCost,
		&i.CurrentValue,
		&i.DepreciationMethod,
		&i.UsefulLifeYears,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.org_id, a.asset_tag, a.name, a.description, a.product_id, a.serial_number, a.custodian_id, a.location_id, a.acquisition_date, a.purchase_cost, a.current_value, a.depreciation_method, a.useful_life_years, a.status, a.created_by, a.updated_by, a.created_at, a.updated_at, u.name as custodian_name, l.code as location_code
FROM assets a
LEFT JOIN users u ON a.custodian_id = u.id
LEFT JOIN locations l ON a.location_id = l.id
WHERE a.id = $1 AND a.org_id = $2
`

type GetAssetParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetAssetRow struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	AssetTag           string         `json:"asset_tag"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	SerialNumber       sql.NullString `json:"serial_number"`
	CustodianID        uuid.NullUUID  `json:"custodian_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	AcquisitionDate    sql.NullTime   `json:"acquisition_date"`
	PurchaseCost       sql.NullString `json:"purchase_cost"`
	CurrentValue       sql.NullString `json:"current_value"`
	DepreciationMethod sql.NullString `json:"depreciation_method"`
	UsefulLifeYears    sql.NullInt32  `json:"useful_life_years"`
	Status             string         `json:"status"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustodianName      sql.NullString `json:"custodian_name"`
	LocationCode       sql.NullString `json:"location_code"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.queryRow(ctx, q.getAssetStmt, getAsset, arg.ID, arg.OrgID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetTag,
		&i.Name,
		&i.Description,
		&i.ProductID,
		&i.SerialNumber,
		&i.CustodianID,
		&i.LocationID,
		&i.AcquisitionDate,
		&i.PurchaseCost,
		&i.CurrentValue,
		&i.DepreciationMethod,
		&i.UsefulLifeYears,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustodianName,
		&i.LocationCode,
	)
	return i, err
}

const listAssetCustodyChanges = `-- name: ListAssetCustodyChanges :many
SELECT acc.id, acc.asset_id, acc.from_user_id, acc.to_user_id, acc.changed_by, acc.changed_at, fu.name as from_user_name, tu.name as to_user_name
FROM asset_custody_changes acc
LEFT JOIN users fu ON acc.from_user_id = fu.id
LEFT JOIN users tu ON acc.to_user_id = tu.id
WHERE acc.asset_id = $1
ORDER BY acc.changed_at DESC
`

type ListAssetCustodyChangesRow struct {
	ID           string         `json:"id"`
	AssetID      string         `json:"asset_id"`
	FromUserID   uuid.NullUUID  `json:"from_user_id"`
	ToUserID     uuid.NullUUID  `json:"to_user_id"`
	ChangedBy    sql.NullString `json:"changed_by"`
	ChangedAt    time.Time      `json:"changed_at"`
	FromUserName sql.NullString `json:"from_user_name"`
	ToUserName   sql.NullString `json:"to_user_name"`
}

func (q *Queries) ListAssetCustodyChanges(ctx context.Context, assetID string) ([]ListAssetCustodyChangesRow, error) {
	rows, err := q.query(ctx, q.listAssetCustodyChangesStmt, listAssetCustodyChanges, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetCustodyChangesRow{}
	for rows.Next() {
		var i ListAssetCustodyChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.FromUserID,
			&i.ToUserID,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.FromUserName,
			&i.ToUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetDepreciation = `-- name: ListAssetDepreciation :many
SELECT id, asset_id, period_date, depreciation_amount, book_value_before, book_value_after, method, created_at FROM asset_depreciation_schedule
WHERE asset_id = $1
ORDER BY period_date DESC
`

func (q *Queries) ListAssetDepreciation(ctx context.Context, assetID string) ([]AssetDepreciationSchedule, error) {
	rows, err := q.query(ctx, q.listAssetDepreciationStmt, listAssetDepreciation, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetDepreciationSchedule{}
	for rows.Next() {
		var i AssetDepreciationSchedule
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.PeriodDate,
			&i.DepreciationAmount,
			&i.BookValueBefore,
			&i.BookValueAfter,
			&i.Method,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetMaintenance = `-- name: ListAssetMaintenance :many
SELECT id, asset_id, maintenance_date, description, cost, performed_by, next_date, created_at FROM asset_maintenance
WHERE asset_id = $1
ORDER BY maintenance_date DESC
`

func (q *Queries) ListAssetMaintenance(ctx context.Context, assetID string) ([]AssetMaintenance, error) {
	rows, err := q.query(ctx, q.listAssetMaintenanceStmt, listAssetMaintenance, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetMaintenance{}
	for rows.Next() {
		var i AssetMaintenance
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.MaintenanceDate,
			&i.Description,
			&i.Cost,
			&i.PerformedBy,
			&i.NextDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.org_id, a.asset_tag, a.name, a.description, a.product_id, a.serial_number, a.custodian_id, a.location_id, a.acquisition_date, a.purchase_cost, a.current_value, a.depreciation_method, a.useful_life_years, a.status, a.created_by, a.updated_by, a.created_at, a.updated_at, u.name as custodian_name, l.code as location_code
FROM assets a
LEFT JOIN users u ON a.custodian_id = u.id
LEFT JOIN locations l ON a.location_id = l.id
WHERE a.org_id = $1
ORDER BY a.name
LIMIT $2 OFFSET $3
`

type ListAssetsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAssetsRow struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	AssetTag           string         `json:"asset_tag"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	SerialNumber       sql.NullString `json:"serial_number"`
	CustodianID        uuid.NullUUID  `json:"custodian_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	AcquisitionDate    sql.NullTime   `json:"acquisition_date"`
	PurchaseCost       sql.NullString `json:"purchase_cost"`
	CurrentValue       sql.NullString `json:"current_value"`
	DepreciationMethod sql.NullString `json:"depreciation_method"`
	UsefulLifeYears    sql.NullInt32  `json:"useful_life_years"`
	Status             string         `json:"status"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustodianName      sql.NullString `json:"custodian_name"`
	LocationCode       sql.NullString `json:"location_code"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.query(ctx, q.listAssetsStmt, listAssets, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AssetTag,
			&i.Name,
			&i.Description,
			&i.ProductID,
			&i.SerialNumber,
			&i.CustodianID,
			&i.LocationID,
			&i.AcquisitionDate,
			&i.PurchaseCost,
			&i.CurrentValue,
			&i.DepreciationMethod,
			&i.UsefulLifeYears,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustodianName,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :exec
UPDATE assets SET
    name = $1, description = $2, custodian_id = $3, location_id = $4,
    current_value = $5, status = $6, updated_by = $7
WHERE id = $8 AND org_id = $9
`

type UpdateAssetParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CustodianID  uuid.NullUUID  `json:"custodian_id"`
	LocationID   uuid.NullUUID  `json:"location_id"`
	CurrentValue sql.NullString `json:"current_value"`
	Status       string         `json:"status"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) error {
	_, err := q.exec(ctx, q.updateAssetStmt, updateAsset,
		arg.Name,
		arg.Description,
		arg.CustodianID,
		arg.LocationID,
		arg.CurrentValue,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
