// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (org_id, user_id, action, entity_type, entity_id, changes, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditLogParams struct {
	OrgID      string                `json:"org_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   sql.NullString        `json:"entity_id"`
	Changes    pqtype.NullRawMessage `json:"changes"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.exec(ctx, q.createAuditLogStmt, createAuditLog,
		arg.OrgID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createDataChangeLog = `-- name: CreateDataChangeLog :exec
INSERT INTO data_change_log (org_id, table_name, record_id, operation, old_values, new_values, changed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDataChangeLogParams struct {
	OrgID     string                `json:"org_id"`
	TableName string                `json:"table_name"`
	RecordID  string                `json:"record_id"`
	Operation string                `json:"operation"`
	OldValues pqtype.NullRawMessage `json:"old_values"`
	NewValues pqtype.NullRawMessage `json:"new_values"`
	ChangedBy string                `json:"changed_by"`
}

func (q *Queries) CreateDataChangeLog(ctx context.Context, arg CreateDataChangeLogParams) error {
	_, err := q.exec(ctx, q.createDataChangeLogStmt, createDataChangeLog,
		arg.OrgID,
		arg.TableName,
		arg.RecordID,
		arg.Operation,
		arg.OldValues,
		arg.NewValues,
		arg.ChangedBy,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.org_id, al.user_id, al.action, al.entity_type, al.entity_id, al.changes, al.ip_address, al.user_agent, al.timestamp, u.name as user_name
FROM audit_log al
LEFT JOIN users u ON al.user_id = u.id
WHERE al.org_id = $1
ORDER BY al.timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAuditLogsRow struct {
	ID         string                `json:"id"`
	OrgID      string                `json:"org_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   sql.NullString        `json:"entity_id"`
	Changes    pqtype.NullRawMessage `json:"changes"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	Timestamp  time.Time             `json:"timestamp"`
	UserName   sql.NullString        `json:"user_name"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.query(ctx, q.listAuditLogsStmt, listAuditLogs, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.UserAgent,
			&i.Timestamp,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLogs = `-- name: SearchAuditLogs :many
SELECT al.id, al.org_id, al.user_id, al.action, al.entity_type, al.entity_id, al.changes, al.ip_address, al.user_agent, al.timestamp, u.name as user_name
FROM audit_log al
LEFT JOIN users u ON al.user_id = u.id
WHERE al.org_id = $1
  AND ($2 = '' OR al.action = $2)
  AND ($3 = '' OR al.entity_type = $3)
  AND ($4::date IS NULL OR al.timestamp >= $4::date)
  AND ($5::date IS NULL OR al.timestamp <= $5::date + interval '1 day')
ORDER BY al.timestamp DESC
LIMIT $6 OFFSET $7
`

type SearchAuditLogsParams struct {
	OrgID   string      `json:"org_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 time.Time   `json:"column_4"`
	Column5 time.Time   `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchAuditLogsRow struct {
	ID         string                `json:"id"`
	OrgID      string                `json:"org_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   sql.NullString        `json:"entity_id"`
	Changes    pqtype.NullRawMessage `json:"changes"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	Timestamp  time.Time             `json:"timestamp"`
	UserName   sql.NullString        `json:"user_name"`
}

func (q *Queries) SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]SearchAuditLogsRow, error) {
	rows, err := q.query(ctx, q.searchAuditLogsStmt, searchAuditLogs,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAuditLogsRow{}
	for rows.Next() {
		var i SearchAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.UserAgent,
			&i.Timestamp,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
