// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO product_categories (org_id, parent_id, name, description, unspsc, eclass, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, parent_id, name, description, unspsc, eclass, status, created_by, updated_by, created_at, updated_at
`

type CreateCategoryParams struct {
	OrgID       string         `json:"org_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Unspsc      sql.NullString `json:"unspsc"`
	Eclass      sql.NullString `json:"eclass"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ProductCategory, error) {
	row := q.queryRow(ctx, q.createCategoryStmt, createCategory,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Unspsc,
		arg.Eclass,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Unspsc,
		&i.Eclass,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE product_categories SET status = 'inactive', updated_by = $1
WHERE id = $2 AND org_id = $3
`

type DeleteCategoryParams struct {
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.exec(ctx, q.deleteCategoryStmt, deleteCategory, arg.UpdatedBy, arg.ID, arg.OrgID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, org_id, parent_id, name, description, unspsc, eclass, status, created_by, updated_by, created_at, updated_at FROM product_categories
WHERE id = $1 AND org_id = $2
`

type GetCategoryParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (ProductCategory, error) {
	row := q.queryRow(ctx, q.getCategoryStmt, getCategory, arg.ID, arg.OrgID)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Unspsc,
		&i.Eclass,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, org_id, parent_id, name, description, unspsc, eclass, status, created_by, updated_by, created_at, updated_at FROM product_categories
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, orgID string) ([]ProductCategory, error) {
	rows, err := q.query(ctx, q.listCategoriesStmt, listCategories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCategory{}
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Unspsc,
			&i.Eclass,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTree = `-- name: ListCategoryTree :many
SELECT c.id, c.org_id, c.parent_id, c.name, c.description, c.unspsc, c.eclass, c.status, c.created_by, c.updated_by, c.created_at, c.updated_at, p.name as parent_name
FROM product_categories c
LEFT JOIN product_categories p ON c.parent_id = p.id
WHERE c.org_id = $1
ORDER BY c.name
`

type ListCategoryTreeRow struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Unspsc      sql.NullString `json:"unspsc"`
	Eclass      sql.NullString `json:"eclass"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ParentName  sql.NullString `json:"parent_name"`
}

func (q *Queries) ListCategoryTree(ctx context.Context, orgID string) ([]ListCategoryTreeRow, error) {
	rows, err := q.query(ctx, q.listCategoryTreeStmt, listCategoryTree, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryTreeRow{}
	for rows.Next() {
		var i ListCategoryTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Unspsc,
			&i.Eclass,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE product_categories SET
    name = $1, description = $2, unspsc = $3, eclass = $4,
    status = $5, updated_by = $6
WHERE id = $7 AND org_id = $8
`

type UpdateCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Unspsc      sql.NullString `json:"unspsc"`
	Eclass      sql.NullString `json:"eclass"`
	Status      EntityStatus   `json:"status"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.exec(ctx, q.updateCategoryStmt, updateCategory,
		arg.Name,
		arg.Description,
		arg.Unspsc,
		arg.Eclass,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
