// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.acknowledgeAlertStmt, err = db.PrepareContext(ctx, acknowledgeAlert); err != nil {
		return nil, fmt.Errorf("error preparing query AcknowledgeAlert: %w", err)
	}
	if q.addCustodyChangeStmt, err = db.PrepareContext(ctx, addCustodyChange); err != nil {
		return nil, fmt.Errorf("error preparing query AddCustodyChange: %w", err)
	}
	if q.addDistributionLineItemStmt, err = db.PrepareContext(ctx, addDistributionLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddDistributionLineItem: %w", err)
	}
	if q.addMaintenanceRecordStmt, err = db.PrepareContext(ctx, addMaintenanceRecord); err != nil {
		return nil, fmt.Errorf("error preparing query AddMaintenanceRecord: %w", err)
	}
	if q.addPOLineItemStmt, err = db.PrepareContext(ctx, addPOLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddPOLineItem: %w", err)
	}
	if q.countProductsStmt, err = db.PrepareContext(ctx, countProducts); err != nil {
		return nil, fmt.Errorf("error preparing query CountProducts: %w", err)
	}
	if q.createAMCCalculationStmt, err = db.PrepareContext(ctx, createAMCCalculation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAMCCalculation: %w", err)
	}
	if q.createAdjustmentStmt, err = db.PrepareContext(ctx, createAdjustment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAdjustment: %w", err)
	}
	if q.createAdjustmentLineItemStmt, err = db.PrepareContext(ctx, createAdjustmentLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAdjustmentLineItem: %w", err)
	}
	if q.createAlertStmt, err = db.PrepareContext(ctx, createAlert); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAlert: %w", err)
	}
	if q.createAlertConfigurationStmt, err = db.PrepareContext(ctx, createAlertConfiguration); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAlertConfiguration: %w", err)
	}
	if q.createAssetStmt, err = db.PrepareContext(ctx, createAsset); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAsset: %w", err)
	}
	if q.createAuditLogStmt, err = db.PrepareContext(ctx, createAuditLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuditLog: %w", err)
	}
	if q.createBatchStmt, err = db.PrepareContext(ctx, createBatch); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBatch: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createDataChangeLogStmt, err = db.PrepareContext(ctx, createDataChangeLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDataChangeLog: %w", err)
	}
	if q.createDepartmentStmt, err = db.PrepareContext(ctx, createDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDepartment: %w", err)
	}
	if q.createDistributionStmt, err = db.PrepareContext(ctx, createDistribution); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDistribution: %w", err)
	}
	if q.createForecastResultStmt, err = db.PrepareContext(ctx, createForecastResult); err != nil {
		return nil, fmt.Errorf("error preparing query CreateForecastResult: %w", err)
	}
	if q.createGRNStmt, err = db.PrepareContext(ctx, createGRN); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGRN: %w", err)
	}
	if q.createGRNLineItemStmt, err = db.PrepareContext(ctx, createGRNLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGRNLineItem: %w", err)
	}
	if q.createIssueLineItemStmt, err = db.PrepareContext(ctx, createIssueLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIssueLineItem: %w", err)
	}
	if q.createLocationStmt, err = db.PrepareContext(ctx, createLocation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLocation: %w", err)
	}
	if q.createOrgLevelStmt, err = db.PrepareContext(ctx, createOrgLevel); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrgLevel: %w", err)
	}
	if q.createOrganizationStmt, err = db.PrepareContext(ctx, createOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganization: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createProgramStmt, err = db.PrepareContext(ctx, createProgram); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProgram: %w", err)
	}
	if q.createPurchaseOrderStmt, err = db.PrepareContext(ctx, createPurchaseOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePurchaseOrder: %w", err)
	}
	if q.createQAChecklistItemStmt, err = db.PrepareContext(ctx, createQAChecklistItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQAChecklistItem: %w", err)
	}
	if q.createQAChecklistTemplateStmt, err = db.PrepareContext(ctx, createQAChecklistTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQAChecklistTemplate: %w", err)
	}
	if q.createQAInspectionStmt, err = db.PrepareContext(ctx, createQAInspection); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQAInspection: %w", err)
	}
	if q.createReorderRecommendationStmt, err = db.PrepareContext(ctx, createReorderRecommendation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReorderRecommendation: %w", err)
	}
	if q.createReportDefinitionStmt, err = db.PrepareContext(ctx, createReportDefinition); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReportDefinition: %w", err)
	}
	if q.createReportScheduleStmt, err = db.PrepareContext(ctx, createReportSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReportSchedule: %w", err)
	}
	if q.createRoleStmt, err = db.PrepareContext(ctx, createRole); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRole: %w", err)
	}
	if q.createStockIssueStmt, err = db.PrepareContext(ctx, createStockIssue); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockIssue: %w", err)
	}
	if q.createStockMovementStmt, err = db.PrepareContext(ctx, createStockMovement); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStockMovement: %w", err)
	}
	if q.createSupplierStmt, err = db.PrepareContext(ctx, createSupplier); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSupplier: %w", err)
	}
	if q.createSyncConflictStmt, err = db.PrepareContext(ctx, createSyncConflict); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSyncConflict: %w", err)
	}
	if q.createSyncLogStmt, err = db.PrepareContext(ctx, createSyncLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSyncLog: %w", err)
	}
	if q.createTransferStmt, err = db.PrepareContext(ctx, createTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransfer: %w", err)
	}
	if q.createTransferLineItemStmt, err = db.PrepareContext(ctx, createTransferLineItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransferLineItem: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createWarehouseStmt, err = db.PrepareContext(ctx, createWarehouse); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWarehouse: %w", err)
	}
	if q.deleteCategoryStmt, err = db.PrepareContext(ctx, deleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategory: %w", err)
	}
	if q.deleteProductStmt, err = db.PrepareContext(ctx, deleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProduct: %w", err)
	}
	if q.getActiveAlertsStmt, err = db.PrepareContext(ctx, getActiveAlerts); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveAlerts: %w", err)
	}
	if q.getAdjustmentStmt, err = db.PrepareContext(ctx, getAdjustment); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdjustment: %w", err)
	}
	if q.getAssetStmt, err = db.PrepareContext(ctx, getAsset); err != nil {
		return nil, fmt.Errorf("error preparing query GetAsset: %w", err)
	}
	if q.getBatchesByProductStmt, err = db.PrepareContext(ctx, getBatchesByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetBatchesByProduct: %w", err)
	}
	if q.getCategoryStmt, err = db.PrepareContext(ctx, getCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategory: %w", err)
	}
	if q.getDistributionStmt, err = db.PrepareContext(ctx, getDistribution); err != nil {
		return nil, fmt.Errorf("error preparing query GetDistribution: %w", err)
	}
	if q.getExpiringBatchesStmt, err = db.PrepareContext(ctx, getExpiringBatches); err != nil {
		return nil, fmt.Errorf("error preparing query GetExpiringBatches: %w", err)
	}
	if q.getGRNStmt, err = db.PrepareContext(ctx, getGRN); err != nil {
		return nil, fmt.Errorf("error preparing query GetGRN: %w", err)
	}
	if q.getLatestAMCStmt, err = db.PrepareContext(ctx, getLatestAMC); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestAMC: %w", err)
	}
	if q.getOrgTreeStmt, err = db.PrepareContext(ctx, getOrgTree); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrgTree: %w", err)
	}
	if q.getOrganizationStmt, err = db.PrepareContext(ctx, getOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganization: %w", err)
	}
	if q.getPendingConflictsStmt, err = db.PrepareContext(ctx, getPendingConflicts); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingConflicts: %w", err)
	}
	if q.getProductStmt, err = db.PrepareContext(ctx, getProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetProduct: %w", err)
	}
	if q.getProductBySKUStmt, err = db.PrepareContext(ctx, getProductBySKU); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductBySKU: %w", err)
	}
	if q.getPurchaseOrderStmt, err = db.PrepareContext(ctx, getPurchaseOrder); err != nil {
		return nil, fmt.Errorf("error preparing query GetPurchaseOrder: %w", err)
	}
	if q.getQAChecklistTemplateStmt, err = db.PrepareContext(ctx, getQAChecklistTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query GetQAChecklistTemplate: %w", err)
	}
	if q.getQAInspectionStmt, err = db.PrepareContext(ctx, getQAInspection); err != nil {
		return nil, fmt.Errorf("error preparing query GetQAInspection: %w", err)
	}
	if q.getReportDefinitionStmt, err = db.PrepareContext(ctx, getReportDefinition); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportDefinition: %w", err)
	}
	if q.getStockIssueStmt, err = db.PrepareContext(ctx, getStockIssue); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockIssue: %w", err)
	}
	if q.getStockLevelStmt, err = db.PrepareContext(ctx, getStockLevel); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockLevel: %w", err)
	}
	if q.getStockLevelsStmt, err = db.PrepareContext(ctx, getStockLevels); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockLevels: %w", err)
	}
	if q.getStockMovementsStmt, err = db.PrepareContext(ctx, getStockMovements); err != nil {
		return nil, fmt.Errorf("error preparing query GetStockMovements: %w", err)
	}
	if q.getSupplierStmt, err = db.PrepareContext(ctx, getSupplier); err != nil {
		return nil, fmt.Errorf("error preparing query GetSupplier: %w", err)
	}
	if q.getTransferStmt, err = db.PrepareContext(ctx, getTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransfer: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserPermissionsStmt, err = db.PrepareContext(ctx, getUserPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPermissions: %w", err)
	}
	if q.getWarehouseStmt, err = db.PrepareContext(ctx, getWarehouse); err != nil {
		return nil, fmt.Errorf("error preparing query GetWarehouse: %w", err)
	}
	if q.getWarehouseWithLocationsStmt, err = db.PrepareContext(ctx, getWarehouseWithLocations); err != nil {
		return nil, fmt.Errorf("error preparing query GetWarehouseWithLocations: %w", err)
	}
	if q.listAMCCalculationsStmt, err = db.PrepareContext(ctx, listAMCCalculations); err != nil {
		return nil, fmt.Errorf("error preparing query ListAMCCalculations: %w", err)
	}
	if q.listAdjustmentReasonCodesStmt, err = db.PrepareContext(ctx, listAdjustmentReasonCodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListAdjustmentReasonCodes: %w", err)
	}
	if q.listAdjustmentsStmt, err = db.PrepareContext(ctx, listAdjustments); err != nil {
		return nil, fmt.Errorf("error preparing query ListAdjustments: %w", err)
	}
	if q.listAlertConfigurationsStmt, err = db.PrepareContext(ctx, listAlertConfigurations); err != nil {
		return nil, fmt.Errorf("error preparing query ListAlertConfigurations: %w", err)
	}
	if q.listAlertsStmt, err = db.PrepareContext(ctx, listAlerts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAlerts: %w", err)
	}
	if q.listAssetCustodyChangesStmt, err = db.PrepareContext(ctx, listAssetCustodyChanges); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssetCustodyChanges: %w", err)
	}
	if q.listAssetDepreciationStmt, err = db.PrepareContext(ctx, listAssetDepreciation); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssetDepreciation: %w", err)
	}
	if q.listAssetMaintenanceStmt, err = db.PrepareContext(ctx, listAssetMaintenance); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssetMaintenance: %w", err)
	}
	if q.listAssetsStmt, err = db.PrepareContext(ctx, listAssets); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssets: %w", err)
	}
	if q.listAuditLogsStmt, err = db.PrepareContext(ctx, listAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuditLogs: %w", err)
	}
	if q.listCategoriesStmt, err = db.PrepareContext(ctx, listCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategories: %w", err)
	}
	if q.listCategoryTreeStmt, err = db.PrepareContext(ctx, listCategoryTree); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategoryTree: %w", err)
	}
	if q.listDepartmentsStmt, err = db.PrepareContext(ctx, listDepartments); err != nil {
		return nil, fmt.Errorf("error preparing query ListDepartments: %w", err)
	}
	if q.listDistributionLineItemsStmt, err = db.PrepareContext(ctx, listDistributionLineItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListDistributionLineItems: %w", err)
	}
	if q.listDistributionsStmt, err = db.PrepareContext(ctx, listDistributions); err != nil {
		return nil, fmt.Errorf("error preparing query ListDistributions: %w", err)
	}
	if q.listForecastResultsStmt, err = db.PrepareContext(ctx, listForecastResults); err != nil {
		return nil, fmt.Errorf("error preparing query ListForecastResults: %w", err)
	}
	if q.listGRNLineItemsStmt, err = db.PrepareContext(ctx, listGRNLineItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListGRNLineItems: %w", err)
	}
	if q.listGRNsStmt, err = db.PrepareContext(ctx, listGRNs); err != nil {
		return nil, fmt.Errorf("error preparing query ListGRNs: %w", err)
	}
	if q.listIssueLineItemsStmt, err = db.PrepareContext(ctx, listIssueLineItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListIssueLineItems: %w", err)
	}
	if q.listLocationsStmt, err = db.PrepareContext(ctx, listLocations); err != nil {
		return nil, fmt.Errorf("error preparing query ListLocations: %w", err)
	}
	if q.listOrgLevelsStmt, err = db.PrepareContext(ctx, listOrgLevels); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrgLevels: %w", err)
	}
	if q.listOrganizationsStmt, err = db.PrepareContext(ctx, listOrganizations); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrganizations: %w", err)
	}
	if q.listPOLineItemsStmt, err = db.PrepareContext(ctx, listPOLineItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListPOLineItems: %w", err)
	}
	if q.listPermissionsStmt, err = db.PrepareContext(ctx, listPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query ListPermissions: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.listProductsByCategoryStmt, err = db.PrepareContext(ctx, listProductsByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsByCategory: %w", err)
	}
	if q.listProgramsStmt, err = db.PrepareContext(ctx, listPrograms); err != nil {
		return nil, fmt.Errorf("error preparing query ListPrograms: %w", err)
	}
	if q.listPurchaseOrdersStmt, err = db.PrepareContext(ctx, listPurchaseOrders); err != nil {
		return nil, fmt.Errorf("error preparing query ListPurchaseOrders: %w", err)
	}
	if q.listQAChecklistItemsStmt, err = db.PrepareContext(ctx, listQAChecklistItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListQAChecklistItems: %w", err)
	}
	if q.listQAChecklistTemplatesStmt, err = db.PrepareContext(ctx, listQAChecklistTemplates); err != nil {
		return nil, fmt.Errorf("error preparing query ListQAChecklistTemplates: %w", err)
	}
	if q.listQAInspectionsStmt, err = db.PrepareContext(ctx, listQAInspections); err != nil {
		return nil, fmt.Errorf("error preparing query ListQAInspections: %w", err)
	}
	if q.listReorderRecommendationsStmt, err = db.PrepareContext(ctx, listReorderRecommendations); err != nil {
		return nil, fmt.Errorf("error preparing query ListReorderRecommendations: %w", err)
	}
	if q.listReportDefinitionsStmt, err = db.PrepareContext(ctx, listReportDefinitions); err != nil {
		return nil, fmt.Errorf("error preparing query ListReportDefinitions: %w", err)
	}
	if q.listReportSchedulesStmt, err = db.PrepareContext(ctx, listReportSchedules); err != nil {
		return nil, fmt.Errorf("error preparing query ListReportSchedules: %w", err)
	}
	if q.listRolesStmt, err = db.PrepareContext(ctx, listRoles); err != nil {
		return nil, fmt.Errorf("error preparing query ListRoles: %w", err)
	}
	if q.listStockIssuesStmt, err = db.PrepareContext(ctx, listStockIssues); err != nil {
		return nil, fmt.Errorf("error preparing query ListStockIssues: %w", err)
	}
	if q.listSuppliersStmt, err = db.PrepareContext(ctx, listSuppliers); err != nil {
		return nil, fmt.Errorf("error preparing query ListSuppliers: %w", err)
	}
	if q.listTransferLineItemsStmt, err = db.PrepareContext(ctx, listTransferLineItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransferLineItems: %w", err)
	}
	if q.listTransfersStmt, err = db.PrepareContext(ctx, listTransfers); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransfers: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.listWarehousesStmt, err = db.PrepareContext(ctx, listWarehouses); err != nil {
		return nil, fmt.Errorf("error preparing query ListWarehouses: %w", err)
	}
	if q.listWarehousesByTypeStmt, err = db.PrepareContext(ctx, listWarehousesByType); err != nil {
		return nil, fmt.Errorf("error preparing query ListWarehousesByType: %w", err)
	}
	if q.markRecommendationReviewedStmt, err = db.PrepareContext(ctx, markRecommendationReviewed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkRecommendationReviewed: %w", err)
	}
	if q.resolveAlertStmt, err = db.PrepareContext(ctx, resolveAlert); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveAlert: %w", err)
	}
	if q.resolveSyncConflictStmt, err = db.PrepareContext(ctx, resolveSyncConflict); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveSyncConflict: %w", err)
	}
	if q.searchAuditLogsStmt, err = db.PrepareContext(ctx, searchAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query SearchAuditLogs: %w", err)
	}
	if q.searchProductsStmt, err = db.PrepareContext(ctx, searchProducts); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProducts: %w", err)
	}
	if q.searchStockMovementsStmt, err = db.PrepareContext(ctx, searchStockMovements); err != nil {
		return nil, fmt.Errorf("error preparing query SearchStockMovements: %w", err)
	}
	if q.updateAssetStmt, err = db.PrepareContext(ctx, updateAsset); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAsset: %w", err)
	}
	if q.updateCategoryStmt, err = db.PrepareContext(ctx, updateCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategory: %w", err)
	}
	if q.updateDistributionStatusStmt, err = db.PrepareContext(ctx, updateDistributionStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDistributionStatus: %w", err)
	}
	if q.updateLocationStmt, err = db.PrepareContext(ctx, updateLocation); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLocation: %w", err)
	}
	if q.updateOrganizationStmt, err = db.PrepareContext(ctx, updateOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrganization: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updateProductStockParamsStmt, err = db.PrepareContext(ctx, updateProductStockParams); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductStockParams: %w", err)
	}
	if q.updatePurchaseOrderStatusStmt, err = db.PrepareContext(ctx, updatePurchaseOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePurchaseOrderStatus: %w", err)
	}
	if q.updateQAInspectionResultStmt, err = db.PrepareContext(ctx, updateQAInspectionResult); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateQAInspectionResult: %w", err)
	}
	if q.updateScheduleLastRunStmt, err = db.PrepareContext(ctx, updateScheduleLastRun); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateScheduleLastRun: %w", err)
	}
	if q.updateStockLevelStmt, err = db.PrepareContext(ctx, updateStockLevel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStockLevel: %w", err)
	}
	if q.updateSupplierStmt, err = db.PrepareContext(ctx, updateSupplier); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSupplier: %w", err)
	}
	if q.updateSyncLogStmt, err = db.PrepareContext(ctx, updateSyncLog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSyncLog: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.acknowledgeAlertStmt != nil {
		if cerr := q.acknowledgeAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing acknowledgeAlertStmt: %w", cerr)
		}
	}
	if q.addCustodyChangeStmt != nil {
		if cerr := q.addCustodyChangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCustodyChangeStmt: %w", cerr)
		}
	}
	if q.addDistributionLineItemStmt != nil {
		if cerr := q.addDistributionLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addDistributionLineItemStmt: %w", cerr)
		}
	}
	if q.addMaintenanceRecordStmt != nil {
		if cerr := q.addMaintenanceRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMaintenanceRecordStmt: %w", cerr)
		}
	}
	if q.addPOLineItemStmt != nil {
		if cerr := q.addPOLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addPOLineItemStmt: %w", cerr)
		}
	}
	if q.countProductsStmt != nil {
		if cerr := q.countProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsStmt: %w", cerr)
		}
	}
	if q.createAMCCalculationStmt != nil {
		if cerr := q.createAMCCalculationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAMCCalculationStmt: %w", cerr)
		}
	}
	if q.createAdjustmentStmt != nil {
		if cerr := q.createAdjustmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAdjustmentStmt: %w", cerr)
		}
	}
	if q.createAdjustmentLineItemStmt != nil {
		if cerr := q.createAdjustmentLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAdjustmentLineItemStmt: %w", cerr)
		}
	}
	if q.createAlertStmt != nil {
		if cerr := q.createAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAlertStmt: %w", cerr)
		}
	}
	if q.createAlertConfigurationStmt != nil {
		if cerr := q.createAlertConfigurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAlertConfigurationStmt: %w", cerr)
		}
	}
	if q.createAssetStmt != nil {
		if cerr := q.createAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAssetStmt: %w", cerr)
		}
	}
	if q.createAuditLogStmt != nil {
		if cerr := q.createAuditLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuditLogStmt: %w", cerr)
		}
	}
	if q.createBatchStmt != nil {
		if cerr := q.createBatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBatchStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createDataChangeLogStmt != nil {
		if cerr := q.createDataChangeLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDataChangeLogStmt: %w", cerr)
		}
	}
	if q.createDepartmentStmt != nil {
		if cerr := q.createDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDepartmentStmt: %w", cerr)
		}
	}
	if q.createDistributionStmt != nil {
		if cerr := q.createDistributionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDistributionStmt: %w", cerr)
		}
	}
	if q.createForecastResultStmt != nil {
		if cerr := q.createForecastResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createForecastResultStmt: %w", cerr)
		}
	}
	if q.createGRNStmt != nil {
		if cerr := q.createGRNStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGRNStmt: %w", cerr)
		}
	}
	if q.createGRNLineItemStmt != nil {
		if cerr := q.createGRNLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGRNLineItemStmt: %w", cerr)
		}
	}
	if q.createIssueLineItemStmt != nil {
		if cerr := q.createIssueLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIssueLineItemStmt: %w", cerr)
		}
	}
	if q.createLocationStmt != nil {
		if cerr := q.createLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLocationStmt: %w", cerr)
		}
	}
	if q.createOrgLevelStmt != nil {
		if cerr := q.createOrgLevelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrgLevelStmt: %w", cerr)
		}
	}
	if q.createOrganizationStmt != nil {
		if cerr := q.createOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createProgramStmt != nil {
		if cerr := q.createProgramStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProgramStmt: %w", cerr)
		}
	}
	if q.createPurchaseOrderStmt != nil {
		if cerr := q.createPurchaseOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPurchaseOrderStmt: %w", cerr)
		}
	}
	if q.createQAChecklistItemStmt != nil {
		if cerr := q.createQAChecklistItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQAChecklistItemStmt: %w", cerr)
		}
	}
	if q.createQAChecklistTemplateStmt != nil {
		if cerr := q.createQAChecklistTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQAChecklistTemplateStmt: %w", cerr)
		}
	}
	if q.createQAInspectionStmt != nil {
		if cerr := q.createQAInspectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQAInspectionStmt: %w", cerr)
		}
	}
	if q.createReorderRecommendationStmt != nil {
		if cerr := q.createReorderRecommendationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReorderRecommendationStmt: %w", cerr)
		}
	}
	if q.createReportDefinitionStmt != nil {
		if cerr := q.createReportDefinitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReportDefinitionStmt: %w", cerr)
		}
	}
	if q.createReportScheduleStmt != nil {
		if cerr := q.createReportScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReportScheduleStmt: %w", cerr)
		}
	}
	if q.createRoleStmt != nil {
		if cerr := q.createRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRoleStmt: %w", cerr)
		}
	}
	if q.createStockIssueStmt != nil {
		if cerr := q.createStockIssueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockIssueStmt: %w", cerr)
		}
	}
	if q.createStockMovementStmt != nil {
		if cerr := q.createStockMovementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStockMovementStmt: %w", cerr)
		}
	}
	if q.createSupplierStmt != nil {
		if cerr := q.createSupplierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSupplierStmt: %w", cerr)
		}
	}
	if q.createSyncConflictStmt != nil {
		if cerr := q.createSyncConflictStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSyncConflictStmt: %w", cerr)
		}
	}
	if q.createSyncLogStmt != nil {
		if cerr := q.createSyncLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSyncLogStmt: %w", cerr)
		}
	}
	if q.createTransferStmt != nil {
		if cerr := q.createTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferStmt: %w", cerr)
		}
	}
	if q.createTransferLineItemStmt != nil {
		if cerr := q.createTransferLineItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferLineItemStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createWarehouseStmt != nil {
		if cerr := q.createWarehouseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWarehouseStmt: %w", cerr)
		}
	}
	if q.deleteCategoryStmt != nil {
		if cerr := q.deleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryStmt: %w", cerr)
		}
	}
	if q.deleteProductStmt != nil {
		if cerr := q.deleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductStmt: %w", cerr)
		}
	}
	if q.getActiveAlertsStmt != nil {
		if cerr := q.getActiveAlertsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveAlertsStmt: %w", cerr)
		}
	}
	if q.getAdjustmentStmt != nil {
		if cerr := q.getAdjustmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdjustmentStmt: %w", cerr)
		}
	}
	if q.getAssetStmt != nil {
		if cerr := q.getAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssetStmt: %w", cerr)
		}
	}
	if q.getBatchesByProductStmt != nil {
		if cerr := q.getBatchesByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBatchesByProductStmt: %w", cerr)
		}
	}
	if q.getCategoryStmt != nil {
		if cerr := q.getCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryStmt: %w", cerr)
		}
	}
	if q.getDistributionStmt != nil {
		if cerr := q.getDistributionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDistributionStmt: %w", cerr)
		}
	}
	if q.getExpiringBatchesStmt != nil {
		if cerr := q.getExpiringBatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExpiringBatchesStmt: %w", cerr)
		}
	}
	if q.getGRNStmt != nil {
		if cerr := q.getGRNStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGRNStmt: %w", cerr)
		}
	}
	if q.getLatestAMCStmt != nil {
		if cerr := q.getLatestAMCStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestAMCStmt: %w", cerr)
		}
	}
	if q.getOrgTreeStmt != nil {
		if cerr := q.getOrgTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrgTreeStmt: %w", cerr)
		}
	}
	if q.getOrganizationStmt != nil {
		if cerr := q.getOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationStmt: %w", cerr)
		}
	}
	if q.getPendingConflictsStmt != nil {
		if cerr := q.getPendingConflictsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingConflictsStmt: %w", cerr)
		}
	}
	if q.getProductStmt != nil {
		if cerr := q.getProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductStmt: %w", cerr)
		}
	}
	if q.getProductBySKUStmt != nil {
		if cerr := q.getProductBySKUStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductBySKUStmt: %w", cerr)
		}
	}
	if q.getPurchaseOrderStmt != nil {
		if cerr := q.getPurchaseOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPurchaseOrderStmt: %w", cerr)
		}
	}
	if q.getQAChecklistTemplateStmt != nil {
		if cerr := q.getQAChecklistTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQAChecklistTemplateStmt: %w", cerr)
		}
	}
	if q.getQAInspectionStmt != nil {
		if cerr := q.getQAInspectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQAInspectionStmt: %w", cerr)
		}
	}
	if q.getReportDefinitionStmt != nil {
		if cerr := q.getReportDefinitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReportDefinitionStmt: %w", cerr)
		}
	}
	if q.getStockIssueStmt != nil {
		if cerr := q.getStockIssueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockIssueStmt: %w", cerr)
		}
	}
	if q.getStockLevelStmt != nil {
		if cerr := q.getStockLevelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockLevelStmt: %w", cerr)
		}
	}
	if q.getStockLevelsStmt != nil {
		if cerr := q.getStockLevelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockLevelsStmt: %w", cerr)
		}
	}
	if q.getStockMovementsStmt != nil {
		if cerr := q.getStockMovementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStockMovementsStmt: %w", cerr)
		}
	}
	if q.getSupplierStmt != nil {
		if cerr := q.getSupplierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSupplierStmt: %w", cerr)
		}
	}
	if q.getTransferStmt != nil {
		if cerr := q.getTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransferStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserPermissionsStmt != nil {
		if cerr := q.getUserPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPermissionsStmt: %w", cerr)
		}
	}
	if q.getWarehouseStmt != nil {
		if cerr := q.getWarehouseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWarehouseStmt: %w", cerr)
		}
	}
	if q.getWarehouseWithLocationsStmt != nil {
		if cerr := q.getWarehouseWithLocationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWarehouseWithLocationsStmt: %w", cerr)
		}
	}
	if q.listAMCCalculationsStmt != nil {
		if cerr := q.listAMCCalculationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAMCCalculationsStmt: %w", cerr)
		}
	}
	if q.listAdjustmentReasonCodesStmt != nil {
		if cerr := q.listAdjustmentReasonCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAdjustmentReasonCodesStmt: %w", cerr)
		}
	}
	if q.listAdjustmentsStmt != nil {
		if cerr := q.listAdjustmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAdjustmentsStmt: %w", cerr)
		}
	}
	if q.listAlertConfigurationsStmt != nil {
		if cerr := q.listAlertConfigurationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAlertConfigurationsStmt: %w", cerr)
		}
	}
	if q.listAlertsStmt != nil {
		if cerr := q.listAlertsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAlertsStmt: %w", cerr)
		}
	}
	if q.listAssetCustodyChangesStmt != nil {
		if cerr := q.listAssetCustodyChangesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetCustodyChangesStmt: %w", cerr)
		}
	}
	if q.listAssetDepreciationStmt != nil {
		if cerr := q.listAssetDepreciationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetDepreciationStmt: %w", cerr)
		}
	}
	if q.listAssetMaintenanceStmt != nil {
		if cerr := q.listAssetMaintenanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetMaintenanceStmt: %w", cerr)
		}
	}
	if q.listAssetsStmt != nil {
		if cerr := q.listAssetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetsStmt: %w", cerr)
		}
	}
	if q.listAuditLogsStmt != nil {
		if cerr := q.listAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuditLogsStmt: %w", cerr)
		}
	}
	if q.listCategoriesStmt != nil {
		if cerr := q.listCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesStmt: %w", cerr)
		}
	}
	if q.listCategoryTreeStmt != nil {
		if cerr := q.listCategoryTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoryTreeStmt: %w", cerr)
		}
	}
	if q.listDepartmentsStmt != nil {
		if cerr := q.listDepartmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDepartmentsStmt: %w", cerr)
		}
	}
	if q.listDistributionLineItemsStmt != nil {
		if cerr := q.listDistributionLineItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDistributionLineItemsStmt: %w", cerr)
		}
	}
	if q.listDistributionsStmt != nil {
		if cerr := q.listDistributionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDistributionsStmt: %w", cerr)
		}
	}
	if q.listForecastResultsStmt != nil {
		if cerr := q.listForecastResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listForecastResultsStmt: %w", cerr)
		}
	}
	if q.listGRNLineItemsStmt != nil {
		if cerr := q.listGRNLineItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGRNLineItemsStmt: %w", cerr)
		}
	}
	if q.listGRNsStmt != nil {
		if cerr := q.listGRNsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGRNsStmt: %w", cerr)
		}
	}
	if q.listIssueLineItemsStmt != nil {
		if cerr := q.listIssueLineItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listIssueLineItemsStmt: %w", cerr)
		}
	}
	if q.listLocationsStmt != nil {
		if cerr := q.listLocationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLocationsStmt: %w", cerr)
		}
	}
	if q.listOrgLevelsStmt != nil {
		if cerr := q.listOrgLevelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrgLevelsStmt: %w", cerr)
		}
	}
	if q.listOrganizationsStmt != nil {
		if cerr := q.listOrganizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrganizationsStmt: %w", cerr)
		}
	}
	if q.listPOLineItemsStmt != nil {
		if cerr := q.listPOLineItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPOLineItemsStmt: %w", cerr)
		}
	}
	if q.listPermissionsStmt != nil {
		if cerr := q.listPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPermissionsStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.listProductsByCategoryStmt != nil {
		if cerr := q.listProductsByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsByCategoryStmt: %w", cerr)
		}
	}
	if q.listProgramsStmt != nil {
		if cerr := q.listProgramsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProgramsStmt: %w", cerr)
		}
	}
	if q.listPurchaseOrdersStmt != nil {
		if cerr := q.listPurchaseOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPurchaseOrdersStmt: %w", cerr)
		}
	}
	if q.listQAChecklistItemsStmt != nil {
		if cerr := q.listQAChecklistItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listQAChecklistItemsStmt: %w", cerr)
		}
	}
	if q.listQAChecklistTemplatesStmt != nil {
		if cerr := q.listQAChecklistTemplatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listQAChecklistTemplatesStmt: %w", cerr)
		}
	}
	if q.listQAInspectionsStmt != nil {
		if cerr := q.listQAInspectionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listQAInspectionsStmt: %w", cerr)
		}
	}
	if q.listReorderRecommendationsStmt != nil {
		if cerr := q.listReorderRecommendationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReorderRecommendationsStmt: %w", cerr)
		}
	}
	if q.listReportDefinitionsStmt != nil {
		if cerr := q.listReportDefinitionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReportDefinitionsStmt: %w", cerr)
		}
	}
	if q.listReportSchedulesStmt != nil {
		if cerr := q.listReportSchedulesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReportSchedulesStmt: %w", cerr)
		}
	}
	if q.listRolesStmt != nil {
		if cerr := q.listRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRolesStmt: %w", cerr)
		}
	}
	if q.listStockIssuesStmt != nil {
		if cerr := q.listStockIssuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStockIssuesStmt: %w", cerr)
		}
	}
	if q.listSuppliersStmt != nil {
		if cerr := q.listSuppliersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSuppliersStmt: %w", cerr)
		}
	}
	if q.listTransferLineItemsStmt != nil {
		if cerr := q.listTransferLineItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransferLineItemsStmt: %w", cerr)
		}
	}
	if q.listTransfersStmt != nil {
		if cerr := q.listTransfersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransfersStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.listWarehousesStmt != nil {
		if cerr := q.listWarehousesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWarehousesStmt: %w", cerr)
		}
	}
	if q.listWarehousesByTypeStmt != nil {
		if cerr := q.listWarehousesByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWarehousesByTypeStmt: %w", cerr)
		}
	}
	if q.markRecommendationReviewedStmt != nil {
		if cerr := q.markRecommendationReviewedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markRecommendationReviewedStmt: %w", cerr)
		}
	}
	if q.resolveAlertStmt != nil {
		if cerr := q.resolveAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveAlertStmt: %w", cerr)
		}
	}
	if q.resolveSyncConflictStmt != nil {
		if cerr := q.resolveSyncConflictStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveSyncConflictStmt: %w", cerr)
		}
	}
	if q.searchAuditLogsStmt != nil {
		if cerr := q.searchAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchAuditLogsStmt: %w", cerr)
		}
	}
	if q.searchProductsStmt != nil {
		if cerr := q.searchProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProductsStmt: %w", cerr)
		}
	}
	if q.searchStockMovementsStmt != nil {
		if cerr := q.searchStockMovementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchStockMovementsStmt: %w", cerr)
		}
	}
	if q.updateAssetStmt != nil {
		if cerr := q.updateAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAssetStmt: %w", cerr)
		}
	}
	if q.updateCategoryStmt != nil {
		if cerr := q.updateCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryStmt: %w", cerr)
		}
	}
	if q.updateDistributionStatusStmt != nil {
		if cerr := q.updateDistributionStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDistributionStatusStmt: %w", cerr)
		}
	}
	if q.updateLocationStmt != nil {
		if cerr := q.updateLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLocationStmt: %w", cerr)
		}
	}
	if q.updateOrganizationStmt != nil {
		if cerr := q.updateOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrganizationStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updateProductStockParamsStmt != nil {
		if cerr := q.updateProductStockParamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStockParamsStmt: %w", cerr)
		}
	}
	if q.updatePurchaseOrderStatusStmt != nil {
		if cerr := q.updatePurchaseOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePurchaseOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateQAInspectionResultStmt != nil {
		if cerr := q.updateQAInspectionResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateQAInspectionResultStmt: %w", cerr)
		}
	}
	if q.updateScheduleLastRunStmt != nil {
		if cerr := q.updateScheduleLastRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateScheduleLastRunStmt: %w", cerr)
		}
	}
	if q.updateStockLevelStmt != nil {
		if cerr := q.updateStockLevelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStockLevelStmt: %w", cerr)
		}
	}
	if q.updateSupplierStmt != nil {
		if cerr := q.updateSupplierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSupplierStmt: %w", cerr)
		}
	}
	if q.updateSyncLogStmt != nil {
		if cerr := q.updateSyncLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSyncLogStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	acknowledgeAlertStmt            *sql.Stmt
	addCustodyChangeStmt            *sql.Stmt
	addDistributionLineItemStmt     *sql.Stmt
	addMaintenanceRecordStmt        *sql.Stmt
	addPOLineItemStmt               *sql.Stmt
	countProductsStmt               *sql.Stmt
	createAMCCalculationStmt        *sql.Stmt
	createAdjustmentStmt            *sql.Stmt
	createAdjustmentLineItemStmt    *sql.Stmt
	createAlertStmt                 *sql.Stmt
	createAlertConfigurationStmt    *sql.Stmt
	createAssetStmt                 *sql.Stmt
	createAuditLogStmt              *sql.Stmt
	createBatchStmt                 *sql.Stmt
	createCategoryStmt              *sql.Stmt
	createDataChangeLogStmt         *sql.Stmt
	createDepartmentStmt            *sql.Stmt
	createDistributionStmt          *sql.Stmt
	createForecastResultStmt        *sql.Stmt
	createGRNStmt                   *sql.Stmt
	createGRNLineItemStmt           *sql.Stmt
	createIssueLineItemStmt         *sql.Stmt
	createLocationStmt              *sql.Stmt
	createOrgLevelStmt              *sql.Stmt
	createOrganizationStmt          *sql.Stmt
	createProductStmt               *sql.Stmt
	createProgramStmt               *sql.Stmt
	createPurchaseOrderStmt         *sql.Stmt
	createQAChecklistItemStmt       *sql.Stmt
	createQAChecklistTemplateStmt   *sql.Stmt
	createQAInspectionStmt          *sql.Stmt
	createReorderRecommendationStmt *sql.Stmt
	createReportDefinitionStmt      *sql.Stmt
	createReportScheduleStmt        *sql.Stmt
	createRoleStmt                  *sql.Stmt
	createStockIssueStmt            *sql.Stmt
	createStockMovementStmt         *sql.Stmt
	createSupplierStmt              *sql.Stmt
	createSyncConflictStmt          *sql.Stmt
	createSyncLogStmt               *sql.Stmt
	createTransferStmt              *sql.Stmt
	createTransferLineItemStmt      *sql.Stmt
	createUserStmt                  *sql.Stmt
	createWarehouseStmt             *sql.Stmt
	deleteCategoryStmt              *sql.Stmt
	deleteProductStmt               *sql.Stmt
	getActiveAlertsStmt             *sql.Stmt
	getAdjustmentStmt               *sql.Stmt
	getAssetStmt                    *sql.Stmt
	getBatchesByProductStmt         *sql.Stmt
	getCategoryStmt                 *sql.Stmt
	getDistributionStmt             *sql.Stmt
	getExpiringBatchesStmt          *sql.Stmt
	getGRNStmt                      *sql.Stmt
	getLatestAMCStmt                *sql.Stmt
	getOrgTreeStmt                  *sql.Stmt
	getOrganizationStmt             *sql.Stmt
	getPendingConflictsStmt         *sql.Stmt
	getProductStmt                  *sql.Stmt
	getProductBySKUStmt             *sql.Stmt
	getPurchaseOrderStmt            *sql.Stmt
	getQAChecklistTemplateStmt      *sql.Stmt
	getQAInspectionStmt             *sql.Stmt
	getReportDefinitionStmt         *sql.Stmt
	getStockIssueStmt               *sql.Stmt
	getStockLevelStmt               *sql.Stmt
	getStockLevelsStmt              *sql.Stmt
	getStockMovementsStmt           *sql.Stmt
	getSupplierStmt                 *sql.Stmt
	getTransferStmt                 *sql.Stmt
	getUserStmt                     *sql.Stmt
	getUserByEmailStmt              *sql.Stmt
	getUserPermissionsStmt          *sql.Stmt
	getWarehouseStmt                *sql.Stmt
	getWarehouseWithLocationsStmt   *sql.Stmt
	listAMCCalculationsStmt         *sql.Stmt
	listAdjustmentReasonCodesStmt   *sql.Stmt
	listAdjustmentsStmt             *sql.Stmt
	listAlertConfigurationsStmt     *sql.Stmt
	listAlertsStmt                  *sql.Stmt
	listAssetCustodyChangesStmt     *sql.Stmt
	listAssetDepreciationStmt       *sql.Stmt
	listAssetMaintenanceStmt        *sql.Stmt
	listAssetsStmt                  *sql.Stmt
	listAuditLogsStmt               *sql.Stmt
	listCategoriesStmt              *sql.Stmt
	listCategoryTreeStmt            *sql.Stmt
	listDepartmentsStmt             *sql.Stmt
	listDistributionLineItemsStmt   *sql.Stmt
	listDistributionsStmt           *sql.Stmt
	listForecastResultsStmt         *sql.Stmt
	listGRNLineItemsStmt            *sql.Stmt
	listGRNsStmt                    *sql.Stmt
	listIssueLineItemsStmt          *sql.Stmt
	listLocationsStmt               *sql.Stmt
	listOrgLevelsStmt               *sql.Stmt
	listOrganizationsStmt           *sql.Stmt
	listPOLineItemsStmt             *sql.Stmt
	listPermissionsStmt             *sql.Stmt
	listProductsStmt                *sql.Stmt
	listProductsByCategoryStmt      *sql.Stmt
	listProgramsStmt                *sql.Stmt
	listPurchaseOrdersStmt          *sql.Stmt
	listQAChecklistItemsStmt        *sql.Stmt
	listQAChecklistTemplatesStmt    *sql.Stmt
	listQAInspectionsStmt           *sql.Stmt
	listReorderRecommendationsStmt  *sql.Stmt
	listReportDefinitionsStmt       *sql.Stmt
	listReportSchedulesStmt         *sql.Stmt
	listRolesStmt                   *sql.Stmt
	listStockIssuesStmt             *sql.Stmt
	listSuppliersStmt               *sql.Stmt
	listTransferLineItemsStmt       *sql.Stmt
	listTransfersStmt               *sql.Stmt
	listUsersStmt                   *sql.Stmt
	listWarehousesStmt              *sql.Stmt
	listWarehousesByTypeStmt        *sql.Stmt
	markRecommendationReviewedStmt  *sql.Stmt
	resolveAlertStmt                *sql.Stmt
	resolveSyncConflictStmt         *sql.Stmt
	searchAuditLogsStmt             *sql.Stmt
	searchProductsStmt              *sql.Stmt
	searchStockMovementsStmt        *sql.Stmt
	updateAssetStmt                 *sql.Stmt
	updateCategoryStmt              *sql.Stmt
	updateDistributionStatusStmt    *sql.Stmt
	updateLocationStmt              *sql.Stmt
	updateOrganizationStmt          *sql.Stmt
	updateProductStmt               *sql.Stmt
	updateProductStockParamsStmt    *sql.Stmt
	updatePurchaseOrderStatusStmt   *sql.Stmt
	updateQAInspectionResultStmt    *sql.Stmt
	updateScheduleLastRunStmt       *sql.Stmt
	updateStockLevelStmt            *sql.Stmt
	updateSupplierStmt              *sql.Stmt
	updateSyncLogStmt               *sql.Stmt
	updateUserStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		acknowledgeAlertStmt:            q.acknowledgeAlertStmt,
		addCustodyChangeStmt:            q.addCustodyChangeStmt,
		addDistributionLineItemStmt:     q.addDistributionLineItemStmt,
		addMaintenanceRecordStmt:        q.addMaintenanceRecordStmt,
		addPOLineItemStmt:               q.addPOLineItemStmt,
		countProductsStmt:               q.countProductsStmt,
		createAMCCalculationStmt:        q.createAMCCalculationStmt,
		createAdjustmentStmt:            q.createAdjustmentStmt,
		createAdjustmentLineItemStmt:    q.createAdjustmentLineItemStmt,
		createAlertStmt:                 q.createAlertStmt,
		createAlertConfigurationStmt:    q.createAlertConfigurationStmt,
		createAssetStmt:                 q.createAssetStmt,
		createAuditLogStmt:              q.createAuditLogStmt,
		createBatchStmt:                 q.createBatchStmt,
		createCategoryStmt:              q.createCategoryStmt,
		createDataChangeLogStmt:         q.createDataChangeLogStmt,
		createDepartmentStmt:            q.createDepartmentStmt,
		createDistributionStmt:          q.createDistributionStmt,
		createForecastResultStmt:        q.createForecastResultStmt,
		createGRNStmt:                   q.createGRNStmt,
		createGRNLineItemStmt:           q.createGRNLineItemStmt,
		createIssueLineItemStmt:         q.createIssueLineItemStmt,
		createLocationStmt:              q.createLocationStmt,
		createOrgLevelStmt:              q.createOrgLevelStmt,
		createOrganizationStmt:          q.createOrganizationStmt,
		createProductStmt:               q.createProductStmt,
		createProgramStmt:               q.createProgramStmt,
		createPurchaseOrderStmt:         q.createPurchaseOrderStmt,
		createQAChecklistItemStmt:       q.createQAChecklistItemStmt,
		createQAChecklistTemplateStmt:   q.createQAChecklistTemplateStmt,
		createQAInspectionStmt:          q.createQAInspectionStmt,
		createReorderRecommendationStmt: q.createReorderRecommendationStmt,
		createReportDefinitionStmt:      q.createReportDefinitionStmt,
		createReportScheduleStmt:        q.createReportScheduleStmt,
		createRoleStmt:                  q.createRoleStmt,
		createStockIssueStmt:            q.createStockIssueStmt,
		createStockMovementStmt:         q.createStockMovementStmt,
		createSupplierStmt:              q.createSupplierStmt,
		createSyncConflictStmt:          q.createSyncConflictStmt,
		createSyncLogStmt:               q.createSyncLogStmt,
		createTransferStmt:              q.createTransferStmt,
		createTransferLineItemStmt:      q.createTransferLineItemStmt,
		createUserStmt:                  q.createUserStmt,
		createWarehouseStmt:             q.createWarehouseStmt,
		deleteCategoryStmt:              q.deleteCategoryStmt,
		deleteProductStmt:               q.deleteProductStmt,
		getActiveAlertsStmt:             q.getActiveAlertsStmt,
		getAdjustmentStmt:               q.getAdjustmentStmt,
		getAssetStmt:                    q.getAssetStmt,
		getBatchesByProductStmt:         q.getBatchesByProductStmt,
		getCategoryStmt:                 q.getCategoryStmt,
		getDistributionStmt:             q.getDistributionStmt,
		getExpiringBatchesStmt:          q.getExpiringBatchesStmt,
		getGRNStmt:                      q.getGRNStmt,
		getLatestAMCStmt:                q.getLatestAMCStmt,
		getOrgTreeStmt:                  q.getOrgTreeStmt,
		getOrganizationStmt:             q.getOrganizationStmt,
		getPendingConflictsStmt:         q.getPendingConflictsStmt,
		getProductStmt:                  q.getProductStmt,
		getProductBySKUStmt:             q.getProductBySKUStmt,
		getPurchaseOrderStmt:            q.getPurchaseOrderStmt,
		getQAChecklistTemplateStmt:      q.getQAChecklistTemplateStmt,
		getQAInspectionStmt:             q.getQAInspectionStmt,
		getReportDefinitionStmt:         q.getReportDefinitionStmt,
		getStockIssueStmt:               q.getStockIssueStmt,
		getStockLevelStmt:               q.getStockLevelStmt,
		getStockLevelsStmt:              q.getStockLevelsStmt,
		getStockMovementsStmt:           q.getStockMovementsStmt,
		getSupplierStmt:                 q.getSupplierStmt,
		getTransferStmt:                 q.getTransferStmt,
		getUserStmt:                     q.getUserStmt,
		getUserByEmailStmt:              q.getUserByEmailStmt,
		getUserPermissionsStmt:          q.getUserPermissionsStmt,
		getWarehouseStmt:                q.getWarehouseStmt,
		getWarehouseWithLocationsStmt:   q.getWarehouseWithLocationsStmt,
		listAMCCalculationsStmt:         q.listAMCCalculationsStmt,
		listAdjustmentReasonCodesStmt:   q.listAdjustmentReasonCodesStmt,
		listAdjustmentsStmt:             q.listAdjustmentsStmt,
		listAlertConfigurationsStmt:     q.listAlertConfigurationsStmt,
		listAlertsStmt:                  q.listAlertsStmt,
		listAssetCustodyChangesStmt:     q.listAssetCustodyChangesStmt,
		listAssetDepreciationStmt:       q.listAssetDepreciationStmt,
		listAssetMaintenanceStmt:        q.listAssetMaintenanceStmt,
		listAssetsStmt:                  q.listAssetsStmt,
		listAuditLogsStmt:               q.listAuditLogsStmt,
		listCategoriesStmt:              q.listCategoriesStmt,
		listCategoryTreeStmt:            q.listCategoryTreeStmt,
		listDepartmentsStmt:             q.listDepartmentsStmt,
		listDistributionLineItemsStmt:   q.listDistributionLineItemsStmt,
		listDistributionsStmt:           q.listDistributionsStmt,
		listForecastResultsStmt:         q.listForecastResultsStmt,
		listGRNLineItemsStmt:            q.listGRNLineItemsStmt,
		listGRNsStmt:                    q.listGRNsStmt,
		listIssueLineItemsStmt:          q.listIssueLineItemsStmt,
		listLocationsStmt:               q.listLocationsStmt,
		listOrgLevelsStmt:               q.listOrgLevelsStmt,
		listOrganizationsStmt:           q.listOrganizationsStmt,
		listPOLineItemsStmt:             q.listPOLineItemsStmt,
		listPermissionsStmt:             q.listPermissionsStmt,
		listProductsStmt:                q.listProductsStmt,
		listProductsByCategoryStmt:      q.listProductsByCategoryStmt,
		listProgramsStmt:                q.listProgramsStmt,
		listPurchaseOrdersStmt:          q.listPurchaseOrdersStmt,
		listQAChecklistItemsStmt:        q.listQAChecklistItemsStmt,
		listQAChecklistTemplatesStmt:    q.listQAChecklistTemplatesStmt,
		listQAInspectionsStmt:           q.listQAInspectionsStmt,
		listReorderRecommendationsStmt:  q.listReorderRecommendationsStmt,
		listReportDefinitionsStmt:       q.listReportDefinitionsStmt,
		listReportSchedulesStmt:         q.listReportSchedulesStmt,
		listRolesStmt:                   q.listRolesStmt,
		listStockIssuesStmt:             q.listStockIssuesStmt,
		listSuppliersStmt:               q.listSuppliersStmt,
		listTransferLineItemsStmt:       q.listTransferLineItemsStmt,
		listTransfersStmt:               q.listTransfersStmt,
		listUsersStmt:                   q.listUsersStmt,
		listWarehousesStmt:              q.listWarehousesStmt,
		listWarehousesByTypeStmt:        q.listWarehousesByTypeStmt,
		markRecommendationReviewedStmt:  q.markRecommendationReviewedStmt,
		resolveAlertStmt:                q.resolveAlertStmt,
		resolveSyncConflictStmt:         q.resolveSyncConflictStmt,
		searchAuditLogsStmt:             q.searchAuditLogsStmt,
		searchProductsStmt:              q.searchProductsStmt,
		searchStockMovementsStmt:        q.searchStockMovementsStmt,
		updateAssetStmt:                 q.updateAssetStmt,
		updateCategoryStmt:              q.updateCategoryStmt,
		updateDistributionStatusStmt:    q.updateDistributionStatusStmt,
		updateLocationStmt:              q.updateLocationStmt,
		updateOrganizationStmt:          q.updateOrganizationStmt,
		updateProductStmt:               q.updateProductStmt,
		updateProductStockParamsStmt:    q.updateProductStockParamsStmt,
		updatePurchaseOrderStatusStmt:   q.updatePurchaseOrderStatusStmt,
		updateQAInspectionResultStmt:    q.updateQAInspectionResultStmt,
		updateScheduleLastRunStmt:       q.updateScheduleLastRunStmt,
		updateStockLevelStmt:            q.updateStockLevelStmt,
		updateSupplierStmt:              q.updateSupplierStmt,
		updateSyncLogStmt:               q.updateSyncLogStmt,
		updateUserStmt:                  q.updateUserStmt,
	}
}
