// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: distribution.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addDistributionLineItem = `-- name: AddDistributionLineItem :one
INSERT INTO distribution_line_items (distribution_id, product_id, batch_id, quantity_planned, quantity_distributed, unit_cost, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, distribution_id, product_id, batch_id, quantity_planned, quantity_distributed, unit_cost, status
`

type AddDistributionLineItemParams struct {
	DistributionID      string         `json:"distribution_id"`
	ProductID           string         `json:"product_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	QuantityPlanned     string         `json:"quantity_planned"`
	QuantityDistributed string         `json:"quantity_distributed"`
	UnitCost            sql.NullString `json:"unit_cost"`
	Status              EntityStatus   `json:"status"`
}

func (q *Queries) AddDistributionLineItem(ctx context.Context, arg AddDistributionLineItemParams) (DistributionLineItem, error) {
	row := q.queryRow(ctx, q.addDistributionLineItemStmt, addDistributionLineItem,
		arg.DistributionID,
		arg.ProductID,
		arg.BatchID,
		arg.QuantityPlanned,
		arg.QuantityDistributed,
		arg.UnitCost,
		arg.Status,
	)
	var i DistributionLineItem
	err := row.Scan(
		&i.ID,
		&i.DistributionID,
		&i.ProductID,
		&i.BatchID,
		&i.QuantityPlanned,
		&i.QuantityDistributed,
		&i.UnitCost,
		&i.Status,
	)
	return i, err
}

const createDistribution = `-- name: CreateDistribution :one
INSERT INTO distributions (org_id, org_level_id, program_id, distribution_number, distribution_date, location, beneficiary_count, status, notes, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, org_level_id, program_id, distribution_number, distribution_date, location, beneficiary_count, status, notes, created_by, updated_by, created_at, updated_at
`

type CreateDistributionParams struct {
	OrgID              string         `json:"org_id"`
	OrgLevelID         uuid.NullUUID  `json:"org_level_id"`
	ProgramID          uuid.NullUUID  `json:"program_id"`
	DistributionNumber string         `json:"distribution_number"`
	DistributionDate   time.Time      `json:"distribution_date"`
	Location           sql.NullString `json:"location"`
	BeneficiaryCount   sql.NullInt32  `json:"beneficiary_count"`
	Status             EntityStatus   `json:"status"`
	Notes              sql.NullString `json:"notes"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateDistribution(ctx context.Context, arg CreateDistributionParams) (Distribution, error) {
	row := q.queryRow(ctx, q.createDistributionStmt, createDistribution,
		arg.OrgID,
		arg.OrgLevelID,
		arg.ProgramID,
		arg.DistributionNumber,
		arg.DistributionDate,
		arg.Location,
		arg.BeneficiaryCount,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Distribution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgLevelID,
		&i.ProgramID,
		&i.DistributionNumber,
		&i.DistributionDate,
		&i.Location,
		&i.BeneficiaryCount,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistribution = `-- name: GetDistribution :one
SELECT d.id, d.org_id, d.org_level_id, d.program_id, d.distribution_number, d.distribution_date, d.location, d.beneficiary_count, d.status, d.notes, d.created_by, d.updated_by, d.created_at, d.updated_at, ol.name as org_level_name, p.name as program_name
FROM distributions d
LEFT JOIN org_levels ol ON d.org_level_id = ol.id
LEFT JOIN programs p ON d.program_id = p.id
WHERE d.id = $1 AND d.org_id = $2
`

type GetDistributionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetDistributionRow struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	OrgLevelID         uuid.NullUUID  `json:"org_level_id"`
	ProgramID          uuid.NullUUID  `json:"program_id"`
	DistributionNumber string         `json:"distribution_number"`
	DistributionDate   time.Time      `json:"distribution_date"`
	Location           sql.NullString `json:"location"`
	BeneficiaryCount   sql.NullInt32  `json:"beneficiary_count"`
	Status             EntityStatus   `json:"status"`
	Notes              sql.NullString `json:"notes"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	OrgLevelName       sql.NullString `json:"org_level_name"`
	ProgramName        sql.NullString `json:"program_name"`
}

func (q *Queries) GetDistribution(ctx context.Context, arg GetDistributionParams) (GetDistributionRow, error) {
	row := q.queryRow(ctx, q.getDistributionStmt, getDistribution, arg.ID, arg.OrgID)
	var i GetDistributionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgLevelID,
		&i.ProgramID,
		&i.DistributionNumber,
		&i.DistributionDate,
		&i.Location,
		&i.BeneficiaryCount,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgLevelName,
		&i.ProgramName,
	)
	return i, err
}

const listDistributionLineItems = `-- name: ListDistributionLineItems :many
SELECT dli.id, dli.distribution_id, dli.product_id, dli.batch_id, dli.quantity_planned, dli.quantity_distributed, dli.unit_cost, dli.status, p.name as product_name, p.sku as product_sku
FROM distribution_line_items dli
JOIN products p ON dli.product_id = p.id
WHERE dli.distribution_id = $1
ORDER BY dli.id
`

type ListDistributionLineItemsRow struct {
	ID                  string         `json:"id"`
	DistributionID      string         `json:"distribution_id"`
	ProductID           string         `json:"product_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	QuantityPlanned     string         `json:"quantity_planned"`
	QuantityDistributed string         `json:"quantity_distributed"`
	UnitCost            sql.NullString `json:"unit_cost"`
	Status              EntityStatus   `json:"status"`
	ProductName         string         `json:"product_name"`
	ProductSku          string         `json:"product_sku"`
}

func (q *Queries) ListDistributionLineItems(ctx context.Context, distributionID string) ([]ListDistributionLineItemsRow, error) {
	rows, err := q.query(ctx, q.listDistributionLineItemsStmt, listDistributionLineItems, distributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistributionLineItemsRow{}
	for rows.Next() {
		var i ListDistributionLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DistributionID,
			&i.ProductID,
			&i.BatchID,
			&i.QuantityPlanned,
			&i.QuantityDistributed,
			&i.UnitCost,
			&i.Status,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributions = `-- name: ListDistributions :many
SELECT d.id, d.org_id, d.org_level_id, d.program_id, d.distribution_number, d.distribution_date, d.location, d.beneficiary_count, d.status, d.notes, d.created_by, d.updated_by, d.created_at, d.updated_at, ol.name as org_level_name, p.name as program_name
FROM distributions d
LEFT JOIN org_levels ol ON d.org_level_id = ol.id
LEFT JOIN programs p ON d.program_id = p.id
WHERE d.org_id = $1
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDistributionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListDistributionsRow struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	OrgLevelID         uuid.NullUUID  `json:"org_level_id"`
	ProgramID          uuid.NullUUID  `json:"program_id"`
	DistributionNumber string         `json:"distribution_number"`
	DistributionDate   time.Time      `json:"distribution_date"`
	Location           sql.NullString `json:"location"`
	BeneficiaryCount   sql.NullInt32  `json:"beneficiary_count"`
	Status             EntityStatus   `json:"status"`
	Notes              sql.NullString `json:"notes"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	OrgLevelName       sql.NullString `json:"org_level_name"`
	ProgramName        sql.NullString `json:"program_name"`
}

func (q *Queries) ListDistributions(ctx context.Context, arg ListDistributionsParams) ([]ListDistributionsRow, error) {
	rows, err := q.query(ctx, q.listDistributionsStmt, listDistributions, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistributionsRow{}
	for rows.Next() {
		var i ListDistributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgLevelID,
			&i.ProgramID,
			&i.DistributionNumber,
			&i.DistributionDate,
			&i.Location,
			&i.BeneficiaryCount,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgLevelName,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDistributionStatus = `-- name: UpdateDistributionStatus :exec
UPDATE distributions SET
    status = $1::entity_status, updated_by = $2
WHERE id = $3 AND org_id = $4
`

type UpdateDistributionStatusParams struct {
	Column1   EntityStatus   `json:"column_1"`
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
}

func (q *Queries) UpdateDistributionStatus(ctx context.Context, arg UpdateDistributionStatusParams) error {
	_, err := q.exec(ctx, q.updateDistributionStatusStmt, updateDistributionStatus,
		arg.Column1,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
