// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DocType string

const (
	DocTypeGrn        DocType = "grn"
	DocTypeSrf        DocType = "srf"
	DocTypeTransfer   DocType = "transfer"
	DocTypeAdjustment DocType = "adjustment"
	DocTypeDisposal   DocType = "disposal"
	DocTypeReturn     DocType = "return"
)

func (e *DocType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocType(s)
	case string:
		*e = DocType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocType: %T", src)
	}
	return nil
}

type NullDocType struct {
	DocType DocType `json:"doc_type"`
	Valid   bool    `json:"valid"` // Valid is true if DocType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocType) Scan(value interface{}) error {
	if value == nil {
		ns.DocType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocType), nil
}

type EntityStatus string

const (
	EntityStatusActive   EntityStatus = "active"
	EntityStatusInactive EntityStatus = "inactive"
	EntityStatusDraft    EntityStatus = "draft"
	EntityStatusArchived EntityStatus = "archived"
)

func (e *EntityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityStatus(s)
	case string:
		*e = EntityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityStatus: %T", src)
	}
	return nil
}

type NullEntityStatus struct {
	EntityStatus EntityStatus `json:"entity_status"`
	Valid        bool         `json:"valid"` // Valid is true if EntityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EntityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityStatus), nil
}

type ItemType string

const (
	ItemTypeDrug          ItemType = "drug"
	ItemTypeMedicalSupply ItemType = "medical_supply"
	ItemTypeEquipment     ItemType = "equipment"
	ItemTypeInstrument    ItemType = "instrument"
	ItemTypeMaterial      ItemType = "material"
	ItemTypeVaccine       ItemType = "vaccine"
	ItemTypeNutrition     ItemType = "nutrition"
	ItemTypeLabReagent    ItemType = "lab_reagent"
	ItemTypeAsset         ItemType = "asset"
	ItemTypeConsumable    ItemType = "consumable"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType `json:"item_type"`
	Valid    bool     `json:"valid"` // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type LocationType string

const (
	LocationTypeZone  LocationType = "zone"
	LocationTypeRack  LocationType = "rack"
	LocationTypeBin   LocationType = "bin"
	LocationTypeShelf LocationType = "shelf"
	LocationTypeArea  LocationType = "area"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType `json:"location_type"`
	Valid        bool         `json:"valid"` // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

type MovementType string

const (
	MovementTypeReceipt            MovementType = "receipt"
	MovementTypeIssue              MovementType = "issue"
	MovementTypeTransferIn         MovementType = "transfer_in"
	MovementTypeTransferOut        MovementType = "transfer_out"
	MovementTypeAdjustmentAdd      MovementType = "adjustment_add"
	MovementTypeAdjustmentSubtract MovementType = "adjustment_subtract"
	MovementTypeReturn             MovementType = "return"
	MovementTypeDisposal           MovementType = "disposal"
)

func (e *MovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementType(s)
	case string:
		*e = MovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementType: %T", src)
	}
	return nil
}

type NullMovementType struct {
	MovementType MovementType `json:"movement_type"`
	Valid        bool         `json:"valid"` // Valid is true if MovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.MovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementType), nil
}

type StockStatus string

const (
	StockStatusOnHand      StockStatus = "on_hand"
	StockStatusReserved    StockStatus = "reserved"
	StockStatusInTransit   StockStatus = "in_transit"
	StockStatusOnHold      StockStatus = "on_hold"
	StockStatusDamaged     StockStatus = "damaged"
	StockStatusExpired     StockStatus = "expired"
	StockStatusQuarantined StockStatus = "quarantined"
	StockStatusDisposed    StockStatus = "disposed"
)

func (e *StockStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockStatus(s)
	case string:
		*e = StockStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StockStatus: %T", src)
	}
	return nil
}

type NullStockStatus struct {
	StockStatus StockStatus `json:"stock_status"`
	Valid       bool        `json:"valid"` // Valid is true if StockStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StockStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockStatus), nil
}

type UomCategory string

const (
	UomCategoryCount  UomCategory = "count"
	UomCategoryWeight UomCategory = "weight"
	UomCategoryVolume UomCategory = "volume"
	UomCategoryLength UomCategory = "length"
	UomCategoryTime   UomCategory = "time"
	UomCategoryArea   UomCategory = "area"
)

func (e *UomCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UomCategory(s)
	case string:
		*e = UomCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for UomCategory: %T", src)
	}
	return nil
}

type NullUomCategory struct {
	UomCategory UomCategory `json:"uom_category"`
	Valid       bool        `json:"valid"` // Valid is true if UomCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUomCategory) Scan(value interface{}) error {
	if value == nil {
		ns.UomCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UomCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUomCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UomCategory), nil
}

type WarehouseType string

const (
	WarehouseTypeCentral      WarehouseType = "central"
	WarehouseTypeSubWarehouse WarehouseType = "sub_warehouse"
	WarehouseTypeTransit      WarehouseType = "transit"
	WarehouseTypeQuarantine   WarehouseType = "quarantine"
)

func (e *WarehouseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarehouseType(s)
	case string:
		*e = WarehouseType(s)
	default:
		return fmt.Errorf("unsupported scan type for WarehouseType: %T", src)
	}
	return nil
}

type NullWarehouseType struct {
	WarehouseType WarehouseType `json:"warehouse_type"`
	Valid         bool          `json:"valid"` // Valid is true if WarehouseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarehouseType) Scan(value interface{}) error {
	if value == nil {
		ns.WarehouseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarehouseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarehouseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarehouseType), nil
}

type AdjustmentLineItem struct {
	ID               string         `json:"id"`
	AdjustmentID     string         `json:"adjustment_id"`
	ProductID        string         `json:"product_id"`
	BatchID          uuid.NullUUID  `json:"batch_id"`
	LocationID       uuid.NullUUID  `json:"location_id"`
	ExpectedQuantity string         `json:"expected_quantity"`
	ActualQuantity   string         `json:"actual_quantity"`
	Difference       string         `json:"difference"`
	ReasonCode       sql.NullString `json:"reason_code"`
	UnitCost         sql.NullString `json:"unit_cost"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
}

type AdjustmentReasonCode struct {
	Code             string    `json:"code"`
	Category         string    `json:"category"`
	Description      string    `json:"description"`
	RequiresApproval bool      `json:"requires_approval"`
	IsActive         bool      `json:"is_active"`
	CreatedAt        time.Time `json:"created_at"`
}

type Alert struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	AlertConfigID  uuid.NullUUID  `json:"alert_config_id"`
	AlertType      string         `json:"alert_type"`
	Severity       sql.NullString `json:"severity"`
	Title          string         `json:"title"`
	Message        string         `json:"message"`
	ProductID      uuid.NullUUID  `json:"product_id"`
	WarehouseID    uuid.NullUUID  `json:"warehouse_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	IsRead         bool           `json:"is_read"`
	IsAcknowledged bool           `json:"is_acknowledged"`
	AcknowledgedBy sql.NullString `json:"acknowledged_by"`
	AcknowledgedAt sql.NullTime   `json:"acknowledged_at"`
	ResolvedAt     sql.NullTime   `json:"resolved_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type AlertConfiguration struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	AlertType            string         `json:"alert_type"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	ThresholdType        sql.NullString `json:"threshold_type"`
	ThresholdValue       string         `json:"threshold_value"`
	Enabled              bool           `json:"enabled"`
	NotificationChannels string         `json:"notification_channels"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type AlertRecipient struct {
	ID                  string `json:"id"`
	AlertConfigID       string `json:"alert_config_id"`
	UserID              string `json:"user_id"`
	NotificationChannel string `json:"notification_channel"`
	IsActive            bool   `json:"is_active"`
}

type AmcCalculation struct {
	ID                     string         `json:"id"`
	OrgID                  string         `json:"org_id"`
	ProductID              string         `json:"product_id"`
	WarehouseID            string         `json:"warehouse_id"`
	CalculationDate        time.Time      `json:"calculation_date"`
	Amc3Months             sql.NullString `json:"amc_3_months"`
	Amc6Months             sql.NullString `json:"amc_6_months"`
	Amc12Months            sql.NullString `json:"amc_12_months"`
	MaxConsumption         sql.NullString `json:"max_consumption"`
	StdDeviation           sql.NullString `json:"std_deviation"`
	CalculationPeriodStart sql.NullTime   `json:"calculation_period_start"`
	CalculationPeriodEnd   sql.NullTime   `json:"calculation_period_end"`
	CalculationStatus      string         `json:"calculation_status"`
	CreatedAt              time.Time      `json:"created_at"`
}

type Asset struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	AssetTag           string         `json:"asset_tag"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	SerialNumber       sql.NullString `json:"serial_number"`
	CustodianID        uuid.NullUUID  `json:"custodian_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	AcquisitionDate    sql.NullTime   `json:"acquisition_date"`
	PurchaseCost       sql.NullString `json:"purchase_cost"`
	CurrentValue       sql.NullString `json:"current_value"`
	DepreciationMethod sql.NullString `json:"depreciation_method"`
	UsefulLifeYears    sql.NullInt32  `json:"useful_life_years"`
	Status             string         `json:"status"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type AssetAttachment struct {
	ID          string         `json:"id"`
	AssetID     string         `json:"asset_id"`
	FileName    string         `json:"file_name"`
	FileType    sql.NullString `json:"file_type"`
	FileUrl     string         `json:"file_url"`
	Description sql.NullString `json:"description"`
	UploadedAt  time.Time      `json:"uploaded_at"`
}

type AssetCustodyChange struct {
	ID         string         `json:"id"`
	AssetID    string         `json:"asset_id"`
	FromUserID uuid.NullUUID  `json:"from_user_id"`
	ToUserID   uuid.NullUUID  `json:"to_user_id"`
	ChangedBy  sql.NullString `json:"changed_by"`
	ChangedAt  time.Time      `json:"changed_at"`
}

type AssetDepreciationSchedule struct {
	ID                 string    `json:"id"`
	AssetID            string    `json:"asset_id"`
	PeriodDate         time.Time `json:"period_date"`
	DepreciationAmount string    `json:"depreciation_amount"`
	BookValueBefore    string    `json:"book_value_before"`
	BookValueAfter     string    `json:"book_value_after"`
	Method             string    `json:"method"`
	CreatedAt          time.Time `json:"created_at"`
}

type AssetMaintenance struct {
	ID              string         `json:"id"`
	AssetID         string         `json:"asset_id"`
	MaintenanceDate time.Time      `json:"maintenance_date"`
	Description     sql.NullString `json:"description"`
	Cost            sql.NullString `json:"cost"`
	PerformedBy     sql.NullString `json:"performed_by"`
	NextDate        sql.NullTime   `json:"next_date"`
	CreatedAt       time.Time      `json:"created_at"`
}

type AuditLog struct {
	ID         string                `json:"id"`
	OrgID      string                `json:"org_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   sql.NullString        `json:"entity_id"`
	Changes    pqtype.NullRawMessage `json:"changes"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	Timestamp  time.Time             `json:"timestamp"`
}

type Batch struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	ProductID    string         `json:"product_id"`
	BatchNumber  string         `json:"batch_number"`
	SerialNumber sql.NullString `json:"serial_number"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	Manufacturer sql.NullString `json:"manufacturer"`
	CreatedAt    time.Time      `json:"created_at"`
}

type CapaAction struct {
	ID                      string         `json:"id"`
	OrgID                   string         `json:"org_id"`
	CapaNumber              string         `json:"capa_number"`
	SourceType              string         `json:"source_type"`
	SourceID                sql.NullString `json:"source_id"`
	CapaType                string         `json:"capa_type"`
	Title                   string         `json:"title"`
	RootCause               sql.NullString `json:"root_cause"`
	ActionPlan              string         `json:"action_plan"`
	ResponsibleOwner        sql.NullString `json:"responsible_owner"`
	DueDate                 sql.NullTime   `json:"due_date"`
	Status                  string         `json:"status"`
	EffectivenessCheck      sql.NullString `json:"effectiveness_check"`
	EffectivenessVerified   bool           `json:"effectiveness_verified"`
	EffectivenessVerifiedBy sql.NullString `json:"effectiveness_verified_by"`
	VerifiedAt              sql.NullTime   `json:"verified_at"`
	ClosedBy                sql.NullString `json:"closed_by"`
	ClosedAt                sql.NullTime   `json:"closed_at"`
	CreatedBy               sql.NullString `json:"created_by"`
	UpdatedBy               sql.NullString `json:"updated_by"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type ChangeControl struct {
	ID                    string         `json:"id"`
	OrgID                 string         `json:"org_id"`
	ChangeNumber          string         `json:"change_number"`
	SubjectType           string         `json:"subject_type"`
	SubjectID             sql.NullString `json:"subject_id"`
	Description           string         `json:"description"`
	ImpactAssessment      sql.NullString `json:"impact_assessment"`
	RiskLevel             string         `json:"risk_level"`
	RequiresQualityReview bool           `json:"requires_quality_review"`
	AuthorizedBy          sql.NullString `json:"authorized_by"`
	AuthorizationDate     sql.NullTime   `json:"authorization_date"`
	StartDate             sql.NullTime   `json:"start_date"`
	EndDate               sql.NullTime   `json:"end_date"`
	Status                string         `json:"status"`
	ClosureEvidence       sql.NullString `json:"closure_evidence"`
	CreatedBy             sql.NullString `json:"created_by"`
	UpdatedBy             sql.NullString `json:"updated_by"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type Complaint struct {
	ID                         string         `json:"id"`
	OrgID                      string         `json:"org_id"`
	ComplaintNumber            string         `json:"complaint_number"`
	ReceivedDate               time.Time      `json:"received_date"`
	ReceivedVia                sql.NullString `json:"received_via"`
	Severity                   sql.NullString `json:"severity"`
	Category                   sql.NullString `json:"category"`
	ProductID                  uuid.NullUUID  `json:"product_id"`
	BatchID                    uuid.NullUUID  `json:"batch_id"`
	Description                string         `json:"description"`
	ReporterName               sql.NullString `json:"reporter_name"`
	ReporterContact            sql.NullString `json:"reporter_contact"`
	ImmediateEscalation        bool           `json:"immediate_escalation"`
	Escalated                  bool           `json:"escalated"`
	EscalatedTo                sql.NullString `json:"escalated_to"`
	ManufacturerNotified       bool           `json:"manufacturer_notified"`
	CompetentAuthorityNotified bool           `json:"competent_authority_notified"`
	Status                     string         `json:"status"`
	ResolutionNotes            sql.NullString `json:"resolution_notes"`
	CapaID                     uuid.NullUUID  `json:"capa_id"`
	CreatedBy                  sql.NullString `json:"created_by"`
	UpdatedBy                  sql.NullString `json:"updated_by"`
	CreatedAt                  time.Time      `json:"created_at"`
	UpdatedAt                  time.Time      `json:"updated_at"`
}

type ComplaintSeverity struct {
	Code                string         `json:"code"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	ImmediateEscalation bool           `json:"immediate_escalation"`
	SortOrder           int32          `json:"sort_order"`
	IsActive            bool           `json:"is_active"`
}

type ControlledStockRegister struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	ProductID           string         `json:"product_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	WarehouseID         string         `json:"warehouse_id"`
	RegisterDate        time.Time      `json:"register_date"`
	TransactionType     string         `json:"transaction_type"`
	ReferenceDocument   sql.NullString `json:"reference_document"`
	Quantity            string         `json:"quantity"`
	BalanceAfter        string         `json:"balance_after"`
	ReceivedFrom        sql.NullString `json:"received_from"`
	IssuedTo            sql.NullString `json:"issued_to"`
	AuthorizedRecipient sql.NullString `json:"authorized_recipient"`
	Signature           sql.NullString `json:"signature"`
	Discrepancy         string         `json:"discrepancy"`
	ReconciledAt        sql.NullTime   `json:"reconciled_at"`
	ReconciledBy        sql.NullString `json:"reconciled_by"`
	CreatedBy           sql.NullString `json:"created_by"`
	CreatedAt           time.Time      `json:"created_at"`
}

type CountLineItem struct {
	ID               string         `json:"id"`
	CountID          string         `json:"count_id"`
	ProductID        string         `json:"product_id"`
	LocationID       uuid.NullUUID  `json:"location_id"`
	BatchID          uuid.NullUUID  `json:"batch_id"`
	ExpectedQuantity string         `json:"expected_quantity"`
	CountedQuantity  string         `json:"counted_quantity"`
	Variance         string         `json:"variance"`
	VariancePercent  sql.NullString `json:"variance_percent"`
	Status           EntityStatus   `json:"status"`
	ReviewedBy       sql.NullString `json:"reviewed_by"`
	Notes            sql.NullString `json:"notes"`
}

type CountVarianceReconciliation struct {
	ID                 string         `json:"id"`
	CountLineItemID    string         `json:"count_line_item_id"`
	ReconciliationType sql.NullString `json:"reconciliation_type"`
	AdjustmentID       uuid.NullUUID  `json:"adjustment_id"`
	Reason             string         `json:"reason"`
	ApprovedBy         sql.NullString `json:"approved_by"`
	ApprovedAt         sql.NullTime   `json:"approved_at"`
	CreatedAt          time.Time      `json:"created_at"`
}

type DataChangeLog struct {
	ID              string                `json:"id"`
	OrgID           string                `json:"org_id"`
	TableName       string                `json:"table_name"`
	RecordID        string                `json:"record_id"`
	Operation       string                `json:"operation"`
	OldValues       pqtype.NullRawMessage `json:"old_values"`
	NewValues       pqtype.NullRawMessage `json:"new_values"`
	ChangedBy       string                `json:"changed_by"`
	ChangeTimestamp time.Time             `json:"change_timestamp"`
}

type DeliveryConfirmation struct {
	ID                    string         `json:"id"`
	OrgID                 string         `json:"org_id"`
	WaybillID             string         `json:"waybill_id"`
	ConfirmingWarehouseID uuid.NullUUID  `json:"confirming_warehouse_id"`
	RecipientName         sql.NullString `json:"recipient_name"`
	ConfirmedDate         time.Time      `json:"confirmed_date"`
	DeliveryStatus        string         `json:"delivery_status"`
	ItemsConformed        sql.NullBool   `json:"items_conformed"`
	QuantityConformed     sql.NullBool   `json:"quantity_conformed"`
	BatchConformed        sql.NullBool   `json:"batch_conformed"`
	ExpiryConformed       sql.NullBool   `json:"expiry_conformed"`
	ConditionConformed    sql.NullBool   `json:"condition_conformed"`
	TemperatureConformed  sql.NullBool   `json:"temperature_conformed"`
	UnfilledQuantity      sql.NullString `json:"unfilled_quantity"`
	Substitutions         sql.NullString `json:"substitutions"`
	Discrepancies         sql.NullString `json:"discrepancies"`
	FollowUpCommitments   sql.NullString `json:"follow_up_commitments"`
	ConfirmedBy           sql.NullString `json:"confirmed_by"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type Department struct {
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Deviation struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	DeviationNumber    string         `json:"deviation_number"`
	CategoryCode       sql.NullString `json:"category_code"`
	OccurredAt         time.Time      `json:"occurred_at"`
	ReportedAt         time.Time      `json:"reported_at"`
	SourceDocumentType sql.NullString `json:"source_document_type"`
	SourceDocumentID   sql.NullString `json:"source_document_id"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	BatchID            uuid.NullUUID  `json:"batch_id"`
	WarehouseID        uuid.NullUUID  `json:"warehouse_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	Description        string         `json:"description"`
	ContainmentAction  sql.NullString `json:"containment_action"`
	ImpactAssessment   sql.NullString `json:"impact_assessment"`
	RootCause          sql.NullString `json:"root_cause"`
	RiskRating         string         `json:"risk_rating"`
	Disposition        sql.NullString `json:"disposition"`
	Status             string         `json:"status"`
	ResponsibleOwner   sql.NullString `json:"responsible_owner"`
	DueDate            sql.NullTime   `json:"due_date"`
	Escalated          bool           `json:"escalated"`
	EscalatedTo        sql.NullString `json:"escalated_to"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type DeviationCategory struct {
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	DefaultRiskLevel string         `json:"default_risk_level"`
	SortOrder        int32          `json:"sort_order"`
	IsActive         bool           `json:"is_active"`
}

type DispatchWaybill struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	WaybillNumber        string         `json:"waybill_number"`
	IssueID              uuid.NullUUID  `json:"issue_id"`
	TransferID           uuid.NullUUID  `json:"transfer_id"`
	SenderWarehouseID    string         `json:"sender_warehouse_id"`
	RecipientWarehouseID uuid.NullUUID  `json:"recipient_warehouse_id"`
	Recipient            sql.NullString `json:"recipient"`
	DispatchDate         time.Time      `json:"dispatch_date"`
	Carrier              sql.NullString `json:"carrier"`
	VehicleNumber        sql.NullString `json:"vehicle_number"`
	CartonCount          sql.NullInt32  `json:"carton_count"`
	PackingListReference sql.NullString `json:"packing_list_reference"`
	StorageRequirement   sql.NullString `json:"storage_requirement"`
	TemperatureSensitive bool           `json:"temperature_sensitive"`
	Condition            sql.NullString `json:"condition"`
	DocumentRefs         sql.NullString `json:"document_refs"`
	Status               string         `json:"status"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type Disposal struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	WarehouseID        uuid.NullUUID  `json:"warehouse_id"`
	DisposalNumber     string         `json:"disposal_number"`
	DisposalDate       time.Time      `json:"disposal_date"`
	DisposalMethodCode sql.NullString `json:"disposal_method_code"`
	AuthorizedBy       sql.NullString `json:"authorized_by"`
	WitnessBy          sql.NullString `json:"witness_by"`
	Reason             sql.NullString `json:"reason"`
	Status             EntityStatus   `json:"status"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type DisposalLineItem struct {
	ID         string         `json:"id"`
	DisposalID string         `json:"disposal_id"`
	ProductID  string         `json:"product_id"`
	BatchID    uuid.NullUUID  `json:"batch_id"`
	Quantity   string         `json:"quantity"`
	UnitCost   sql.NullString `json:"unit_cost"`
	Notes      sql.NullString `json:"notes"`
}

type DisposalMethod struct {
	Code                string         `json:"code"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	RequiresWitness     bool           `json:"requires_witness"`
	EnvironmentalImpact sql.NullString `json:"environmental_impact"`
	IsActive            bool           `json:"is_active"`
}

type Distribution struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	OrgLevelID         uuid.NullUUID  `json:"org_level_id"`
	ProgramID          uuid.NullUUID  `json:"program_id"`
	DistributionNumber string         `json:"distribution_number"`
	DistributionDate   time.Time      `json:"distribution_date"`
	Location           sql.NullString `json:"location"`
	BeneficiaryCount   sql.NullInt32  `json:"beneficiary_count"`
	Status             EntityStatus   `json:"status"`
	Notes              sql.NullString `json:"notes"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type DistributionBeneficiary struct {
	ID              string         `json:"id"`
	DistributionID  string         `json:"distribution_id"`
	BeneficiaryType string         `json:"beneficiary_type"`
	Count           int32          `json:"count"`
	Criteria        sql.NullString `json:"criteria"`
}

type DistributionLineItem struct {
	ID                  string         `json:"id"`
	DistributionID      string         `json:"distribution_id"`
	ProductID           string         `json:"product_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	QuantityPlanned     string         `json:"quantity_planned"`
	QuantityDistributed string         `json:"quantity_distributed"`
	UnitCost            sql.NullString `json:"unit_cost"`
	Status              EntityStatus   `json:"status"`
}

type Donation struct {
	ID                      string         `json:"id"`
	OrgID                   string         `json:"org_id"`
	DonationNumber          string         `json:"donation_number"`
	DonorName               string         `json:"donor_name"`
	DonorContact            sql.NullString `json:"donor_contact"`
	OfferDate               time.Time      `json:"offer_date"`
	Decision                sql.NullString `json:"decision"`
	DecisionDate            sql.NullTime   `json:"decision_date"`
	DecidedBy               sql.NullString `json:"decided_by"`
	NeedsAssessment         sql.NullString `json:"needs_assessment"`
	ProposedRecipient       sql.NullString `json:"proposed_recipient"`
	ApprovalReference       sql.NullString `json:"approval_reference"`
	TransportResponsibility sql.NullString `json:"transport_responsibility"`
	CustomsNotes            sql.NullString `json:"customs_notes"`
	DisposalResponsibility  sql.NullString `json:"disposal_responsibility"`
	CertificateNumber       sql.NullString `json:"certificate_number"`
	CertificateIssuedDate   sql.NullTime   `json:"certificate_issued_date"`
	RegistryReference       sql.NullString `json:"registry_reference"`
	Status                  string         `json:"status"`
	Notes                   sql.NullString `json:"notes"`
	CreatedBy               sql.NullString `json:"created_by"`
	UpdatedBy               sql.NullString `json:"updated_by"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type DonationLineItem struct {
	ID                       string         `json:"id"`
	DonationID               string         `json:"donation_id"`
	ProductID                string         `json:"product_id"`
	BatchNumber              sql.NullString `json:"batch_number"`
	ExpiryDate               sql.NullTime   `json:"expiry_date"`
	Quantity                 string         `json:"quantity"`
	Uom                      sql.NullString `json:"uom"`
	RemainingShelfLifeMonths sql.NullInt32  `json:"remaining_shelf_life_months"`
	Condition                sql.NullString `json:"condition"`
	ShelfLifeCompliant       sql.NullBool   `json:"shelf_life_compliant"`
	Authorized               bool           `json:"authorized"`
	Notes                    sql.NullString `json:"notes"`
}

type DosageForm struct {
	Code              string        `json:"code"`
	Name              string        `json:"name"`
	Icon              string        `json:"icon"`
	Category          string        `json:"category"`
	IsParenteral      sql.NullBool  `json:"is_parenteral"`
	RequiresColdChain sql.NullBool  `json:"requires_cold_chain"`
	SortOrder         sql.NullInt32 `json:"sort_order"`
}

type EmergencyPlan struct {
	ID                     string         `json:"id"`
	OrgID                  string         `json:"org_id"`
	PlanNumber             string         `json:"plan_number"`
	Name                   string         `json:"name"`
	CountryCode            sql.NullString `json:"country_code"`
	FacilityID             uuid.NullUUID  `json:"facility_id"`
	ScenarioType           string         `json:"scenario_type"`
	Scenario               sql.NullString `json:"scenario"`
	DemandAssumptions      sql.NullString `json:"demand_assumptions"`
	ServiceLevel           sql.NullString `json:"service_level"`
	PrepositionedStockPlan sql.NullString `json:"prepositioned_stock_plan"`
	RotationPlan           sql.NullString `json:"rotation_plan"`
	AlternateSuppliers     sql.NullString `json:"alternate_suppliers"`
	AlternateWarehouses    sql.NullString `json:"alternate_warehouses"`
	AlternateRoutes        sql.NullString `json:"alternate_routes"`
	AlternatePowerSources  sql.NullString `json:"alternate_power_sources"`
	EmergencyAuthority     sql.NullString `json:"emergency_authority"`
	PaperFallbackRecords   bool           `json:"paper_fallback_records"`
	MinimumStaffing        sql.NullString `json:"minimum_staffing"`
	ColdChainContingency   sql.NullString `json:"cold_chain_contingency"`
	Communications         sql.NullString `json:"communications"`
	EscalationContacts     sql.NullString `json:"escalation_contacts"`
	SecurityControls       sql.NullString `json:"security_controls"`
	ReturnToNormalPlan     sql.NullString `json:"return_to_normal_plan"`
	Status                 string         `json:"status"`
	ApprovedBy             sql.NullString `json:"approved_by"`
	ApprovedAt             sql.NullTime   `json:"approved_at"`
	CreatedBy              sql.NullString `json:"created_by"`
	UpdatedBy              sql.NullString `json:"updated_by"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type Entity struct {
	ID          string                `json:"id"`
	OrgID       string                `json:"org_id"`
	FunctionID  uuid.NullUUID         `json:"function_id"`
	EntityType  string                `json:"entity_type"`
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	ParentID    uuid.NullUUID         `json:"parent_id"`
	Status      EntityStatus          `json:"status"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedBy   sql.NullString        `json:"created_by"`
	UpdatedBy   sql.NullString        `json:"updated_by"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type EntityAttribute struct {
	ID             string         `json:"id"`
	EntityID       string         `json:"entity_id"`
	AttributeName  string         `json:"attribute_name"`
	AttributeValue sql.NullString `json:"attribute_value"`
	AttributeType  string         `json:"attribute_type"`
	UomID          uuid.NullUUID  `json:"uom_id"`
	SortOrder      int32          `json:"sort_order"`
	IsRequired     bool           `json:"is_required"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type ForecastResult struct {
	ID              string                `json:"id"`
	OrgID           string                `json:"org_id"`
	ProductID       string                `json:"product_id"`
	WarehouseID     string                `json:"warehouse_id"`
	ForecastDate    time.Time             `json:"forecast_date"`
	ForecastValue   string                `json:"forecast_value"`
	LowerBound      sql.NullString        `json:"lower_bound"`
	UpperBound      sql.NullString        `json:"upper_bound"`
	ConfidenceLevel string                `json:"confidence_level"`
	ModelVersion    sql.NullString        `json:"model_version"`
	FeaturesUsed    pqtype.NullRawMessage `json:"features_used"`
	CreatedAt       time.Time             `json:"created_at"`
}

type Function struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	DepartmentID string         `json:"department_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Status       EntityStatus   `json:"status"`
	CreatedBy    sql.NullString `json:"created_by"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type GoodsReceipt struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	WarehouseID string         `json:"warehouse_id"`
	GrnNumber   string         `json:"grn_number"`
	Supplier    sql.NullString `json:"supplier"`
	PoNumber    sql.NullString `json:"po_number"`
	ReceivedBy  sql.NullString `json:"received_by"`
	Status      EntityStatus   `json:"status"`
	Notes       sql.NullString `json:"notes"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type GrnLineItem struct {
	ID           string         `json:"id"`
	GrnID        string         `json:"grn_id"`
	ProductID    string         `json:"product_id"`
	BatchNumber  sql.NullString `json:"batch_number"`
	SerialNumber sql.NullString `json:"serial_number"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	Quantity     string         `json:"quantity"`
	UnitCost     sql.NullString `json:"unit_cost"`
	Status       EntityStatus   `json:"status"`
}

type IssueLineItem struct {
	ID        string         `json:"id"`
	IssueID   string         `json:"issue_id"`
	ProductID string         `json:"product_id"`
	BatchID   uuid.NullUUID  `json:"batch_id"`
	Quantity  string         `json:"quantity"`
	UnitCost  sql.NullString `json:"unit_cost"`
}

type JustificationCode struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

type Location struct {
	ID          string         `json:"id"`
	WarehouseID string         `json:"warehouse_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Type        LocationType   `json:"type"`
	IsColdChain bool           `json:"is_cold_chain"`
	IsHazardous bool           `json:"is_hazardous"`
	IsSecure    bool           `json:"is_secure"`
	MaxCapacity sql.NullString `json:"max_capacity"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type LocationConstraint struct {
	LocationID         string         `json:"location_id"`
	MinTemperature     sql.NullString `json:"min_temperature"`
	MaxTemperature     sql.NullString `json:"max_temperature"`
	MinHumidity        sql.NullString `json:"min_humidity"`
	MaxHumidity        sql.NullString `json:"max_humidity"`
	IsHazardousAllowed bool           `json:"is_hazardous_allowed"`
	IsFoodGrade        bool           `json:"is_food_grade"`
	IsPharmaGrade      bool           `json:"is_pharma_grade"`
	MaxWeightCapacity  sql.NullString `json:"max_weight_capacity"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type OrgLevel struct {
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Level     int32          `json:"level"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Organization struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Permission struct {
	ID          string         `json:"id"`
	Module      string         `json:"module"`
	Action      string         `json:"action"`
	Description sql.NullString `json:"description"`
}

type PoLineItem struct {
	ID               string         `json:"id"`
	PoID             string         `json:"po_id"`
	ProductID        string         `json:"product_id"`
	LineNumber       int32          `json:"line_number"`
	QuantityOrdered  string         `json:"quantity_ordered"`
	QuantityReceived string         `json:"quantity_received"`
	UnitPrice        string         `json:"unit_price"`
	LineTotal        sql.NullString `json:"line_total"`
	DiscountPercent  string         `json:"discount_percent"`
	TaxPercent       string         `json:"tax_percent"`
	ScheduledDate    sql.NullTime   `json:"scheduled_date"`
	Status           EntityStatus   `json:"status"`
	Notes            sql.NullString `json:"notes"`
}

type Product struct {
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
	CategoryID      uuid.NullUUID  `json:"category_id"`
	UomID           uuid.NullUUID  `json:"uom_id"`
	Sku             string         `json:"sku"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	ItemType        ItemType       `json:"item_type"`
	Gtin            sql.NullString `json:"gtin"`
	AlternativeCode sql.NullString `json:"alternative_code"`
	Brand           sql.NullString `json:"brand"`
	Manufacturer    sql.NullString `json:"manufacturer"`
	IsBatchTracked  bool           `json:"is_batch_tracked"`
	IsSerialTracked bool           `json:"is_serial_tracked"`
	IsExpiryTracked bool           `json:"is_expiry_tracked"`
	IsHazardous     bool           `json:"is_hazardous"`
	IsColdChain     bool           `json:"is_cold_chain"`
	MinStock        string         `json:"min_stock"`
	MaxStock        string         `json:"max_stock"`
	ReorderPoint    string         `json:"reorder_point"`
	LeadTimeDays    int32          `json:"lead_time_days"`
	UnitCost        string         `json:"unit_cost"`
	Status          EntityStatus   `json:"status"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type ProductAttachment struct {
	ID          string         `json:"id"`
	ProductID   string         `json:"product_id"`
	FileName    string         `json:"file_name"`
	FileType    sql.NullString `json:"file_type"`
	FileUrl     string         `json:"file_url"`
	Description sql.NullString `json:"description"`
	UploadedBy  sql.NullString `json:"uploaded_by"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProductCategory struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Unspsc      sql.NullString `json:"unspsc"`
	Eclass      sql.NullString `json:"eclass"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProductPackaging struct {
	ID                 string         `json:"id"`
	ProductID          string         `json:"product_id"`
	UomID              string         `json:"uom_id"`
	PackageLevel       int32          `json:"package_level"`
	Quantity           string         `json:"quantity"`
	PackageDescription sql.NullString `json:"package_description"`
	Barcode            sql.NullString `json:"barcode"`
	Length             sql.NullString `json:"length"`
	Width              sql.NullString `json:"width"`
	Height             sql.NullString `json:"height"`
	Weight             sql.NullString `json:"weight"`
	Status             EntityStatus   `json:"status"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type ProductSubstitute struct {
	ProductID           string    `json:"product_id"`
	SubstituteProductID string    `json:"substitute_product_id"`
	SubstitutionType    string    `json:"substitution_type"`
	Priority            int32     `json:"priority"`
	IsActive            bool      `json:"is_active"`
	CreatedAt           time.Time `json:"created_at"`
}

type Program struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type PurchaseOrder struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	PoNumber             string         `json:"po_number"`
	SupplierID           uuid.NullUUID  `json:"supplier_id"`
	WarehouseID          uuid.NullUUID  `json:"warehouse_id"`
	ProgramID            uuid.NullUUID  `json:"program_id"`
	DepartmentID         uuid.NullUUID  `json:"department_id"`
	OrderDate            time.Time      `json:"order_date"`
	ExpectedDeliveryDate sql.NullTime   `json:"expected_delivery_date"`
	DeliveryAddress      sql.NullString `json:"delivery_address"`
	Currency             string         `json:"currency"`
	Subtotal             string         `json:"subtotal"`
	TaxAmount            string         `json:"tax_amount"`
	TotalAmount          string         `json:"total_amount"`
	Status               EntityStatus   `json:"status"`
	ApprovalStatus       string         `json:"approval_status"`
	ApprovedBy           sql.NullString `json:"approved_by"`
	ApprovedAt           sql.NullTime   `json:"approved_at"`
	Notes                sql.NullString `json:"notes"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type QaChecklistItem struct {
	ID             string `json:"id"`
	TemplateID     string `json:"template_id"`
	ItemOrder      int32  `json:"item_order"`
	Question       string `json:"question"`
	ExpectedAnswer string `json:"expected_answer"`
	IsCritical     bool   `json:"is_critical"`
	Weight         string `json:"weight"`
}

type QaChecklistResult struct {
	ID              string         `json:"id"`
	InspectionID    string         `json:"inspection_id"`
	ChecklistItemID string         `json:"checklist_item_id"`
	Answer          sql.NullString `json:"answer"`
	Score           sql.NullString `json:"score"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
}

type QaChecklistTemplate struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	IsMandatory bool           `json:"is_mandatory"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type QaDisposition struct {
	ID                    string         `json:"id"`
	InspectionID          string         `json:"inspection_id"`
	DispositionType       string         `json:"disposition_type"`
	DispositionDate       time.Time      `json:"disposition_date"`
	ApprovedBy            sql.NullString `json:"approved_by"`
	DestinationLocationID uuid.NullUUID  `json:"destination_location_id"`
	Notes                 sql.NullString `json:"notes"`
	CreatedBy             sql.NullString `json:"created_by"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type QaInspection struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	GrnID          uuid.NullUUID  `json:"grn_id"`
	ProductID      string         `json:"product_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	InspectionDate time.Time      `json:"inspection_date"`
	Inspector      sql.NullString `json:"inspector"`
	Result         string         `json:"result"`
	Notes          sql.NullString `json:"notes"`
	Disposition    sql.NullString `json:"disposition"`
	CreatedBy      sql.NullString `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Recall struct {
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
	RecallNumber    string         `json:"recall_number"`
	RecallType      string         `json:"recall_type"`
	RecallDate      time.Time      `json:"recall_date"`
	ProductID       uuid.NullUUID  `json:"product_id"`
	SubjectProduct  string         `json:"subject_product"`
	BatchNumbers    sql.NullString `json:"batch_numbers"`
	Reason          string         `json:"reason"`
	InitiatedBy     sql.NullString `json:"initiated_by"`
	AuthorizedBy    sql.NullString `json:"authorized_by"`
	Communications  sql.NullString `json:"communications"`
	DispositionPlan sql.NullString `json:"disposition_plan"`
	Status          string         `json:"status"`
	ClosureEvidence sql.NullString `json:"closure_evidence"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type RecallLineItem struct {
	ID                  string         `json:"id"`
	RecallID            string         `json:"recall_id"`
	Recipient           string         `json:"recipient"`
	Location            sql.NullString `json:"location"`
	ProductID           uuid.NullUUID  `json:"product_id"`
	BatchNumber         sql.NullString `json:"batch_number"`
	QuantityIssued      string         `json:"quantity_issued"`
	QuantityRecovered   string         `json:"quantity_recovered"`
	QuantityOutstanding string         `json:"quantity_outstanding"`
	StorageDisposition  sql.NullString `json:"storage_disposition"`
	RecoveredAt         sql.NullTime   `json:"recovered_at"`
	Notes               sql.NullString `json:"notes"`
}

type RecallType struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

type RegulatoryApproval struct {
	ID               string         `json:"id"`
	OrgID            string         `json:"org_id"`
	ScopeType        string         `json:"scope_type"`
	ScopeID          string         `json:"scope_id"`
	Authority        string         `json:"authority"`
	LicenseType      string         `json:"license_type"`
	ReferenceNumber  string         `json:"reference_number"`
	ProductScope     sql.NullString `json:"product_scope"`
	Conditions       sql.NullString `json:"conditions"`
	IssueDate        sql.NullTime   `json:"issue_date"`
	ExpiryDate       sql.NullTime   `json:"expiry_date"`
	RenewalLeadDays  int32          `json:"renewal_lead_days"`
	ResponsibleOwner sql.NullString `json:"responsible_owner"`
	Status           string         `json:"status"`
	EvidenceUrl      sql.NullString `json:"evidence_url"`
	Notes            sql.NullString `json:"notes"`
	CreatedBy        sql.NullString `json:"created_by"`
	UpdatedBy        sql.NullString `json:"updated_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type ReorderRecommendation struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	ProductID          string         `json:"product_id"`
	WarehouseID        string         `json:"warehouse_id"`
	RecommendationDate time.Time      `json:"recommendation_date"`
	CurrentStock       string         `json:"current_stock"`
	ReorderPoint       string         `json:"reorder_point"`
	ReorderQuantity    string         `json:"reorder_quantity"`
	LeadTimeDays       sql.NullInt32  `json:"lead_time_days"`
	AmcUsed            sql.NullString `json:"amc_used"`
	SafetyStock        sql.NullString `json:"safety_stock"`
	RecommendationType sql.NullString `json:"recommendation_type"`
	Priority           sql.NullString `json:"priority"`
	Notes              sql.NullString `json:"notes"`
	Reviewed           bool           `json:"reviewed"`
	CreatedAt          time.Time      `json:"created_at"`
}

type ReportDefinition struct {
	ID            string                `json:"id"`
	OrgID         string                `json:"org_id"`
	Code          string                `json:"code"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Category      string                `json:"category"`
	SqlQuery      sql.NullString        `json:"sql_query"`
	Parameters    pqtype.NullRawMessage `json:"parameters"`
	OutputFormats string                `json:"output_formats"`
	IsSystem      bool                  `json:"is_system"`
	Status        EntityStatus          `json:"status"`
	CreatedBy     sql.NullString        `json:"created_by"`
	UpdatedBy     sql.NullString        `json:"updated_by"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

type ReportSchedule struct {
	ID           string                `json:"id"`
	ReportID     string                `json:"report_id"`
	ScheduleCron string                `json:"schedule_cron"`
	Parameters   pqtype.NullRawMessage `json:"parameters"`
	Recipients   sql.NullString        `json:"recipients"`
	Format       string                `json:"format"`
	IsActive     bool                  `json:"is_active"`
	LastRunAt    sql.NullTime          `json:"last_run_at"`
	NextRunAt    sql.NullTime          `json:"next_run_at"`
	CreatedBy    sql.NullString        `json:"created_by"`
	UpdatedBy    sql.NullString        `json:"updated_by"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type ReturnLineItem struct {
	ID          string         `json:"id"`
	ReturnID    string         `json:"return_id"`
	ProductID   string         `json:"product_id"`
	BatchID     uuid.NullUUID  `json:"batch_id"`
	Quantity    string         `json:"quantity"`
	Condition   sql.NullString `json:"condition"`
	Disposition sql.NullString `json:"disposition"`
	UnitCost    sql.NullString `json:"unit_cost"`
}

type Role struct {
	ID          string         `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Level       int32          `json:"level"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type ShortExpiryReview struct {
	ID                       string         `json:"id"`
	OrgID                    string         `json:"org_id"`
	ReviewDate               time.Time      `json:"review_date"`
	ProductID                string         `json:"product_id"`
	BatchID                  uuid.NullUUID  `json:"batch_id"`
	WarehouseID              string         `json:"warehouse_id"`
	ExpiryDate               time.Time      `json:"expiry_date"`
	RemainingShelfLifeMonths int32          `json:"remaining_shelf_life_months"`
	ExpectedConsumption      sql.NullString `json:"expected_consumption"`
	TransferOption           sql.NullString `json:"transfer_option"`
	DonorCondition           sql.NullString `json:"donor_condition"`
	RegulatoryRestriction    sql.NullString `json:"regulatory_restriction"`
	Decision                 string         `json:"decision"`
	DecisionBy               sql.NullString `json:"decision_by"`
	DecisionDate             sql.NullTime   `json:"decision_date"`
	Notes                    sql.NullString `json:"notes"`
	CreatedBy                sql.NullString `json:"created_by"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type StockAdjustment struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	WarehouseID string         `json:"warehouse_id"`
	ReasonCode  string         `json:"reason_code"`
	Description sql.NullString `json:"description"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type StockCount struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	WarehouseID string         `json:"warehouse_id"`
	CountNumber string         `json:"count_number"`
	CountDate   time.Time      `json:"count_date"`
	CountType   sql.NullString `json:"count_type"`
	Status      EntityStatus   `json:"status"`
	CountedBy   sql.NullString `json:"counted_by"`
	VerifiedBy  sql.NullString `json:"verified_by"`
	Notes       sql.NullString `json:"notes"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type StockIssue struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	WarehouseID  string         `json:"warehouse_id"`
	IssueNumber  string         `json:"issue_number"`
	RequestedBy  sql.NullString `json:"requested_by"`
	ApprovedBy   sql.NullString `json:"approved_by"`
	ProgramID    uuid.NullUUID  `json:"program_id"`
	DepartmentID uuid.NullUUID  `json:"department_id"`
	Status       EntityStatus   `json:"status"`
	Notes        sql.NullString `json:"notes"`
	CreatedBy    sql.NullString `json:"created_by"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type StockLevel struct {
	ID          string        `json:"id"`
	OrgID       string        `json:"org_id"`
	ProductID   string        `json:"product_id"`
	WarehouseID string        `json:"warehouse_id"`
	LocationID  uuid.NullUUID `json:"location_id"`
	BatchID     uuid.NullUUID `json:"batch_id"`
	Quantity    string        `json:"quantity"`
	ReservedQty string        `json:"reserved_qty"`
	Status      StockStatus   `json:"status"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type StockMovement struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	ProductID    string         `json:"product_id"`
	WarehouseID  string         `json:"warehouse_id"`
	LocationID   uuid.NullUUID  `json:"location_id"`
	BatchID      uuid.NullUUID  `json:"batch_id"`
	MovementType MovementType   `json:"movement_type"`
	Quantity     string         `json:"quantity"`
	RefDocType   NullDocType    `json:"ref_doc_type"`
	RefDocID     sql.NullString `json:"ref_doc_id"`
	ReasonCode   sql.NullString `json:"reason_code"`
	Reference    sql.NullString `json:"reference"`
	CreatedBy    string         `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
}

type StockReleaseRecord struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	ReleaseNumber       string         `json:"release_number"`
	WarehouseID         string         `json:"warehouse_id"`
	ProductID           string         `json:"product_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	LocationID          uuid.NullUUID  `json:"location_id"`
	Quantity            string         `json:"quantity"`
	QuarantineReference sql.NullString `json:"quarantine_reference"`
	EvidenceReviewed    sql.NullString `json:"evidence_reviewed"`
	Decision            string         `json:"decision"`
	DecisionDate        time.Time      `json:"decision_date"`
	DecidedBy           string         `json:"decided_by"`
	Notes               sql.NullString `json:"notes"`
	CreatedBy           sql.NullString `json:"created_by"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type StockReturn struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	WarehouseID  uuid.NullUUID  `json:"warehouse_id"`
	ReturnNumber string         `json:"return_number"`
	ReturnedFrom sql.NullString `json:"returned_from"`
	ReturnDate   time.Time      `json:"return_date"`
	ReturnType   sql.NullString `json:"return_type"`
	Reason       sql.NullString `json:"reason"`
	Status       EntityStatus   `json:"status"`
	Notes        sql.NullString `json:"notes"`
	CreatedBy    sql.NullString `json:"created_by"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type StockSnapshot struct {
	ID               string        `json:"id"`
	OrgID            string        `json:"org_id"`
	ProductID        string        `json:"product_id"`
	WarehouseID      string        `json:"warehouse_id"`
	LocationID       uuid.NullUUID `json:"location_id"`
	BatchID          uuid.NullUUID `json:"batch_id"`
	QuantityOnHand   string        `json:"quantity_on_hand"`
	QuantityReserved string        `json:"quantity_reserved"`
	SnapshotDate     time.Time     `json:"snapshot_date"`
	SnapshotType     string        `json:"snapshot_type"`
	CreatedAt        time.Time     `json:"created_at"`
}

type StockTransfer struct {
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
	FromWarehouseID string         `json:"from_warehouse_id"`
	ToWarehouseID   string         `json:"to_warehouse_id"`
	TransferNumber  string         `json:"transfer_number"`
	Status          EntityStatus   `json:"status"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Supplier struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Type          sql.NullString `json:"type"`
	ContactPerson sql.NullString `json:"contact_person"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	City          sql.NullString `json:"city"`
	Country       sql.NullString `json:"country"`
	TaxID         sql.NullString `json:"tax_id"`
	PaymentTerms  sql.NullString `json:"payment_terms"`
	IsActive      bool           `json:"is_active"`
	Status        EntityStatus   `json:"status"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type SupplierContract struct {
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
	SupplierID      string         `json:"supplier_id"`
	ContractNumber  string         `json:"contract_number"`
	ContractDate    time.Time      `json:"contract_date"`
	ExpiryDate      sql.NullTime   `json:"expiry_date"`
	Terms           sql.NullString `json:"terms"`
	DiscountPercent string         `json:"discount_percent"`
	Currency        string         `json:"currency"`
	IsExclusive     bool           `json:"is_exclusive"`
	Status          EntityStatus   `json:"status"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type SyncConflict struct {
	ID            string                `json:"id"`
	OrgID         string                `json:"org_id"`
	TableName     string                `json:"table_name"`
	RecordID      string                `json:"record_id"`
	DeviceID      string                `json:"device_id"`
	ServerVersion pqtype.NullRawMessage `json:"server_version"`
	ClientVersion pqtype.NullRawMessage `json:"client_version"`
	ConflictType  sql.NullString        `json:"conflict_type"`
	Resolution    string                `json:"resolution"`
	ResolvedBy    sql.NullString        `json:"resolved_by"`
	ResolvedAt    sql.NullTime          `json:"resolved_at"`
	CreatedAt     time.Time             `json:"created_at"`
}

type SyncLog struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	DeviceID      string         `json:"device_id"`
	UserID        uuid.NullUUID  `json:"user_id"`
	SyncType      sql.NullString `json:"sync_type"`
	StartedAt     time.Time      `json:"started_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	Status        sql.NullString `json:"status"`
	RecordsPushed int32          `json:"records_pushed"`
	RecordsPulled int32          `json:"records_pulled"`
	ErrorsCount   int32          `json:"errors_count"`
	ErrorMessage  sql.NullString `json:"error_message"`
}

type TemperatureExcursion struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	WarehouseID         string         `json:"warehouse_id"`
	LocationID          uuid.NullUUID  `json:"location_id"`
	EquipmentID         uuid.NullUUID  `json:"equipment_id"`
	DeviceName          sql.NullString `json:"device_name"`
	ExcursionType       string         `json:"excursion_type"`
	StartedAt           time.Time      `json:"started_at"`
	EndedAt             sql.NullTime   `json:"ended_at"`
	MinValue            sql.NullString `json:"min_value"`
	MaxValue            sql.NullString `json:"max_value"`
	ExpectedMin         sql.NullString `json:"expected_min"`
	ExpectedMax         sql.NullString `json:"expected_max"`
	AffectedProducts    sql.NullString `json:"affected_products"`
	AffectedBatches     sql.NullString `json:"affected_batches"`
	QuantityAffected    sql.NullString `json:"quantity_affected"`
	Quarantined         bool           `json:"quarantined"`
	QuarantineReference sql.NullString `json:"quarantine_reference"`
	Disposition         string         `json:"disposition"`
	NotifiedQuality     bool           `json:"notified_quality"`
	NotifiedManager     bool           `json:"notified_manager"`
	TechnicalAdvice     sql.NullString `json:"technical_advice"`
	RootCause           sql.NullString `json:"root_cause"`
	CapaID              uuid.NullUUID  `json:"capa_id"`
	Status              string         `json:"status"`
	CreatedBy           sql.NullString `json:"created_by"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type TemperatureMonitoringEntry struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	WarehouseID  string         `json:"warehouse_id"`
	LocationID   uuid.NullUUID  `json:"location_id"`
	EquipmentID  uuid.NullUUID  `json:"equipment_id"`
	DeviceName   sql.NullString `json:"device_name"`
	MonitorType  string         `json:"monitor_type"`
	ReadingValue string         `json:"reading_value"`
	MinThreshold sql.NullString `json:"min_threshold"`
	MaxThreshold sql.NullString `json:"max_threshold"`
	RecordedAt   time.Time      `json:"recorded_at"`
	RecordedBy   sql.NullString `json:"recorded_by"`
	CreatedAt    time.Time      `json:"created_at"`
}

type TrainingRecord struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	UserID               uuid.NullUUID  `json:"user_id"`
	TrainingTitle        string         `json:"training_title"`
	TrainingType         string         `json:"training_type"`
	Topic                sql.NullString `json:"topic"`
	TrainingDate         time.Time      `json:"training_date"`
	Method               sql.NullString `json:"method"`
	Trainer              sql.NullString `json:"trainer"`
	Assessed             bool           `json:"assessed"`
	AssessmentResult     sql.NullString `json:"assessment_result"`
	CompetencyValidUntil sql.NullTime   `json:"competency_valid_until"`
	CertificateUrl       sql.NullString `json:"certificate_url"`
	CreatedBy            sql.NullString `json:"created_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type TransferLineItem struct {
	ID         string         `json:"id"`
	TransferID string         `json:"transfer_id"`
	ProductID  string         `json:"product_id"`
	BatchID    uuid.NullUUID  `json:"batch_id"`
	Quantity   string         `json:"quantity"`
	UnitCost   sql.NullString `json:"unit_cost"`
	Status     EntityStatus   `json:"status"`
}

type UnitsOfMeasure struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	Abbreviation string       `json:"abbreviation"`
	Category     UomCategory  `json:"category"`
	Status       EntityStatus `json:"status"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type User struct {
	ID         string         `json:"id"`
	OrgID      string         `json:"org_id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	RoleID     uuid.NullUUID  `json:"role_id"`
	OrgLevelID uuid.NullUUID  `json:"org_level_id"`
	IsActive   bool           `json:"is_active"`
	CreatedBy  sql.NullString `json:"created_by"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type UserPreference struct {
	UserID            string                `json:"user_id"`
	Language          string                `json:"language"`
	Theme             string                `json:"theme"`
	Timezone          string                `json:"timezone"`
	DateFormat        string                `json:"date_format"`
	NotificationEmail bool                  `json:"notification_email"`
	NotificationPush  bool                  `json:"notification_push"`
	DashboardConfig   pqtype.NullRawMessage `json:"dashboard_config"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type UserRoleAssignment struct {
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	OrgLevelID string         `json:"org_level_id"`
	GrantedBy  sql.NullString `json:"granted_by"`
	GrantedAt  time.Time      `json:"granted_at"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
}

type UserSession struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Token          string         `json:"token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	IpAddress      sql.NullString `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
	ExpiresAt      time.Time      `json:"expires_at"`
	LastActivityAt sql.NullTime   `json:"last_activity_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Warehouse struct {
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Type      WarehouseType  `json:"type"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
	IsActive  bool           `json:"is_active"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type WarehouseDocument struct {
	ID           string         `json:"id"`
	WarehouseID  string         `json:"warehouse_id"`
	DocumentType string         `json:"document_type"`
	DocumentName string         `json:"document_name"`
	FileUrl      string         `json:"file_url"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	UploadedBy   sql.NullString `json:"uploaded_by"`
	CreatedAt    time.Time      `json:"created_at"`
}
