// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organizations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (org_id, name, code, parent_id, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, code, parent_id, status, created_by, updated_by, created_at, updated_at
`

type CreateDepartmentParams struct {
	OrgID     string         `json:"org_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.queryRow(ctx, q.createDepartmentStmt, createDepartment,
		arg.OrgID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrgLevel = `-- name: CreateOrgLevel :one
INSERT INTO org_levels (org_id, parent_id, name, code, level, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, parent_id, name, code, level, status, created_by, updated_by, created_at, updated_at
`

type CreateOrgLevelParams struct {
	OrgID     string         `json:"org_id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Level     int32          `json:"level"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateOrgLevel(ctx context.Context, arg CreateOrgLevelParams) (OrgLevel, error) {
	row := q.queryRow(ctx, q.createOrgLevelStmt, createOrgLevel,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.Level,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i OrgLevel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Level,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, code, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, code, status, created_by, updated_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Status    EntityStatus   `json:"status"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.queryRow(ctx, q.createOrganizationStmt, createOrganization,
		arg.Name,
		arg.Code,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (org_id, code, name, description, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, code, name, description, status, created_by, updated_by, created_at, updated_at
`

type CreateProgramParams struct {
	OrgID       string         `json:"org_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.queryRow(ctx, q.createProgramStmt, createProgram,
		arg.OrgID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgTree = `-- name: GetOrgTree :many
SELECT c.id, c.org_id, c.parent_id, c.name, c.code, c.level, c.status, c.created_by, c.updated_by, c.created_at, c.updated_at, p.name as parent_name
FROM org_levels c
LEFT JOIN org_levels p ON c.parent_id = p.id
WHERE c.org_id = $1
ORDER BY c.level, c.name
`

type GetOrgTreeRow struct {
	ID         string         `json:"id"`
	OrgID      string         `json:"org_id"`
	ParentID   uuid.NullUUID  `json:"parent_id"`
	Name       string         `json:"name"`
	Code       string         `json:"code"`
	Level      int32          `json:"level"`
	Status     EntityStatus   `json:"status"`
	CreatedBy  sql.NullString `json:"created_by"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ParentName sql.NullString `json:"parent_name"`
}

func (q *Queries) GetOrgTree(ctx context.Context, orgID string) ([]GetOrgTreeRow, error) {
	rows, err := q.query(ctx, q.getOrgTreeStmt, getOrgTree, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgTreeRow{}
	for rows.Next() {
		var i GetOrgTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Level,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, code, status, created_by, updated_by, created_at, updated_at FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.queryRow(ctx, q.getOrganizationStmt, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, org_id, name, code, parent_id, status, created_by, updated_by, created_at, updated_at FROM departments
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context, orgID string) ([]Department, error) {
	rows, err := q.query(ctx, q.listDepartmentsStmt, listDepartments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgLevels = `-- name: ListOrgLevels :many
SELECT id, org_id, parent_id, name, code, level, status, created_by, updated_by, created_at, updated_at FROM org_levels
WHERE org_id = $1
ORDER BY level, name
`

func (q *Queries) ListOrgLevels(ctx context.Context, orgID string) ([]OrgLevel, error) {
	rows, err := q.query(ctx, q.listOrgLevelsStmt, listOrgLevels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgLevel{}
	for rows.Next() {
		var i OrgLevel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Level,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, code, status, created_by, updated_by, created_at, updated_at FROM organizations
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.query(ctx, q.listOrganizationsStmt, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, org_id, code, name, description, status, created_by, updated_by, created_at, updated_at FROM programs
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListPrograms(ctx context.Context, orgID string) ([]Program, error) {
	rows, err := q.query(ctx, q.listProgramsStmt, listPrograms, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations SET
    name = $1, status = $2::entity_status, updated_by = $3
WHERE id = $4
`

type UpdateOrganizationParams struct {
	Name      string         `json:"name"`
	Column2   EntityStatus   `json:"column_2"`
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.exec(ctx, q.updateOrganizationStmt, updateOrganization,
		arg.Name,
		arg.Column2,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
