// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_dispatch.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDeliveryConfirmation = `-- name: CreateDeliveryConfirmation :one
INSERT INTO delivery_confirmations (
    org_id, waybill_id, confirming_warehouse_id, recipient_name, confirmed_date,
    delivery_status, items_conformed, quantity_conformed, batch_conformed,
    expiry_conformed, condition_conformed, temperature_conformed,
    unfilled_quantity, substitutions, discrepancies, follow_up_commitments, confirmed_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, org_id, waybill_id, confirming_warehouse_id, recipient_name, confirmed_date, delivery_status, items_conformed, quantity_conformed, batch_conformed, expiry_conformed, condition_conformed, temperature_conformed, unfilled_quantity, substitutions, discrepancies, follow_up_commitments, confirmed_by, created_at, updated_at
`

type CreateDeliveryConfirmationParams struct {
	OrgID                 string         `json:"org_id"`
	WaybillID             string         `json:"waybill_id"`
	ConfirmingWarehouseID uuid.NullUUID  `json:"confirming_warehouse_id"`
	RecipientName         sql.NullString `json:"recipient_name"`
	ConfirmedDate         time.Time      `json:"confirmed_date"`
	DeliveryStatus        string         `json:"delivery_status"`
	ItemsConformed        sql.NullBool   `json:"items_conformed"`
	QuantityConformed     sql.NullBool   `json:"quantity_conformed"`
	BatchConformed        sql.NullBool   `json:"batch_conformed"`
	ExpiryConformed       sql.NullBool   `json:"expiry_conformed"`
	ConditionConformed    sql.NullBool   `json:"condition_conformed"`
	TemperatureConformed  sql.NullBool   `json:"temperature_conformed"`
	UnfilledQuantity      sql.NullString `json:"unfilled_quantity"`
	Substitutions         sql.NullString `json:"substitutions"`
	Discrepancies         sql.NullString `json:"discrepancies"`
	FollowUpCommitments   sql.NullString `json:"follow_up_commitments"`
	ConfirmedBy           sql.NullString `json:"confirmed_by"`
}

func (q *Queries) CreateDeliveryConfirmation(ctx context.Context, arg CreateDeliveryConfirmationParams) (DeliveryConfirmation, error) {
	row := q.queryRow(ctx, q.createDeliveryConfirmationStmt, createDeliveryConfirmation,
		arg.OrgID,
		arg.WaybillID,
		arg.ConfirmingWarehouseID,
		arg.RecipientName,
		arg.ConfirmedDate,
		arg.DeliveryStatus,
		arg.ItemsConformed,
		arg.QuantityConformed,
		arg.BatchConformed,
		arg.ExpiryConformed,
		arg.ConditionConformed,
		arg.TemperatureConformed,
		arg.UnfilledQuantity,
		arg.Substitutions,
		arg.Discrepancies,
		arg.FollowUpCommitments,
		arg.ConfirmedBy,
	)
	var i DeliveryConfirmation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WaybillID,
		&i.ConfirmingWarehouseID,
		&i.RecipientName,
		&i.ConfirmedDate,
		&i.DeliveryStatus,
		&i.ItemsConformed,
		&i.QuantityConformed,
		&i.BatchConformed,
		&i.ExpiryConformed,
		&i.ConditionConformed,
		&i.TemperatureConformed,
		&i.UnfilledQuantity,
		&i.Substitutions,
		&i.Discrepancies,
		&i.FollowUpCommitments,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDispatchWaybill = `-- name: CreateDispatchWaybill :one

INSERT INTO dispatch_waybills (
    org_id, waybill_number, issue_id, transfer_id, sender_warehouse_id,
    recipient_warehouse_id, recipient, dispatch_date, carrier, vehicle_number,
    carton_count, packing_list_reference, storage_requirement,
    temperature_sensitive, condition, document_refs, status, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, org_id, waybill_number, issue_id, transfer_id, sender_warehouse_id, recipient_warehouse_id, recipient, dispatch_date, carrier, vehicle_number, carton_count, packing_list_reference, storage_requirement, temperature_sensitive, condition, document_refs, status, created_by, updated_by, created_at, updated_at
`

type CreateDispatchWaybillParams struct {
	OrgID                string         `json:"org_id"`
	WaybillNumber        string         `json:"waybill_number"`
	IssueID              uuid.NullUUID  `json:"issue_id"`
	TransferID           uuid.NullUUID  `json:"transfer_id"`
	SenderWarehouseID    string         `json:"sender_warehouse_id"`
	RecipientWarehouseID uuid.NullUUID  `json:"recipient_warehouse_id"`
	Recipient            sql.NullString `json:"recipient"`
	DispatchDate         time.Time      `json:"dispatch_date"`
	Carrier              sql.NullString `json:"carrier"`
	VehicleNumber        sql.NullString `json:"vehicle_number"`
	CartonCount          sql.NullInt32  `json:"carton_count"`
	PackingListReference sql.NullString `json:"packing_list_reference"`
	StorageRequirement   sql.NullString `json:"storage_requirement"`
	TemperatureSensitive bool           `json:"temperature_sensitive"`
	Condition            sql.NullString `json:"condition"`
	DocumentRefs         sql.NullString `json:"document_refs"`
	Status               string         `json:"status"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

// Policy §16 — Dispatch waybills and delivery confirmation
func (q *Queries) CreateDispatchWaybill(ctx context.Context, arg CreateDispatchWaybillParams) (DispatchWaybill, error) {
	row := q.queryRow(ctx, q.createDispatchWaybillStmt, createDispatchWaybill,
		arg.OrgID,
		arg.WaybillNumber,
		arg.IssueID,
		arg.TransferID,
		arg.SenderWarehouseID,
		arg.RecipientWarehouseID,
		arg.Recipient,
		arg.DispatchDate,
		arg.Carrier,
		arg.VehicleNumber,
		arg.CartonCount,
		arg.PackingListReference,
		arg.StorageRequirement,
		arg.TemperatureSensitive,
		arg.Condition,
		arg.DocumentRefs,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i DispatchWaybill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WaybillNumber,
		&i.IssueID,
		&i.TransferID,
		&i.SenderWarehouseID,
		&i.RecipientWarehouseID,
		&i.Recipient,
		&i.DispatchDate,
		&i.Carrier,
		&i.VehicleNumber,
		&i.CartonCount,
		&i.PackingListReference,
		&i.StorageRequirement,
		&i.TemperatureSensitive,
		&i.Condition,
		&i.DocumentRefs,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryConfirmation = `-- name: GetDeliveryConfirmation :one
SELECT id, org_id, waybill_id, confirming_warehouse_id, recipient_name, confirmed_date, delivery_status, items_conformed, quantity_conformed, batch_conformed, expiry_conformed, condition_conformed, temperature_conformed, unfilled_quantity, substitutions, discrepancies, follow_up_commitments, confirmed_by, created_at, updated_at FROM delivery_confirmations
WHERE id = $1 AND org_id = $2
`

type GetDeliveryConfirmationParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetDeliveryConfirmation(ctx context.Context, arg GetDeliveryConfirmationParams) (DeliveryConfirmation, error) {
	row := q.queryRow(ctx, q.getDeliveryConfirmationStmt, getDeliveryConfirmation, arg.ID, arg.OrgID)
	var i DeliveryConfirmation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WaybillID,
		&i.ConfirmingWarehouseID,
		&i.RecipientName,
		&i.ConfirmedDate,
		&i.DeliveryStatus,
		&i.ItemsConformed,
		&i.QuantityConformed,
		&i.BatchConformed,
		&i.ExpiryConformed,
		&i.ConditionConformed,
		&i.TemperatureConformed,
		&i.UnfilledQuantity,
		&i.Substitutions,
		&i.Discrepancies,
		&i.FollowUpCommitments,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispatchWaybill = `-- name: GetDispatchWaybill :one
SELECT id, org_id, waybill_number, issue_id, transfer_id, sender_warehouse_id, recipient_warehouse_id, recipient, dispatch_date, carrier, vehicle_number, carton_count, packing_list_reference, storage_requirement, temperature_sensitive, condition, document_refs, status, created_by, updated_by, created_at, updated_at FROM dispatch_waybills
WHERE id = $1 AND org_id = $2
`

type GetDispatchWaybillParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetDispatchWaybill(ctx context.Context, arg GetDispatchWaybillParams) (DispatchWaybill, error) {
	row := q.queryRow(ctx, q.getDispatchWaybillStmt, getDispatchWaybill, arg.ID, arg.OrgID)
	var i DispatchWaybill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WaybillNumber,
		&i.IssueID,
		&i.TransferID,
		&i.SenderWarehouseID,
		&i.RecipientWarehouseID,
		&i.Recipient,
		&i.DispatchDate,
		&i.Carrier,
		&i.VehicleNumber,
		&i.CartonCount,
		&i.PackingListReference,
		&i.StorageRequirement,
		&i.TemperatureSensitive,
		&i.Condition,
		&i.DocumentRefs,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveryConfirmations = `-- name: ListDeliveryConfirmations :many
SELECT id, org_id, waybill_id, confirming_warehouse_id, recipient_name, confirmed_date, delivery_status, items_conformed, quantity_conformed, batch_conformed, expiry_conformed, condition_conformed, temperature_conformed, unfilled_quantity, substitutions, discrepancies, follow_up_commitments, confirmed_by, created_at, updated_at FROM delivery_confirmations
WHERE org_id = $1
ORDER BY confirmed_date DESC
LIMIT $2 OFFSET $3
`

type ListDeliveryConfirmationsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDeliveryConfirmations(ctx context.Context, arg ListDeliveryConfirmationsParams) ([]DeliveryConfirmation, error) {
	rows, err := q.query(ctx, q.listDeliveryConfirmationsStmt, listDeliveryConfirmations, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryConfirmation{}
	for rows.Next() {
		var i DeliveryConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WaybillID,
			&i.ConfirmingWarehouseID,
			&i.RecipientName,
			&i.ConfirmedDate,
			&i.DeliveryStatus,
			&i.ItemsConformed,
			&i.QuantityConformed,
			&i.BatchConformed,
			&i.ExpiryConformed,
			&i.ConditionConformed,
			&i.TemperatureConformed,
			&i.UnfilledQuantity,
			&i.Substitutions,
			&i.Discrepancies,
			&i.FollowUpCommitments,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryConfirmationsByWaybill = `-- name: ListDeliveryConfirmationsByWaybill :many
SELECT id, org_id, waybill_id, confirming_warehouse_id, recipient_name, confirmed_date, delivery_status, items_conformed, quantity_conformed, batch_conformed, expiry_conformed, condition_conformed, temperature_conformed, unfilled_quantity, substitutions, discrepancies, follow_up_commitments, confirmed_by, created_at, updated_at FROM delivery_confirmations
WHERE org_id = $1 AND waybill_id = $2
ORDER BY confirmed_date DESC
LIMIT $3 OFFSET $4
`

type ListDeliveryConfirmationsByWaybillParams struct {
	OrgID     string `json:"org_id"`
	WaybillID string `json:"waybill_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListDeliveryConfirmationsByWaybill(ctx context.Context, arg ListDeliveryConfirmationsByWaybillParams) ([]DeliveryConfirmation, error) {
	rows, err := q.query(ctx, q.listDeliveryConfirmationsByWaybillStmt, listDeliveryConfirmationsByWaybill,
		arg.OrgID,
		arg.WaybillID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryConfirmation{}
	for rows.Next() {
		var i DeliveryConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WaybillID,
			&i.ConfirmingWarehouseID,
			&i.RecipientName,
			&i.ConfirmedDate,
			&i.DeliveryStatus,
			&i.ItemsConformed,
			&i.QuantityConformed,
			&i.BatchConformed,
			&i.ExpiryConformed,
			&i.ConditionConformed,
			&i.TemperatureConformed,
			&i.UnfilledQuantity,
			&i.Substitutions,
			&i.Discrepancies,
			&i.FollowUpCommitments,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchWaybills = `-- name: ListDispatchWaybills :many
SELECT id, org_id, waybill_number, issue_id, transfer_id, sender_warehouse_id, recipient_warehouse_id, recipient, dispatch_date, carrier, vehicle_number, carton_count, packing_list_reference, storage_requirement, temperature_sensitive, condition, document_refs, status, created_by, updated_by, created_at, updated_at FROM dispatch_waybills
WHERE org_id = $1
ORDER BY dispatch_date DESC
LIMIT $2 OFFSET $3
`

type ListDispatchWaybillsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDispatchWaybills(ctx context.Context, arg ListDispatchWaybillsParams) ([]DispatchWaybill, error) {
	rows, err := q.query(ctx, q.listDispatchWaybillsStmt, listDispatchWaybills, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchWaybill{}
	for rows.Next() {
		var i DispatchWaybill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WaybillNumber,
			&i.IssueID,
			&i.TransferID,
			&i.SenderWarehouseID,
			&i.RecipientWarehouseID,
			&i.Recipient,
			&i.DispatchDate,
			&i.Carrier,
			&i.VehicleNumber,
			&i.CartonCount,
			&i.PackingListReference,
			&i.StorageRequirement,
			&i.TemperatureSensitive,
			&i.Condition,
			&i.DocumentRefs,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchWaybillsByStatus = `-- name: ListDispatchWaybillsByStatus :many
SELECT id, org_id, waybill_number, issue_id, transfer_id, sender_warehouse_id, recipient_warehouse_id, recipient, dispatch_date, carrier, vehicle_number, carton_count, packing_list_reference, storage_requirement, temperature_sensitive, condition, document_refs, status, created_by, updated_by, created_at, updated_at FROM dispatch_waybills
WHERE org_id = $1 AND status = $2
ORDER BY dispatch_date DESC
LIMIT $3 OFFSET $4
`

type ListDispatchWaybillsByStatusParams struct {
	OrgID  string `json:"org_id"`
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDispatchWaybillsByStatus(ctx context.Context, arg ListDispatchWaybillsByStatusParams) ([]DispatchWaybill, error) {
	rows, err := q.query(ctx, q.listDispatchWaybillsByStatusStmt, listDispatchWaybillsByStatus,
		arg.OrgID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchWaybill{}
	for rows.Next() {
		var i DispatchWaybill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WaybillNumber,
			&i.IssueID,
			&i.TransferID,
			&i.SenderWarehouseID,
			&i.RecipientWarehouseID,
			&i.Recipient,
			&i.DispatchDate,
			&i.Carrier,
			&i.VehicleNumber,
			&i.CartonCount,
			&i.PackingListReference,
			&i.StorageRequirement,
			&i.TemperatureSensitive,
			&i.Condition,
			&i.DocumentRefs,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
