// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_events.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComplaint = `-- name: CreateComplaint :one

INSERT INTO complaints (
    org_id, complaint_number, received_date, received_via, severity, category,
    product_id, batch_id, description, reporter_name, reporter_contact,
    immediate_escalation, escalated, escalated_to, manufacturer_notified,
    competent_authority_notified, status, resolution_notes, capa_id, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, org_id, complaint_number, received_date, received_via, severity, category, product_id, batch_id, description, reporter_name, reporter_contact, immediate_escalation, escalated, escalated_to, manufacturer_notified, competent_authority_notified, status, resolution_notes, capa_id, created_by, updated_by, created_at, updated_at
`

type CreateComplaintParams struct {
	OrgID                      string         `json:"org_id"`
	ComplaintNumber            string         `json:"complaint_number"`
	ReceivedDate               time.Time      `json:"received_date"`
	ReceivedVia                sql.NullString `json:"received_via"`
	Severity                   sql.NullString `json:"severity"`
	Category                   sql.NullString `json:"category"`
	ProductID                  uuid.NullUUID  `json:"product_id"`
	BatchID                    uuid.NullUUID  `json:"batch_id"`
	Description                string         `json:"description"`
	ReporterName               sql.NullString `json:"reporter_name"`
	ReporterContact            sql.NullString `json:"reporter_contact"`
	ImmediateEscalation        bool           `json:"immediate_escalation"`
	Escalated                  bool           `json:"escalated"`
	EscalatedTo                sql.NullString `json:"escalated_to"`
	ManufacturerNotified       bool           `json:"manufacturer_notified"`
	CompetentAuthorityNotified bool           `json:"competent_authority_notified"`
	Status                     string         `json:"status"`
	ResolutionNotes            sql.NullString `json:"resolution_notes"`
	CapaID                     uuid.NullUUID  `json:"capa_id"`
	CreatedBy                  sql.NullString `json:"created_by"`
	UpdatedBy                  sql.NullString `json:"updated_by"`
}

// Policy §17 — Complaints, recalls (incl. mock recall) and falsified-product triage
func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.queryRow(ctx, q.createComplaintStmt, createComplaint,
		arg.OrgID,
		arg.ComplaintNumber,
		arg.ReceivedDate,
		arg.ReceivedVia,
		arg.Severity,
		arg.Category,
		arg.ProductID,
		arg.BatchID,
		arg.Description,
		arg.ReporterName,
		arg.ReporterContact,
		arg.ImmediateEscalation,
		arg.Escalated,
		arg.EscalatedTo,
		arg.ManufacturerNotified,
		arg.CompetentAuthorityNotified,
		arg.Status,
		arg.ResolutionNotes,
		arg.CapaID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComplaintNumber,
		&i.ReceivedDate,
		&i.ReceivedVia,
		&i.Severity,
		&i.Category,
		&i.ProductID,
		&i.BatchID,
		&i.Description,
		&i.ReporterName,
		&i.ReporterContact,
		&i.ImmediateEscalation,
		&i.Escalated,
		&i.EscalatedTo,
		&i.ManufacturerNotified,
		&i.CompetentAuthorityNotified,
		&i.Status,
		&i.ResolutionNotes,
		&i.CapaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecall = `-- name: CreateRecall :one
INSERT INTO recalls (
    org_id, recall_number, recall_type, recall_date, product_id, subject_product,
    batch_numbers, reason, initiated_by, authorized_by, communications,
    disposition_plan, status, closure_evidence, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, org_id, recall_number, recall_type, recall_date, product_id, subject_product, batch_numbers, reason, initiated_by, authorized_by, communications, disposition_plan, status, closure_evidence, created_by, updated_by, created_at, updated_at
`

type CreateRecallParams struct {
	OrgID           string         `json:"org_id"`
	RecallNumber    string         `json:"recall_number"`
	RecallType      string         `json:"recall_type"`
	RecallDate      time.Time      `json:"recall_date"`
	ProductID       uuid.NullUUID  `json:"product_id"`
	SubjectProduct  string         `json:"subject_product"`
	BatchNumbers    sql.NullString `json:"batch_numbers"`
	Reason          string         `json:"reason"`
	InitiatedBy     sql.NullString `json:"initiated_by"`
	AuthorizedBy    sql.NullString `json:"authorized_by"`
	Communications  sql.NullString `json:"communications"`
	DispositionPlan sql.NullString `json:"disposition_plan"`
	Status          string         `json:"status"`
	ClosureEvidence sql.NullString `json:"closure_evidence"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateRecall(ctx context.Context, arg CreateRecallParams) (Recall, error) {
	row := q.queryRow(ctx, q.createRecallStmt, createRecall,
		arg.OrgID,
		arg.RecallNumber,
		arg.RecallType,
		arg.RecallDate,
		arg.ProductID,
		arg.SubjectProduct,
		arg.BatchNumbers,
		arg.Reason,
		arg.InitiatedBy,
		arg.AuthorizedBy,
		arg.Communications,
		arg.DispositionPlan,
		arg.Status,
		arg.ClosureEvidence,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Recall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecallNumber,
		&i.RecallType,
		&i.RecallDate,
		&i.ProductID,
		&i.SubjectProduct,
		&i.BatchNumbers,
		&i.Reason,
		&i.InitiatedBy,
		&i.AuthorizedBy,
		&i.Communications,
		&i.DispositionPlan,
		&i.Status,
		&i.ClosureEvidence,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecallLineItem = `-- name: CreateRecallLineItem :one
INSERT INTO recall_line_items (
    recall_id, recipient, location, product_id, batch_number, quantity_issued,
    quantity_recovered, quantity_outstanding, storage_disposition, recovered_at, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, recall_id, recipient, location, product_id, batch_number, quantity_issued, quantity_recovered, quantity_outstanding, storage_disposition, recovered_at, notes
`

type CreateRecallLineItemParams struct {
	RecallID            string         `json:"recall_id"`
	Recipient           string         `json:"recipient"`
	Location            sql.NullString `json:"location"`
	ProductID           uuid.NullUUID  `json:"product_id"`
	BatchNumber         sql.NullString `json:"batch_number"`
	QuantityIssued      string         `json:"quantity_issued"`
	QuantityRecovered   string         `json:"quantity_recovered"`
	QuantityOutstanding string         `json:"quantity_outstanding"`
	StorageDisposition  sql.NullString `json:"storage_disposition"`
	RecoveredAt         sql.NullTime   `json:"recovered_at"`
	Notes               sql.NullString `json:"notes"`
}

func (q *Queries) CreateRecallLineItem(ctx context.Context, arg CreateRecallLineItemParams) (RecallLineItem, error) {
	row := q.queryRow(ctx, q.createRecallLineItemStmt, createRecallLineItem,
		arg.RecallID,
		arg.Recipient,
		arg.Location,
		arg.ProductID,
		arg.BatchNumber,
		arg.QuantityIssued,
		arg.QuantityRecovered,
		arg.QuantityOutstanding,
		arg.StorageDisposition,
		arg.RecoveredAt,
		arg.Notes,
	)
	var i RecallLineItem
	err := row.Scan(
		&i.ID,
		&i.RecallID,
		&i.Recipient,
		&i.Location,
		&i.ProductID,
		&i.BatchNumber,
		&i.QuantityIssued,
		&i.QuantityRecovered,
		&i.QuantityOutstanding,
		&i.StorageDisposition,
		&i.RecoveredAt,
		&i.Notes,
	)
	return i, err
}

const getComplaint = `-- name: GetComplaint :one
SELECT id, org_id, complaint_number, received_date, received_via, severity, category, product_id, batch_id, description, reporter_name, reporter_contact, immediate_escalation, escalated, escalated_to, manufacturer_notified, competent_authority_notified, status, resolution_notes, capa_id, created_by, updated_by, created_at, updated_at FROM complaints
WHERE id = $1 AND org_id = $2
`

type GetComplaintParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetComplaint(ctx context.Context, arg GetComplaintParams) (Complaint, error) {
	row := q.queryRow(ctx, q.getComplaintStmt, getComplaint, arg.ID, arg.OrgID)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComplaintNumber,
		&i.ReceivedDate,
		&i.ReceivedVia,
		&i.Severity,
		&i.Category,
		&i.ProductID,
		&i.BatchID,
		&i.Description,
		&i.ReporterName,
		&i.ReporterContact,
		&i.ImmediateEscalation,
		&i.Escalated,
		&i.EscalatedTo,
		&i.ManufacturerNotified,
		&i.CompetentAuthorityNotified,
		&i.Status,
		&i.ResolutionNotes,
		&i.CapaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecall = `-- name: GetRecall :one
SELECT id, org_id, recall_number, recall_type, recall_date, product_id, subject_product, batch_numbers, reason, initiated_by, authorized_by, communications, disposition_plan, status, closure_evidence, created_by, updated_by, created_at, updated_at FROM recalls
WHERE id = $1 AND org_id = $2
`

type GetRecallParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetRecall(ctx context.Context, arg GetRecallParams) (Recall, error) {
	row := q.queryRow(ctx, q.getRecallStmt, getRecall, arg.ID, arg.OrgID)
	var i Recall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecallNumber,
		&i.RecallType,
		&i.RecallDate,
		&i.ProductID,
		&i.SubjectProduct,
		&i.BatchNumbers,
		&i.Reason,
		&i.InitiatedBy,
		&i.AuthorizedBy,
		&i.Communications,
		&i.DispositionPlan,
		&i.Status,
		&i.ClosureEvidence,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecallLineItems = `-- name: GetRecallLineItems :many
SELECT id, recall_id, recipient, location, product_id, batch_number, quantity_issued, quantity_recovered, quantity_outstanding, storage_disposition, recovered_at, notes FROM recall_line_items
WHERE recall_id = $1
ORDER BY recovered_at DESC
`

func (q *Queries) GetRecallLineItems(ctx context.Context, recallID string) ([]RecallLineItem, error) {
	rows, err := q.query(ctx, q.getRecallLineItemsStmt, getRecallLineItems, recallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallLineItem{}
	for rows.Next() {
		var i RecallLineItem
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.Recipient,
			&i.Location,
			&i.ProductID,
			&i.BatchNumber,
			&i.QuantityIssued,
			&i.QuantityRecovered,
			&i.QuantityOutstanding,
			&i.StorageDisposition,
			&i.RecoveredAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplaints = `-- name: ListComplaints :many
SELECT id, org_id, complaint_number, received_date, received_via, severity, category, product_id, batch_id, description, reporter_name, reporter_contact, immediate_escalation, escalated, escalated_to, manufacturer_notified, competent_authority_notified, status, resolution_notes, capa_id, created_by, updated_by, created_at, updated_at FROM complaints
WHERE org_id = $1
ORDER BY received_date DESC
LIMIT $2 OFFSET $3
`

type ListComplaintsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListComplaints(ctx context.Context, arg ListComplaintsParams) ([]Complaint, error) {
	rows, err := q.query(ctx, q.listComplaintsStmt, listComplaints, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Complaint{}
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ComplaintNumber,
			&i.ReceivedDate,
			&i.ReceivedVia,
			&i.Severity,
			&i.Category,
			&i.ProductID,
			&i.BatchID,
			&i.Description,
			&i.ReporterName,
			&i.ReporterContact,
			&i.ImmediateEscalation,
			&i.Escalated,
			&i.EscalatedTo,
			&i.ManufacturerNotified,
			&i.CompetentAuthorityNotified,
			&i.Status,
			&i.ResolutionNotes,
			&i.CapaID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalatedComplaints = `-- name: ListEscalatedComplaints :many
SELECT id, org_id, complaint_number, received_date, received_via, severity, category, product_id, batch_id, description, reporter_name, reporter_contact, immediate_escalation, escalated, escalated_to, manufacturer_notified, competent_authority_notified, status, resolution_notes, capa_id, created_by, updated_by, created_at, updated_at FROM complaints
WHERE org_id = $1 AND (immediate_escalation = true OR escalated = true)
ORDER BY received_date DESC
LIMIT $2 OFFSET $3
`

type ListEscalatedComplaintsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListEscalatedComplaints(ctx context.Context, arg ListEscalatedComplaintsParams) ([]Complaint, error) {
	rows, err := q.query(ctx, q.listEscalatedComplaintsStmt, listEscalatedComplaints, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Complaint{}
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ComplaintNumber,
			&i.ReceivedDate,
			&i.ReceivedVia,
			&i.Severity,
			&i.Category,
			&i.ProductID,
			&i.BatchID,
			&i.Description,
			&i.ReporterName,
			&i.ReporterContact,
			&i.ImmediateEscalation,
			&i.Escalated,
			&i.EscalatedTo,
			&i.ManufacturerNotified,
			&i.CompetentAuthorityNotified,
			&i.Status,
			&i.ResolutionNotes,
			&i.CapaID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecalls = `-- name: ListRecalls :many
SELECT id, org_id, recall_number, recall_type, recall_date, product_id, subject_product, batch_numbers, reason, initiated_by, authorized_by, communications, disposition_plan, status, closure_evidence, created_by, updated_by, created_at, updated_at FROM recalls
WHERE org_id = $1
ORDER BY recall_date DESC
LIMIT $2 OFFSET $3
`

type ListRecallsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRecalls(ctx context.Context, arg ListRecallsParams) ([]Recall, error) {
	rows, err := q.query(ctx, q.listRecallsStmt, listRecalls, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recall{}
	for rows.Next() {
		var i Recall
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RecallNumber,
			&i.RecallType,
			&i.RecallDate,
			&i.ProductID,
			&i.SubjectProduct,
			&i.BatchNumbers,
			&i.Reason,
			&i.InitiatedBy,
			&i.AuthorizedBy,
			&i.Communications,
			&i.DispositionPlan,
			&i.Status,
			&i.ClosureEvidence,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecallsByType = `-- name: ListRecallsByType :many
SELECT id, org_id, recall_number, recall_type, recall_date, product_id, subject_product, batch_numbers, reason, initiated_by, authorized_by, communications, disposition_plan, status, closure_evidence, created_by, updated_by, created_at, updated_at FROM recalls
WHERE org_id = $1 AND recall_type = $2
ORDER BY recall_date DESC
LIMIT $3 OFFSET $4
`

type ListRecallsByTypeParams struct {
	OrgID      string `json:"org_id"`
	RecallType string `json:"recall_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListRecallsByType(ctx context.Context, arg ListRecallsByTypeParams) ([]Recall, error) {
	rows, err := q.query(ctx, q.listRecallsByTypeStmt, listRecallsByType,
		arg.OrgID,
		arg.RecallType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recall{}
	for rows.Next() {
		var i Recall
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RecallNumber,
			&i.RecallType,
			&i.RecallDate,
			&i.ProductID,
			&i.SubjectProduct,
			&i.BatchNumbers,
			&i.Reason,
			&i.InitiatedBy,
			&i.AuthorizedBy,
			&i.Communications,
			&i.DispositionPlan,
			&i.Status,
			&i.ClosureEvidence,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
