// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_coldchain.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTemperatureExcursion = `-- name: CreateTemperatureExcursion :one
INSERT INTO temperature_excursions (
    org_id, warehouse_id, location_id, equipment_id, device_name,
    excursion_type, started_at, ended_at, min_value, max_value,
    expected_min, expected_max, affected_products, affected_batches,
    quantity_affected, quarantined, quarantine_reference, disposition,
    notified_quality, notified_manager, technical_advice, root_cause,
    capa_id, status, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
RETURNING id, org_id, warehouse_id, location_id, equipment_id, device_name, excursion_type, started_at, ended_at, min_value, max_value, expected_min, expected_max, affected_products, affected_batches, quantity_affected, quarantined, quarantine_reference, disposition, notified_quality, notified_manager, technical_advice, root_cause, capa_id, status, created_by, updated_by, created_at, updated_at
`

type CreateTemperatureExcursionParams struct {
	OrgID               string         `json:"org_id"`
	WarehouseID         string         `json:"warehouse_id"`
	LocationID          uuid.NullUUID  `json:"location_id"`
	EquipmentID         uuid.NullUUID  `json:"equipment_id"`
	DeviceName          sql.NullString `json:"device_name"`
	ExcursionType       string         `json:"excursion_type"`
	StartedAt           time.Time      `json:"started_at"`
	EndedAt             sql.NullTime   `json:"ended_at"`
	MinValue            sql.NullString `json:"min_value"`
	MaxValue            sql.NullString `json:"max_value"`
	ExpectedMin         sql.NullString `json:"expected_min"`
	ExpectedMax         sql.NullString `json:"expected_max"`
	AffectedProducts    sql.NullString `json:"affected_products"`
	AffectedBatches     sql.NullString `json:"affected_batches"`
	QuantityAffected    sql.NullString `json:"quantity_affected"`
	Quarantined         bool           `json:"quarantined"`
	QuarantineReference sql.NullString `json:"quarantine_reference"`
	Disposition         string         `json:"disposition"`
	NotifiedQuality     bool           `json:"notified_quality"`
	NotifiedManager     bool           `json:"notified_manager"`
	TechnicalAdvice     sql.NullString `json:"technical_advice"`
	RootCause           sql.NullString `json:"root_cause"`
	CapaID              uuid.NullUUID  `json:"capa_id"`
	Status              string         `json:"status"`
	CreatedBy           sql.NullString `json:"created_by"`
	UpdatedBy           sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateTemperatureExcursion(ctx context.Context, arg CreateTemperatureExcursionParams) (TemperatureExcursion, error) {
	row := q.queryRow(ctx, q.createTemperatureExcursionStmt, createTemperatureExcursion,
		arg.OrgID,
		arg.WarehouseID,
		arg.LocationID,
		arg.EquipmentID,
		arg.DeviceName,
		arg.ExcursionType,
		arg.StartedAt,
		arg.EndedAt,
		arg.MinValue,
		arg.MaxValue,
		arg.ExpectedMin,
		arg.ExpectedMax,
		arg.AffectedProducts,
		arg.AffectedBatches,
		arg.QuantityAffected,
		arg.Quarantined,
		arg.QuarantineReference,
		arg.Disposition,
		arg.NotifiedQuality,
		arg.NotifiedManager,
		arg.TechnicalAdvice,
		arg.RootCause,
		arg.CapaID,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TemperatureExcursion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.LocationID,
		&i.EquipmentID,
		&i.DeviceName,
		&i.ExcursionType,
		&i.StartedAt,
		&i.EndedAt,
		&i.MinValue,
		&i.MaxValue,
		&i.ExpectedMin,
		&i.ExpectedMax,
		&i.AffectedProducts,
		&i.AffectedBatches,
		&i.QuantityAffected,
		&i.Quarantined,
		&i.QuarantineReference,
		&i.Disposition,
		&i.NotifiedQuality,
		&i.NotifiedManager,
		&i.TechnicalAdvice,
		&i.RootCause,
		&i.CapaID,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemperatureMonitoringEntry = `-- name: CreateTemperatureMonitoringEntry :one

INSERT INTO temperature_monitoring_entries (
    org_id, warehouse_id, location_id, equipment_id, device_name,
    monitor_type, reading_value, min_threshold, max_threshold,
    recorded_at, recorded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, warehouse_id, location_id, equipment_id, device_name, monitor_type, reading_value, min_threshold, max_threshold, recorded_at, recorded_by, created_at
`

type CreateTemperatureMonitoringEntryParams struct {
	OrgID        string         `json:"org_id"`
	WarehouseID  string         `json:"warehouse_id"`
	LocationID   uuid.NullUUID  `json:"location_id"`
	EquipmentID  uuid.NullUUID  `json:"equipment_id"`
	DeviceName   sql.NullString `json:"device_name"`
	MonitorType  string         `json:"monitor_type"`
	ReadingValue string         `json:"reading_value"`
	MinThreshold sql.NullString `json:"min_threshold"`
	MaxThreshold sql.NullString `json:"max_threshold"`
	RecordedAt   time.Time      `json:"recorded_at"`
	RecordedBy   sql.NullString `json:"recorded_by"`
}

// Policy §13 — Cold Chain & Environmental Control
func (q *Queries) CreateTemperatureMonitoringEntry(ctx context.Context, arg CreateTemperatureMonitoringEntryParams) (TemperatureMonitoringEntry, error) {
	row := q.queryRow(ctx, q.createTemperatureMonitoringEntryStmt, createTemperatureMonitoringEntry,
		arg.OrgID,
		arg.WarehouseID,
		arg.LocationID,
		arg.EquipmentID,
		arg.DeviceName,
		arg.MonitorType,
		arg.ReadingValue,
		arg.MinThreshold,
		arg.MaxThreshold,
		arg.RecordedAt,
		arg.RecordedBy,
	)
	var i TemperatureMonitoringEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.LocationID,
		&i.EquipmentID,
		&i.DeviceName,
		&i.MonitorType,
		&i.ReadingValue,
		&i.MinThreshold,
		&i.MaxThreshold,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTemperatureExcursion = `-- name: GetTemperatureExcursion :one
SELECT id, org_id, warehouse_id, location_id, equipment_id, device_name, excursion_type, started_at, ended_at, min_value, max_value, expected_min, expected_max, affected_products, affected_batches, quantity_affected, quarantined, quarantine_reference, disposition, notified_quality, notified_manager, technical_advice, root_cause, capa_id, status, created_by, updated_by, created_at, updated_at FROM temperature_excursions
WHERE id = $1 AND org_id = $2
`

type GetTemperatureExcursionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetTemperatureExcursion(ctx context.Context, arg GetTemperatureExcursionParams) (TemperatureExcursion, error) {
	row := q.queryRow(ctx, q.getTemperatureExcursionStmt, getTemperatureExcursion, arg.ID, arg.OrgID)
	var i TemperatureExcursion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.LocationID,
		&i.EquipmentID,
		&i.DeviceName,
		&i.ExcursionType,
		&i.StartedAt,
		&i.EndedAt,
		&i.MinValue,
		&i.MaxValue,
		&i.ExpectedMin,
		&i.ExpectedMax,
		&i.AffectedProducts,
		&i.AffectedBatches,
		&i.QuantityAffected,
		&i.Quarantined,
		&i.QuarantineReference,
		&i.Disposition,
		&i.NotifiedQuality,
		&i.NotifiedManager,
		&i.TechnicalAdvice,
		&i.RootCause,
		&i.CapaID,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenTemperatureExcursions = `-- name: ListOpenTemperatureExcursions :many
SELECT id, org_id, warehouse_id, location_id, equipment_id, device_name, excursion_type, started_at, ended_at, min_value, max_value, expected_min, expected_max, affected_products, affected_batches, quantity_affected, quarantined, quarantine_reference, disposition, notified_quality, notified_manager, technical_advice, root_cause, capa_id, status, created_by, updated_by, created_at, updated_at FROM temperature_excursions
WHERE org_id = $1 AND status <> 'closed'
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListOpenTemperatureExcursionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListOpenTemperatureExcursions(ctx context.Context, arg ListOpenTemperatureExcursionsParams) ([]TemperatureExcursion, error) {
	rows, err := q.query(ctx, q.listOpenTemperatureExcursionsStmt, listOpenTemperatureExcursions, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureExcursion{}
	for rows.Next() {
		var i TemperatureExcursion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.LocationID,
			&i.EquipmentID,
			&i.DeviceName,
			&i.ExcursionType,
			&i.StartedAt,
			&i.EndedAt,
			&i.MinValue,
			&i.MaxValue,
			&i.ExpectedMin,
			&i.ExpectedMax,
			&i.AffectedProducts,
			&i.AffectedBatches,
			&i.QuantityAffected,
			&i.Quarantined,
			&i.QuarantineReference,
			&i.Disposition,
			&i.NotifiedQuality,
			&i.NotifiedManager,
			&i.TechnicalAdvice,
			&i.RootCause,
			&i.CapaID,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemperatureExcursions = `-- name: ListTemperatureExcursions :many
SELECT id, org_id, warehouse_id, location_id, equipment_id, device_name, excursion_type, started_at, ended_at, min_value, max_value, expected_min, expected_max, affected_products, affected_batches, quantity_affected, quarantined, quarantine_reference, disposition, notified_quality, notified_manager, technical_advice, root_cause, capa_id, status, created_by, updated_by, created_at, updated_at FROM temperature_excursions
WHERE org_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListTemperatureExcursionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListTemperatureExcursions(ctx context.Context, arg ListTemperatureExcursionsParams) ([]TemperatureExcursion, error) {
	rows, err := q.query(ctx, q.listTemperatureExcursionsStmt, listTemperatureExcursions, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureExcursion{}
	for rows.Next() {
		var i TemperatureExcursion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.LocationID,
			&i.EquipmentID,
			&i.DeviceName,
			&i.ExcursionType,
			&i.StartedAt,
			&i.EndedAt,
			&i.MinValue,
			&i.MaxValue,
			&i.ExpectedMin,
			&i.ExpectedMax,
			&i.AffectedProducts,
			&i.AffectedBatches,
			&i.QuantityAffected,
			&i.Quarantined,
			&i.QuarantineReference,
			&i.Disposition,
			&i.NotifiedQuality,
			&i.NotifiedManager,
			&i.TechnicalAdvice,
			&i.RootCause,
			&i.CapaID,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemperatureMonitoringEntries = `-- name: ListTemperatureMonitoringEntries :many
SELECT id, org_id, warehouse_id, location_id, equipment_id, device_name, monitor_type, reading_value, min_threshold, max_threshold, recorded_at, recorded_by, created_at FROM temperature_monitoring_entries
WHERE org_id = $1
ORDER BY recorded_at DESC
LIMIT $2 OFFSET $3
`

type ListTemperatureMonitoringEntriesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListTemperatureMonitoringEntries(ctx context.Context, arg ListTemperatureMonitoringEntriesParams) ([]TemperatureMonitoringEntry, error) {
	rows, err := q.query(ctx, q.listTemperatureMonitoringEntriesStmt, listTemperatureMonitoringEntries, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureMonitoringEntry{}
	for rows.Next() {
		var i TemperatureMonitoringEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.LocationID,
			&i.EquipmentID,
			&i.DeviceName,
			&i.MonitorType,
			&i.ReadingValue,
			&i.MinThreshold,
			&i.MaxThreshold,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemperatureMonitoringEntriesByWarehouse = `-- name: ListTemperatureMonitoringEntriesByWarehouse :many
SELECT id, org_id, warehouse_id, location_id, equipment_id, device_name, monitor_type, reading_value, min_threshold, max_threshold, recorded_at, recorded_by, created_at FROM temperature_monitoring_entries
WHERE org_id = $1 AND warehouse_id = $2 AND monitor_type = $3
  AND recorded_at >= $4 AND recorded_at <= $5
ORDER BY recorded_at ASC
LIMIT $6 OFFSET $7
`

type ListTemperatureMonitoringEntriesByWarehouseParams struct {
	OrgID        string    `json:"org_id"`
	WarehouseID  string    `json:"warehouse_id"`
	MonitorType  string    `json:"monitor_type"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListTemperatureMonitoringEntriesByWarehouse(ctx context.Context, arg ListTemperatureMonitoringEntriesByWarehouseParams) ([]TemperatureMonitoringEntry, error) {
	rows, err := q.query(ctx, q.listTemperatureMonitoringEntriesByWarehouseStmt, listTemperatureMonitoringEntriesByWarehouse,
		arg.OrgID,
		arg.WarehouseID,
		arg.MonitorType,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemperatureMonitoringEntry{}
	for rows.Next() {
		var i TemperatureMonitoringEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.LocationID,
			&i.EquipmentID,
			&i.DeviceName,
			&i.MonitorType,
			&i.ReadingValue,
			&i.MinThreshold,
			&i.MaxThreshold,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemperatureExcursionDisposition = `-- name: UpdateTemperatureExcursionDisposition :exec
UPDATE temperature_excursions SET
    disposition = $1, status = $2, technical_advice = $3,
    root_cause = $4, capa_id = $5, ended_at = $6,
    updated_by = $7, updated_at = now()
WHERE id = $8 AND org_id = $9
`

type UpdateTemperatureExcursionDispositionParams struct {
	Disposition     string         `json:"disposition"`
	Status          string         `json:"status"`
	TechnicalAdvice sql.NullString `json:"technical_advice"`
	RootCause       sql.NullString `json:"root_cause"`
	CapaID          uuid.NullUUID  `json:"capa_id"`
	EndedAt         sql.NullTime   `json:"ended_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
}

func (q *Queries) UpdateTemperatureExcursionDisposition(ctx context.Context, arg UpdateTemperatureExcursionDispositionParams) error {
	_, err := q.exec(ctx, q.updateTemperatureExcursionDispositionStmt, updateTemperatureExcursionDisposition,
		arg.Disposition,
		arg.Status,
		arg.TechnicalAdvice,
		arg.RootCause,
		arg.CapaID,
		arg.EndedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
