// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_regulatory.sql

package db

import (
	"context"
	"database/sql"
)

const createRegulatoryApproval = `-- name: CreateRegulatoryApproval :one

INSERT INTO regulatory_approvals (
    org_id, scope_type, scope_id, authority, license_type, reference_number,
    product_scope, conditions, issue_date, expiry_date, renewal_lead_days,
    responsible_owner, status, evidence_url, notes, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, org_id, scope_type, scope_id, authority, license_type, reference_number, product_scope, conditions, issue_date, expiry_date, renewal_lead_days, responsible_owner, status, evidence_url, notes, created_by, updated_by, created_at, updated_at
`

type CreateRegulatoryApprovalParams struct {
	OrgID            string         `json:"org_id"`
	ScopeType        string         `json:"scope_type"`
	ScopeID          string         `json:"scope_id"`
	Authority        string         `json:"authority"`
	LicenseType      string         `json:"license_type"`
	ReferenceNumber  string         `json:"reference_number"`
	ProductScope     sql.NullString `json:"product_scope"`
	Conditions       sql.NullString `json:"conditions"`
	IssueDate        sql.NullTime   `json:"issue_date"`
	ExpiryDate       sql.NullTime   `json:"expiry_date"`
	RenewalLeadDays  int32          `json:"renewal_lead_days"`
	ResponsibleOwner sql.NullString `json:"responsible_owner"`
	Status           string         `json:"status"`
	EvidenceUrl      sql.NullString `json:"evidence_url"`
	Notes            sql.NullString `json:"notes"`
	CreatedBy        sql.NullString `json:"created_by"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

// Policy §8 — Regulatory & Legal Compliance (Bangladesh DGDA/DNC matrix)
func (q *Queries) CreateRegulatoryApproval(ctx context.Context, arg CreateRegulatoryApprovalParams) (RegulatoryApproval, error) {
	row := q.queryRow(ctx, q.createRegulatoryApprovalStmt, createRegulatoryApproval,
		arg.OrgID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Authority,
		arg.LicenseType,
		arg.ReferenceNumber,
		arg.ProductScope,
		arg.Conditions,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.RenewalLeadDays,
		arg.ResponsibleOwner,
		arg.Status,
		arg.EvidenceUrl,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RegulatoryApproval
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Authority,
		&i.LicenseType,
		&i.ReferenceNumber,
		&i.ProductScope,
		&i.Conditions,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.ResponsibleOwner,
		&i.Status,
		&i.EvidenceUrl,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegulatoryApproval = `-- name: GetRegulatoryApproval :one
SELECT id, org_id, scope_type, scope_id, authority, license_type, reference_number, product_scope, conditions, issue_date, expiry_date, renewal_lead_days, responsible_owner, status, evidence_url, notes, created_by, updated_by, created_at, updated_at FROM regulatory_approvals
WHERE id = $1 AND org_id = $2
`

type GetRegulatoryApprovalParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetRegulatoryApproval(ctx context.Context, arg GetRegulatoryApprovalParams) (RegulatoryApproval, error) {
	row := q.queryRow(ctx, q.getRegulatoryApprovalStmt, getRegulatoryApproval, arg.ID, arg.OrgID)
	var i RegulatoryApproval
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Authority,
		&i.LicenseType,
		&i.ReferenceNumber,
		&i.ProductScope,
		&i.Conditions,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.ResponsibleOwner,
		&i.Status,
		&i.EvidenceUrl,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiringRegulatoryApprovals = `-- name: ListExpiringRegulatoryApprovals :many
SELECT id, org_id, scope_type, scope_id, authority, license_type, reference_number, product_scope, conditions, issue_date, expiry_date, renewal_lead_days, responsible_owner, status, evidence_url, notes, created_by, updated_by, created_at, updated_at FROM regulatory_approvals
WHERE org_id = $1 AND expiry_date IS NOT NULL
  AND expiry_date <= $2
ORDER BY expiry_date ASC
LIMIT $3 OFFSET $4
`

type ListExpiringRegulatoryApprovalsParams struct {
	OrgID      string       `json:"org_id"`
	ExpiryDate sql.NullTime `json:"expiry_date"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
}

func (q *Queries) ListExpiringRegulatoryApprovals(ctx context.Context, arg ListExpiringRegulatoryApprovalsParams) ([]RegulatoryApproval, error) {
	rows, err := q.query(ctx, q.listExpiringRegulatoryApprovalsStmt, listExpiringRegulatoryApprovals,
		arg.OrgID,
		arg.ExpiryDate,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegulatoryApproval{}
	for rows.Next() {
		var i RegulatoryApproval
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Authority,
			&i.LicenseType,
			&i.ReferenceNumber,
			&i.ProductScope,
			&i.Conditions,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.RenewalLeadDays,
			&i.ResponsibleOwner,
			&i.Status,
			&i.EvidenceUrl,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulatoryApprovals = `-- name: ListRegulatoryApprovals :many
SELECT id, org_id, scope_type, scope_id, authority, license_type, reference_number, product_scope, conditions, issue_date, expiry_date, renewal_lead_days, responsible_owner, status, evidence_url, notes, created_by, updated_by, created_at, updated_at FROM regulatory_approvals
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRegulatoryApprovalsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRegulatoryApprovals(ctx context.Context, arg ListRegulatoryApprovalsParams) ([]RegulatoryApproval, error) {
	rows, err := q.query(ctx, q.listRegulatoryApprovalsStmt, listRegulatoryApprovals, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegulatoryApproval{}
	for rows.Next() {
		var i RegulatoryApproval
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Authority,
			&i.LicenseType,
			&i.ReferenceNumber,
			&i.ProductScope,
			&i.Conditions,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.RenewalLeadDays,
			&i.ResponsibleOwner,
			&i.Status,
			&i.EvidenceUrl,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegulatoryApprovalStatus = `-- name: UpdateRegulatoryApprovalStatus :exec
UPDATE regulatory_approvals SET
    status = $1, updated_by = $2, updated_at = now()
WHERE id = $3 AND org_id = $4
`

type UpdateRegulatoryApprovalStatusParams struct {
	Status    string         `json:"status"`
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
}

func (q *Queries) UpdateRegulatoryApprovalStatus(ctx context.Context, arg UpdateRegulatoryApprovalStatusParams) error {
	_, err := q.exec(ctx, q.updateRegulatoryApprovalStatusStmt, updateRegulatoryApprovalStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
