// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_planning.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChangeControl = `-- name: CreateChangeControl :one
INSERT INTO change_controls (
    org_id, change_number, subject_type, subject_id, description, impact_assessment,
    risk_level, requires_quality_review, authorized_by, authorization_date,
    start_date, end_date, status, closure_evidence, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, org_id, change_number, subject_type, subject_id, description, impact_assessment, risk_level, requires_quality_review, authorized_by, authorization_date, start_date, end_date, status, closure_evidence, created_by, updated_by, created_at, updated_at
`

type CreateChangeControlParams struct {
	OrgID                 string         `json:"org_id"`
	ChangeNumber          string         `json:"change_number"`
	SubjectType           string         `json:"subject_type"`
	SubjectID             sql.NullString `json:"subject_id"`
	Description           string         `json:"description"`
	ImpactAssessment      sql.NullString `json:"impact_assessment"`
	RiskLevel             string         `json:"risk_level"`
	RequiresQualityReview bool           `json:"requires_quality_review"`
	AuthorizedBy          sql.NullString `json:"authorized_by"`
	AuthorizationDate     sql.NullTime   `json:"authorization_date"`
	StartDate             sql.NullTime   `json:"start_date"`
	EndDate               sql.NullTime   `json:"end_date"`
	Status                string         `json:"status"`
	ClosureEvidence       sql.NullString `json:"closure_evidence"`
	CreatedBy             sql.NullString `json:"created_by"`
	UpdatedBy             sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateChangeControl(ctx context.Context, arg CreateChangeControlParams) (ChangeControl, error) {
	row := q.queryRow(ctx, q.createChangeControlStmt, createChangeControl,
		arg.OrgID,
		arg.ChangeNumber,
		arg.SubjectType,
		arg.SubjectID,
		arg.Description,
		arg.ImpactAssessment,
		arg.RiskLevel,
		arg.RequiresQualityReview,
		arg.AuthorizedBy,
		arg.AuthorizationDate,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ClosureEvidence,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ChangeControl
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChangeNumber,
		&i.SubjectType,
		&i.SubjectID,
		&i.Description,
		&i.ImpactAssessment,
		&i.RiskLevel,
		&i.RequiresQualityReview,
		&i.AuthorizedBy,
		&i.AuthorizationDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosureEvidence,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmergencyPlan = `-- name: CreateEmergencyPlan :one

INSERT INTO emergency_plans (
    org_id, plan_number, name, country_code, facility_id, scenario_type, scenario,
    demand_assumptions, service_level, prepositioned_stock_plan, rotation_plan,
    alternate_suppliers, alternate_warehouses, alternate_routes,
    alternate_power_sources, emergency_authority, paper_fallback_records,
    minimum_staffing, cold_chain_contingency, communications, escalation_contacts,
    security_controls, return_to_normal_plan, status, approved_by, approved_at,
    created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
RETURNING id, org_id, plan_number, name, country_code, facility_id, scenario_type, scenario, demand_assumptions, service_level, prepositioned_stock_plan, rotation_plan, alternate_suppliers, alternate_warehouses, alternate_routes, alternate_power_sources, emergency_authority, paper_fallback_records, minimum_staffing, cold_chain_contingency, communications, escalation_contacts, security_controls, return_to_normal_plan, status, approved_by, approved_at, created_by, updated_by, created_at, updated_at
`

type CreateEmergencyPlanParams struct {
	OrgID                  string         `json:"org_id"`
	PlanNumber             string         `json:"plan_number"`
	Name                   string         `json:"name"`
	CountryCode            sql.NullString `json:"country_code"`
	FacilityID             uuid.NullUUID  `json:"facility_id"`
	ScenarioType           string         `json:"scenario_type"`
	Scenario               sql.NullString `json:"scenario"`
	DemandAssumptions      sql.NullString `json:"demand_assumptions"`
	ServiceLevel           sql.NullString `json:"service_level"`
	PrepositionedStockPlan sql.NullString `json:"prepositioned_stock_plan"`
	RotationPlan           sql.NullString `json:"rotation_plan"`
	AlternateSuppliers     sql.NullString `json:"alternate_suppliers"`
	AlternateWarehouses    sql.NullString `json:"alternate_warehouses"`
	AlternateRoutes        sql.NullString `json:"alternate_routes"`
	AlternatePowerSources  sql.NullString `json:"alternate_power_sources"`
	EmergencyAuthority     sql.NullString `json:"emergency_authority"`
	PaperFallbackRecords   bool           `json:"paper_fallback_records"`
	MinimumStaffing        sql.NullString `json:"minimum_staffing"`
	ColdChainContingency   sql.NullString `json:"cold_chain_contingency"`
	Communications         sql.NullString `json:"communications"`
	EscalationContacts     sql.NullString `json:"escalation_contacts"`
	SecurityControls       sql.NullString `json:"security_controls"`
	ReturnToNormalPlan     sql.NullString `json:"return_to_normal_plan"`
	Status                 string         `json:"status"`
	ApprovedBy             sql.NullString `json:"approved_by"`
	ApprovedAt             sql.NullTime   `json:"approved_at"`
	CreatedBy              sql.NullString `json:"created_by"`
	UpdatedBy              sql.NullString `json:"updated_by"`
}

// Policy §20 / §27 — Emergency plans and change control
func (q *Queries) CreateEmergencyPlan(ctx context.Context, arg CreateEmergencyPlanParams) (EmergencyPlan, error) {
	row := q.queryRow(ctx, q.createEmergencyPlanStmt, createEmergencyPlan,
		arg.OrgID,
		arg.PlanNumber,
		arg.Name,
		arg.CountryCode,
		arg.FacilityID,
		arg.ScenarioType,
		arg.Scenario,
		arg.DemandAssumptions,
		arg.ServiceLevel,
		arg.PrepositionedStockPlan,
		arg.RotationPlan,
		arg.AlternateSuppliers,
		arg.AlternateWarehouses,
		arg.AlternateRoutes,
		arg.AlternatePowerSources,
		arg.EmergencyAuthority,
		arg.PaperFallbackRecords,
		arg.MinimumStaffing,
		arg.ColdChainContingency,
		arg.Communications,
		arg.EscalationContacts,
		arg.SecurityControls,
		arg.ReturnToNormalPlan,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i EmergencyPlan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanNumber,
		&i.Name,
		&i.CountryCode,
		&i.FacilityID,
		&i.ScenarioType,
		&i.Scenario,
		&i.DemandAssumptions,
		&i.ServiceLevel,
		&i.PrepositionedStockPlan,
		&i.RotationPlan,
		&i.AlternateSuppliers,
		&i.AlternateWarehouses,
		&i.AlternateRoutes,
		&i.AlternatePowerSources,
		&i.EmergencyAuthority,
		&i.PaperFallbackRecords,
		&i.MinimumStaffing,
		&i.ColdChainContingency,
		&i.Communications,
		&i.EscalationContacts,
		&i.SecurityControls,
		&i.ReturnToNormalPlan,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangeControl = `-- name: GetChangeControl :one
SELECT id, org_id, change_number, subject_type, subject_id, description, impact_assessment, risk_level, requires_quality_review, authorized_by, authorization_date, start_date, end_date, status, closure_evidence, created_by, updated_by, created_at, updated_at FROM change_controls
WHERE id = $1 AND org_id = $2
`

type GetChangeControlParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetChangeControl(ctx context.Context, arg GetChangeControlParams) (ChangeControl, error) {
	row := q.queryRow(ctx, q.getChangeControlStmt, getChangeControl, arg.ID, arg.OrgID)
	var i ChangeControl
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChangeNumber,
		&i.SubjectType,
		&i.SubjectID,
		&i.Description,
		&i.ImpactAssessment,
		&i.RiskLevel,
		&i.RequiresQualityReview,
		&i.AuthorizedBy,
		&i.AuthorizationDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosureEvidence,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyPlan = `-- name: GetEmergencyPlan :one
SELECT id, org_id, plan_number, name, country_code, facility_id, scenario_type, scenario, demand_assumptions, service_level, prepositioned_stock_plan, rotation_plan, alternate_suppliers, alternate_warehouses, alternate_routes, alternate_power_sources, emergency_authority, paper_fallback_records, minimum_staffing, cold_chain_contingency, communications, escalation_contacts, security_controls, return_to_normal_plan, status, approved_by, approved_at, created_by, updated_by, created_at, updated_at FROM emergency_plans
WHERE id = $1 AND org_id = $2
`

type GetEmergencyPlanParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetEmergencyPlan(ctx context.Context, arg GetEmergencyPlanParams) (EmergencyPlan, error) {
	row := q.queryRow(ctx, q.getEmergencyPlanStmt, getEmergencyPlan, arg.ID, arg.OrgID)
	var i EmergencyPlan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanNumber,
		&i.Name,
		&i.CountryCode,
		&i.FacilityID,
		&i.ScenarioType,
		&i.Scenario,
		&i.DemandAssumptions,
		&i.ServiceLevel,
		&i.PrepositionedStockPlan,
		&i.RotationPlan,
		&i.AlternateSuppliers,
		&i.AlternateWarehouses,
		&i.AlternateRoutes,
		&i.AlternatePowerSources,
		&i.EmergencyAuthority,
		&i.PaperFallbackRecords,
		&i.MinimumStaffing,
		&i.ColdChainContingency,
		&i.Communications,
		&i.EscalationContacts,
		&i.SecurityControls,
		&i.ReturnToNormalPlan,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChangeControls = `-- name: ListChangeControls :many
SELECT id, org_id, change_number, subject_type, subject_id, description, impact_assessment, risk_level, requires_quality_review, authorized_by, authorization_date, start_date, end_date, status, closure_evidence, created_by, updated_by, created_at, updated_at FROM change_controls
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChangeControlsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListChangeControls(ctx context.Context, arg ListChangeControlsParams) ([]ChangeControl, error) {
	rows, err := q.query(ctx, q.listChangeControlsStmt, listChangeControls, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeControl{}
	for rows.Next() {
		var i ChangeControl
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ChangeNumber,
			&i.SubjectType,
			&i.SubjectID,
			&i.Description,
			&i.ImpactAssessment,
			&i.RiskLevel,
			&i.RequiresQualityReview,
			&i.AuthorizedBy,
			&i.AuthorizationDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ClosureEvidence,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmergencyPlans = `-- name: ListEmergencyPlans :many
SELECT id, org_id, plan_number, name, country_code, facility_id, scenario_type, scenario, demand_assumptions, service_level, prepositioned_stock_plan, rotation_plan, alternate_suppliers, alternate_warehouses, alternate_routes, alternate_power_sources, emergency_authority, paper_fallback_records, minimum_staffing, cold_chain_contingency, communications, escalation_contacts, security_controls, return_to_normal_plan, status, approved_by, approved_at, created_by, updated_by, created_at, updated_at FROM emergency_plans
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmergencyPlansParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListEmergencyPlans(ctx context.Context, arg ListEmergencyPlansParams) ([]EmergencyPlan, error) {
	rows, err := q.query(ctx, q.listEmergencyPlansStmt, listEmergencyPlans, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyPlan{}
	for rows.Next() {
		var i EmergencyPlan
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PlanNumber,
			&i.Name,
			&i.CountryCode,
			&i.FacilityID,
			&i.ScenarioType,
			&i.Scenario,
			&i.DemandAssumptions,
			&i.ServiceLevel,
			&i.PrepositionedStockPlan,
			&i.RotationPlan,
			&i.AlternateSuppliers,
			&i.AlternateWarehouses,
			&i.AlternateRoutes,
			&i.AlternatePowerSources,
			&i.EmergencyAuthority,
			&i.PaperFallbackRecords,
			&i.MinimumStaffing,
			&i.ColdChainContingency,
			&i.Communications,
			&i.EscalationContacts,
			&i.SecurityControls,
			&i.ReturnToNormalPlan,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
