// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_donations.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDonation = `-- name: CreateDonation :one

INSERT INTO donations (
    org_id, donation_number, donor_name, donor_contact, offer_date, decision,
    decision_date, decided_by, needs_assessment, proposed_recipient,
    approval_reference, transport_responsibility, customs_notes,
    disposal_responsibility, certificate_number, certificate_issued_date,
    registry_reference, status, notes, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, org_id, donation_number, donor_name, donor_contact, offer_date, decision, decision_date, decided_by, needs_assessment, proposed_recipient, approval_reference, transport_responsibility, customs_notes, disposal_responsibility, certificate_number, certificate_issued_date, registry_reference, status, notes, created_by, updated_by, created_at, updated_at
`

type CreateDonationParams struct {
	OrgID                   string         `json:"org_id"`
	DonationNumber          string         `json:"donation_number"`
	DonorName               string         `json:"donor_name"`
	DonorContact            sql.NullString `json:"donor_contact"`
	OfferDate               time.Time      `json:"offer_date"`
	Decision                sql.NullString `json:"decision"`
	DecisionDate            sql.NullTime   `json:"decision_date"`
	DecidedBy               sql.NullString `json:"decided_by"`
	NeedsAssessment         sql.NullString `json:"needs_assessment"`
	ProposedRecipient       sql.NullString `json:"proposed_recipient"`
	ApprovalReference       sql.NullString `json:"approval_reference"`
	TransportResponsibility sql.NullString `json:"transport_responsibility"`
	CustomsNotes            sql.NullString `json:"customs_notes"`
	DisposalResponsibility  sql.NullString `json:"disposal_responsibility"`
	CertificateNumber       sql.NullString `json:"certificate_number"`
	CertificateIssuedDate   sql.NullTime   `json:"certificate_issued_date"`
	RegistryReference       sql.NullString `json:"registry_reference"`
	Status                  string         `json:"status"`
	Notes                   sql.NullString `json:"notes"`
	CreatedBy               sql.NullString `json:"created_by"`
	UpdatedBy               sql.NullString `json:"updated_by"`
}

// Policy §11.3 — Donation registry and acceptance/rejection workflow
func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.queryRow(ctx, q.createDonationStmt, createDonation,
		arg.OrgID,
		arg.DonationNumber,
		arg.DonorName,
		arg.DonorContact,
		arg.OfferDate,
		arg.Decision,
		arg.DecisionDate,
		arg.DecidedBy,
		arg.NeedsAssessment,
		arg.ProposedRecipient,
		arg.ApprovalReference,
		arg.TransportResponsibility,
		arg.CustomsNotes,
		arg.DisposalResponsibility,
		arg.CertificateNumber,
		arg.CertificateIssuedDate,
		arg.RegistryReference,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DonationNumber,
		&i.DonorName,
		&i.DonorContact,
		&i.OfferDate,
		&i.Decision,
		&i.DecisionDate,
		&i.DecidedBy,
		&i.NeedsAssessment,
		&i.ProposedRecipient,
		&i.ApprovalReference,
		&i.TransportResponsibility,
		&i.CustomsNotes,
		&i.DisposalResponsibility,
		&i.CertificateNumber,
		&i.CertificateIssuedDate,
		&i.RegistryReference,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDonationLineItem = `-- name: CreateDonationLineItem :one
INSERT INTO donation_line_items (
    donation_id, product_id, batch_number, expiry_date, quantity, uom,
    remaining_shelf_life_months, condition, shelf_life_compliant, authorized, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, donation_id, product_id, batch_number, expiry_date, quantity, uom, remaining_shelf_life_months, condition, shelf_life_compliant, authorized, notes
`

type CreateDonationLineItemParams struct {
	DonationID               string         `json:"donation_id"`
	ProductID                string         `json:"product_id"`
	BatchNumber              sql.NullString `json:"batch_number"`
	ExpiryDate               sql.NullTime   `json:"expiry_date"`
	Quantity                 string         `json:"quantity"`
	Uom                      sql.NullString `json:"uom"`
	RemainingShelfLifeMonths sql.NullInt32  `json:"remaining_shelf_life_months"`
	Condition                sql.NullString `json:"condition"`
	ShelfLifeCompliant       sql.NullBool   `json:"shelf_life_compliant"`
	Authorized               bool           `json:"authorized"`
	Notes                    sql.NullString `json:"notes"`
}

func (q *Queries) CreateDonationLineItem(ctx context.Context, arg CreateDonationLineItemParams) (DonationLineItem, error) {
	row := q.queryRow(ctx, q.createDonationLineItemStmt, createDonationLineItem,
		arg.DonationID,
		arg.ProductID,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.Quantity,
		arg.Uom,
		arg.RemainingShelfLifeMonths,
		arg.Condition,
		arg.ShelfLifeCompliant,
		arg.Authorized,
		arg.Notes,
	)
	var i DonationLineItem
	err := row.Scan(
		&i.ID,
		&i.DonationID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Uom,
		&i.RemainingShelfLifeMonths,
		&i.Condition,
		&i.ShelfLifeCompliant,
		&i.Authorized,
		&i.Notes,
	)
	return i, err
}

const getDonation = `-- name: GetDonation :one
SELECT id, org_id, donation_number, donor_name, donor_contact, offer_date, decision, decision_date, decided_by, needs_assessment, proposed_recipient, approval_reference, transport_responsibility, customs_notes, disposal_responsibility, certificate_number, certificate_issued_date, registry_reference, status, notes, created_by, updated_by, created_at, updated_at FROM donations
WHERE id = $1 AND org_id = $2
`

type GetDonationParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetDonation(ctx context.Context, arg GetDonationParams) (Donation, error) {
	row := q.queryRow(ctx, q.getDonationStmt, getDonation, arg.ID, arg.OrgID)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DonationNumber,
		&i.DonorName,
		&i.DonorContact,
		&i.OfferDate,
		&i.Decision,
		&i.DecisionDate,
		&i.DecidedBy,
		&i.NeedsAssessment,
		&i.ProposedRecipient,
		&i.ApprovalReference,
		&i.TransportResponsibility,
		&i.CustomsNotes,
		&i.DisposalResponsibility,
		&i.CertificateNumber,
		&i.CertificateIssuedDate,
		&i.RegistryReference,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDonationLineItems = `-- name: GetDonationLineItems :many
SELECT id, donation_id, product_id, batch_number, expiry_date, quantity, uom, remaining_shelf_life_months, condition, shelf_life_compliant, authorized, notes FROM donation_line_items
WHERE donation_id = $1
ORDER BY expiry_date NULLS LAST, id
`

func (q *Queries) GetDonationLineItems(ctx context.Context, donationID string) ([]DonationLineItem, error) {
	rows, err := q.query(ctx, q.getDonationLineItemsStmt, getDonationLineItems, donationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DonationLineItem{}
	for rows.Next() {
		var i DonationLineItem
		if err := rows.Scan(
			&i.ID,
			&i.DonationID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Uom,
			&i.RemainingShelfLifeMonths,
			&i.Condition,
			&i.ShelfLifeCompliant,
			&i.Authorized,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonations = `-- name: ListDonations :many
SELECT id, org_id, donation_number, donor_name, donor_contact, offer_date, decision, decision_date, decided_by, needs_assessment, proposed_recipient, approval_reference, transport_responsibility, customs_notes, disposal_responsibility, certificate_number, certificate_issued_date, registry_reference, status, notes, created_by, updated_by, created_at, updated_at FROM donations
WHERE org_id = $1
ORDER BY offer_date DESC
LIMIT $2 OFFSET $3
`

type ListDonationsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDonations(ctx context.Context, arg ListDonationsParams) ([]Donation, error) {
	rows, err := q.query(ctx, q.listDonationsStmt, listDonations, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Donation{}
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DonationNumber,
			&i.DonorName,
			&i.DonorContact,
			&i.OfferDate,
			&i.Decision,
			&i.DecisionDate,
			&i.DecidedBy,
			&i.NeedsAssessment,
			&i.ProposedRecipient,
			&i.ApprovalReference,
			&i.TransportResponsibility,
			&i.CustomsNotes,
			&i.DisposalResponsibility,
			&i.CertificateNumber,
			&i.CertificateIssuedDate,
			&i.RegistryReference,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonationsByStatus = `-- name: ListDonationsByStatus :many
SELECT id, org_id, donation_number, donor_name, donor_contact, offer_date, decision, decision_date, decided_by, needs_assessment, proposed_recipient, approval_reference, transport_responsibility, customs_notes, disposal_responsibility, certificate_number, certificate_issued_date, registry_reference, status, notes, created_by, updated_by, created_at, updated_at FROM donations
WHERE org_id = $1 AND status = $2
ORDER BY offer_date DESC
LIMIT $3 OFFSET $4
`

type ListDonationsByStatusParams struct {
	OrgID  string `json:"org_id"`
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDonationsByStatus(ctx context.Context, arg ListDonationsByStatusParams) ([]Donation, error) {
	rows, err := q.query(ctx, q.listDonationsByStatusStmt, listDonationsByStatus,
		arg.OrgID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Donation{}
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DonationNumber,
			&i.DonorName,
			&i.DonorContact,
			&i.OfferDate,
			&i.Decision,
			&i.DecisionDate,
			&i.DecidedBy,
			&i.NeedsAssessment,
			&i.ProposedRecipient,
			&i.ApprovalReference,
			&i.TransportResponsibility,
			&i.CustomsNotes,
			&i.DisposalResponsibility,
			&i.CertificateNumber,
			&i.CertificateIssuedDate,
			&i.RegistryReference,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonationDecision = `-- name: UpdateDonationDecision :exec
UPDATE donations SET
    decision = $1, status = $2, decision_date = $3, decided_by = $4,
    certificate_number = $5, certificate_issued_date = $6,
    updated_by = $7, updated_at = now()
WHERE id = $8 AND org_id = $9
`

type UpdateDonationDecisionParams struct {
	Decision              sql.NullString `json:"decision"`
	Status                string         `json:"status"`
	DecisionDate          sql.NullTime   `json:"decision_date"`
	DecidedBy             sql.NullString `json:"decided_by"`
	CertificateNumber     sql.NullString `json:"certificate_number"`
	CertificateIssuedDate sql.NullTime   `json:"certificate_issued_date"`
	UpdatedBy             sql.NullString `json:"updated_by"`
	ID                    string         `json:"id"`
	OrgID                 string         `json:"org_id"`
}

func (q *Queries) UpdateDonationDecision(ctx context.Context, arg UpdateDonationDecisionParams) error {
	_, err := q.exec(ctx, q.updateDonationDecisionStmt, updateDonationDecision,
		arg.Decision,
		arg.Status,
		arg.DecisionDate,
		arg.DecidedBy,
		arg.CertificateNumber,
		arg.CertificateIssuedDate,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
