// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_quality.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCAPAAction = `-- name: CreateCAPAAction :one
INSERT INTO capa_actions (
    org_id, capa_number, source_type, source_id, capa_type, title,
    root_cause, action_plan, responsible_owner, due_date, status,
    effectiveness_check, effectiveness_verified, effectiveness_verified_by,
    verified_at, closed_by, closed_at, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, org_id, capa_number, source_type, source_id, capa_type, title, root_cause, action_plan, responsible_owner, due_date, status, effectiveness_check, effectiveness_verified, effectiveness_verified_by, verified_at, closed_by, closed_at, created_by, updated_by, created_at, updated_at
`

type CreateCAPAActionParams struct {
	OrgID                   string         `json:"org_id"`
	CapaNumber              string         `json:"capa_number"`
	SourceType              string         `json:"source_type"`
	SourceID                sql.NullString `json:"source_id"`
	CapaType                string         `json:"capa_type"`
	Title                   string         `json:"title"`
	RootCause               sql.NullString `json:"root_cause"`
	ActionPlan              string         `json:"action_plan"`
	ResponsibleOwner        sql.NullString `json:"responsible_owner"`
	DueDate                 sql.NullTime   `json:"due_date"`
	Status                  string         `json:"status"`
	EffectivenessCheck      sql.NullString `json:"effectiveness_check"`
	EffectivenessVerified   bool           `json:"effectiveness_verified"`
	EffectivenessVerifiedBy sql.NullString `json:"effectiveness_verified_by"`
	VerifiedAt              sql.NullTime   `json:"verified_at"`
	ClosedBy                sql.NullString `json:"closed_by"`
	ClosedAt                sql.NullTime   `json:"closed_at"`
	CreatedBy               sql.NullString `json:"created_by"`
	UpdatedBy               sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateCAPAAction(ctx context.Context, arg CreateCAPAActionParams) (CapaAction, error) {
	row := q.queryRow(ctx, q.createCAPAActionStmt, createCAPAAction,
		arg.OrgID,
		arg.CapaNumber,
		arg.SourceType,
		arg.SourceID,
		arg.CapaType,
		arg.Title,
		arg.RootCause,
		arg.ActionPlan,
		arg.ResponsibleOwner,
		arg.DueDate,
		arg.Status,
		arg.EffectivenessCheck,
		arg.EffectivenessVerified,
		arg.EffectivenessVerifiedBy,
		arg.VerifiedAt,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CapaAction
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CapaNumber,
		&i.SourceType,
		&i.SourceID,
		&i.CapaType,
		&i.Title,
		&i.RootCause,
		&i.ActionPlan,
		&i.ResponsibleOwner,
		&i.DueDate,
		&i.Status,
		&i.EffectivenessCheck,
		&i.EffectivenessVerified,
		&i.EffectivenessVerifiedBy,
		&i.VerifiedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeviation = `-- name: CreateDeviation :one

INSERT INTO deviations (
    org_id, deviation_number, category_code, occurred_at, reported_at,
    source_document_type, source_document_id, product_id, batch_id,
    warehouse_id, location_id, description, containment_action,
    impact_assessment, root_cause, risk_rating, disposition, status,
    responsible_owner, due_date, escalated, escalated_to, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
RETURNING id, org_id, deviation_number, category_code, occurred_at, reported_at, source_document_type, source_document_id, product_id, batch_id, warehouse_id, location_id, description, containment_action, impact_assessment, root_cause, risk_rating, disposition, status, responsible_owner, due_date, escalated, escalated_to, created_by, updated_by, created_at, updated_at
`

type CreateDeviationParams struct {
	OrgID              string         `json:"org_id"`
	DeviationNumber    string         `json:"deviation_number"`
	CategoryCode       sql.NullString `json:"category_code"`
	OccurredAt         time.Time      `json:"occurred_at"`
	ReportedAt         time.Time      `json:"reported_at"`
	SourceDocumentType sql.NullString `json:"source_document_type"`
	SourceDocumentID   sql.NullString `json:"source_document_id"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	BatchID            uuid.NullUUID  `json:"batch_id"`
	WarehouseID        uuid.NullUUID  `json:"warehouse_id"`
	LocationID         uuid.NullUUID  `json:"location_id"`
	Description        string         `json:"description"`
	ContainmentAction  sql.NullString `json:"containment_action"`
	ImpactAssessment   sql.NullString `json:"impact_assessment"`
	RootCause          sql.NullString `json:"root_cause"`
	RiskRating         string         `json:"risk_rating"`
	Disposition        sql.NullString `json:"disposition"`
	Status             string         `json:"status"`
	ResponsibleOwner   sql.NullString `json:"responsible_owner"`
	DueDate            sql.NullTime   `json:"due_date"`
	Escalated          bool           `json:"escalated"`
	EscalatedTo        sql.NullString `json:"escalated_to"`
	CreatedBy          sql.NullString `json:"created_by"`
	UpdatedBy          sql.NullString `json:"updated_by"`
}

// Policy §7 — QMS: Deviations, CAPA, Training & Competency
func (q *Queries) CreateDeviation(ctx context.Context, arg CreateDeviationParams) (Deviation, error) {
	row := q.queryRow(ctx, q.createDeviationStmt, createDeviation,
		arg.OrgID,
		arg.DeviationNumber,
		arg.CategoryCode,
		arg.OccurredAt,
		arg.ReportedAt,
		arg.SourceDocumentType,
		arg.SourceDocumentID,
		arg.ProductID,
		arg.BatchID,
		arg.WarehouseID,
		arg.LocationID,
		arg.Description,
		arg.ContainmentAction,
		arg.ImpactAssessment,
		arg.RootCause,
		arg.RiskRating,
		arg.Disposition,
		arg.Status,
		arg.ResponsibleOwner,
		arg.DueDate,
		arg.Escalated,
		arg.EscalatedTo,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Deviation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeviationNumber,
		&i.CategoryCode,
		&i.OccurredAt,
		&i.ReportedAt,
		&i.SourceDocumentType,
		&i.SourceDocumentID,
		&i.ProductID,
		&i.BatchID,
		&i.WarehouseID,
		&i.LocationID,
		&i.Description,
		&i.ContainmentAction,
		&i.ImpactAssessment,
		&i.RootCause,
		&i.RiskRating,
		&i.Disposition,
		&i.Status,
		&i.ResponsibleOwner,
		&i.DueDate,
		&i.Escalated,
		&i.EscalatedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrainingRecord = `-- name: CreateTrainingRecord :one
INSERT INTO training_records (
    org_id, user_id, training_title, training_type, topic, training_date,
    method, trainer, assessed, assessment_result, competency_valid_until,
    certificate_url, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, org_id, user_id, training_title, training_type, topic, training_date, method, trainer, assessed, assessment_result, competency_valid_until, certificate_url, created_by, created_at, updated_at
`

type CreateTrainingRecordParams struct {
	OrgID                string         `json:"org_id"`
	UserID               uuid.NullUUID  `json:"user_id"`
	TrainingTitle        string         `json:"training_title"`
	TrainingType         string         `json:"training_type"`
	Topic                sql.NullString `json:"topic"`
	TrainingDate         time.Time      `json:"training_date"`
	Method               sql.NullString `json:"method"`
	Trainer              sql.NullString `json:"trainer"`
	Assessed             bool           `json:"assessed"`
	AssessmentResult     sql.NullString `json:"assessment_result"`
	CompetencyValidUntil sql.NullTime   `json:"competency_valid_until"`
	CertificateUrl       sql.NullString `json:"certificate_url"`
	CreatedBy            sql.NullString `json:"created_by"`
}

func (q *Queries) CreateTrainingRecord(ctx context.Context, arg CreateTrainingRecordParams) (TrainingRecord, error) {
	row := q.queryRow(ctx, q.createTrainingRecordStmt, createTrainingRecord,
		arg.OrgID,
		arg.UserID,
		arg.TrainingTitle,
		arg.TrainingType,
		arg.Topic,
		arg.TrainingDate,
		arg.Method,
		arg.Trainer,
		arg.Assessed,
		arg.AssessmentResult,
		arg.CompetencyValidUntil,
		arg.CertificateUrl,
		arg.CreatedBy,
	)
	var i TrainingRecord
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TrainingTitle,
		&i.TrainingType,
		&i.Topic,
		&i.TrainingDate,
		&i.Method,
		&i.Trainer,
		&i.Assessed,
		&i.AssessmentResult,
		&i.CompetencyValidUntil,
		&i.CertificateUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCAPAAction = `-- name: GetCAPAAction :one
SELECT id, org_id, capa_number, source_type, source_id, capa_type, title, root_cause, action_plan, responsible_owner, due_date, status, effectiveness_check, effectiveness_verified, effectiveness_verified_by, verified_at, closed_by, closed_at, created_by, updated_by, created_at, updated_at FROM capa_actions
WHERE id = $1 AND org_id = $2
`

type GetCAPAActionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetCAPAAction(ctx context.Context, arg GetCAPAActionParams) (CapaAction, error) {
	row := q.queryRow(ctx, q.getCAPAActionStmt, getCAPAAction, arg.ID, arg.OrgID)
	var i CapaAction
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CapaNumber,
		&i.SourceType,
		&i.SourceID,
		&i.CapaType,
		&i.Title,
		&i.RootCause,
		&i.ActionPlan,
		&i.ResponsibleOwner,
		&i.DueDate,
		&i.Status,
		&i.EffectivenessCheck,
		&i.EffectivenessVerified,
		&i.EffectivenessVerifiedBy,
		&i.VerifiedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviation = `-- name: GetDeviation :one
SELECT id, org_id, deviation_number, category_code, occurred_at, reported_at, source_document_type, source_document_id, product_id, batch_id, warehouse_id, location_id, description, containment_action, impact_assessment, root_cause, risk_rating, disposition, status, responsible_owner, due_date, escalated, escalated_to, created_by, updated_by, created_at, updated_at FROM deviations
WHERE id = $1 AND org_id = $2
`

type GetDeviationParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetDeviation(ctx context.Context, arg GetDeviationParams) (Deviation, error) {
	row := q.queryRow(ctx, q.getDeviationStmt, getDeviation, arg.ID, arg.OrgID)
	var i Deviation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeviationNumber,
		&i.CategoryCode,
		&i.OccurredAt,
		&i.ReportedAt,
		&i.SourceDocumentType,
		&i.SourceDocumentID,
		&i.ProductID,
		&i.BatchID,
		&i.WarehouseID,
		&i.LocationID,
		&i.Description,
		&i.ContainmentAction,
		&i.ImpactAssessment,
		&i.RootCause,
		&i.RiskRating,
		&i.Disposition,
		&i.Status,
		&i.ResponsibleOwner,
		&i.DueDate,
		&i.Escalated,
		&i.EscalatedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCAPAActions = `-- name: ListCAPAActions :many
SELECT id, org_id, capa_number, source_type, source_id, capa_type, title, root_cause, action_plan, responsible_owner, due_date, status, effectiveness_check, effectiveness_verified, effectiveness_verified_by, verified_at, closed_by, closed_at, created_by, updated_by, created_at, updated_at FROM capa_actions
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCAPAActionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCAPAActions(ctx context.Context, arg ListCAPAActionsParams) ([]CapaAction, error) {
	rows, err := q.query(ctx, q.listCAPAActionsStmt, listCAPAActions, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapaAction{}
	for rows.Next() {
		var i CapaAction
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CapaNumber,
			&i.SourceType,
			&i.SourceID,
			&i.CapaType,
			&i.Title,
			&i.RootCause,
			&i.ActionPlan,
			&i.ResponsibleOwner,
			&i.DueDate,
			&i.Status,
			&i.EffectivenessCheck,
			&i.EffectivenessVerified,
			&i.EffectivenessVerifiedBy,
			&i.VerifiedAt,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviations = `-- name: ListDeviations :many
SELECT id, org_id, deviation_number, category_code, occurred_at, reported_at, source_document_type, source_document_id, product_id, batch_id, warehouse_id, location_id, description, containment_action, impact_assessment, root_cause, risk_rating, disposition, status, responsible_owner, due_date, escalated, escalated_to, created_by, updated_by, created_at, updated_at FROM deviations
WHERE org_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListDeviationsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDeviations(ctx context.Context, arg ListDeviationsParams) ([]Deviation, error) {
	rows, err := q.query(ctx, q.listDeviationsStmt, listDeviations, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deviation{}
	for rows.Next() {
		var i Deviation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeviationNumber,
			&i.CategoryCode,
			&i.OccurredAt,
			&i.ReportedAt,
			&i.SourceDocumentType,
			&i.SourceDocumentID,
			&i.ProductID,
			&i.BatchID,
			&i.WarehouseID,
			&i.LocationID,
			&i.Description,
			&i.ContainmentAction,
			&i.ImpactAssessment,
			&i.RootCause,
			&i.RiskRating,
			&i.Disposition,
			&i.Status,
			&i.ResponsibleOwner,
			&i.DueDate,
			&i.Escalated,
			&i.EscalatedTo,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviationsByStatus = `-- name: ListDeviationsByStatus :many
SELECT id, org_id, deviation_number, category_code, occurred_at, reported_at, source_document_type, source_document_id, product_id, batch_id, warehouse_id, location_id, description, containment_action, impact_assessment, root_cause, risk_rating, disposition, status, responsible_owner, due_date, escalated, escalated_to, created_by, updated_by, created_at, updated_at FROM deviations
WHERE org_id = $1 AND status = $2
ORDER BY occurred_at DESC
LIMIT $3 OFFSET $4
`

type ListDeviationsByStatusParams struct {
	OrgID  string `json:"org_id"`
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDeviationsByStatus(ctx context.Context, arg ListDeviationsByStatusParams) ([]Deviation, error) {
	rows, err := q.query(ctx, q.listDeviationsByStatusStmt, listDeviationsByStatus,
		arg.OrgID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deviation{}
	for rows.Next() {
		var i Deviation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeviationNumber,
			&i.CategoryCode,
			&i.OccurredAt,
			&i.ReportedAt,
			&i.SourceDocumentType,
			&i.SourceDocumentID,
			&i.ProductID,
			&i.BatchID,
			&i.WarehouseID,
			&i.LocationID,
			&i.Description,
			&i.ContainmentAction,
			&i.ImpactAssessment,
			&i.RootCause,
			&i.RiskRating,
			&i.Disposition,
			&i.Status,
			&i.ResponsibleOwner,
			&i.DueDate,
			&i.Escalated,
			&i.EscalatedTo,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCAPAActions = `-- name: ListOpenCAPAActions :many
SELECT id, org_id, capa_number, source_type, source_id, capa_type, title, root_cause, action_plan, responsible_owner, due_date, status, effectiveness_check, effectiveness_verified, effectiveness_verified_by, verified_at, closed_by, closed_at, created_by, updated_by, created_at, updated_at FROM capa_actions
WHERE org_id = $1 AND status = ANY($2::text[]) AND due_date <= $3
ORDER BY due_date ASC
LIMIT $4 OFFSET $5
`

type ListOpenCAPAActionsParams struct {
	OrgID   string       `json:"org_id"`
	Column2 []string     `json:"column_2"`
	DueDate sql.NullTime `json:"due_date"`
	Limit   int32        `json:"limit"`
	Offset  int32        `json:"offset"`
}

func (q *Queries) ListOpenCAPAActions(ctx context.Context, arg ListOpenCAPAActionsParams) ([]CapaAction, error) {
	rows, err := q.query(ctx, q.listOpenCAPAActionsStmt, listOpenCAPAActions,
		arg.OrgID,
		pq.Array(arg.Column2),
		arg.DueDate,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapaAction{}
	for rows.Next() {
		var i CapaAction
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CapaNumber,
			&i.SourceType,
			&i.SourceID,
			&i.CapaType,
			&i.Title,
			&i.RootCause,
			&i.ActionPlan,
			&i.ResponsibleOwner,
			&i.DueDate,
			&i.Status,
			&i.EffectivenessCheck,
			&i.EffectivenessVerified,
			&i.EffectivenessVerifiedBy,
			&i.VerifiedAt,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingRecords = `-- name: ListTrainingRecords :many
SELECT id, org_id, user_id, training_title, training_type, topic, training_date, method, trainer, assessed, assessment_result, competency_valid_until, certificate_url, created_by, created_at, updated_at FROM training_records
WHERE org_id = $1
ORDER BY training_date DESC
LIMIT $2 OFFSET $3
`

type ListTrainingRecordsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListTrainingRecords(ctx context.Context, arg ListTrainingRecordsParams) ([]TrainingRecord, error) {
	rows, err := q.query(ctx, q.listTrainingRecordsStmt, listTrainingRecords, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingRecord{}
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.TrainingTitle,
			&i.TrainingType,
			&i.Topic,
			&i.TrainingDate,
			&i.Method,
			&i.Trainer,
			&i.Assessed,
			&i.AssessmentResult,
			&i.CompetencyValidUntil,
			&i.CertificateUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingRecordsByUser = `-- name: ListTrainingRecordsByUser :many
SELECT id, org_id, user_id, training_title, training_type, topic, training_date, method, trainer, assessed, assessment_result, competency_valid_until, certificate_url, created_by, created_at, updated_at FROM training_records
WHERE org_id = $1 AND user_id = $2
ORDER BY training_date DESC
LIMIT $3 OFFSET $4
`

type ListTrainingRecordsByUserParams struct {
	OrgID  string        `json:"org_id"`
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListTrainingRecordsByUser(ctx context.Context, arg ListTrainingRecordsByUserParams) ([]TrainingRecord, error) {
	rows, err := q.query(ctx, q.listTrainingRecordsByUserStmt, listTrainingRecordsByUser,
		arg.OrgID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingRecord{}
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.TrainingTitle,
			&i.TrainingType,
			&i.Topic,
			&i.TrainingDate,
			&i.Method,
			&i.Trainer,
			&i.Assessed,
			&i.AssessmentResult,
			&i.CompetencyValidUntil,
			&i.CertificateUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCAPAStatus = `-- name: UpdateCAPAStatus :exec
UPDATE capa_actions SET
    status = $1, updated_by = $2, updated_at = now()
WHERE id = $3 AND org_id = $4
`

type UpdateCAPAStatusParams struct {
	Status    string         `json:"status"`
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
}

func (q *Queries) UpdateCAPAStatus(ctx context.Context, arg UpdateCAPAStatusParams) error {
	_, err := q.exec(ctx, q.updateCAPAStatusStmt, updateCAPAStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateDeviationStatus = `-- name: UpdateDeviationStatus :exec
UPDATE deviations SET
    status = $1, disposition = $2, root_cause = $3,
    escalated = $4, escalated_to = $5, updated_by = $6, updated_at = now()
WHERE id = $7 AND org_id = $8
`

type UpdateDeviationStatusParams struct {
	Status      string         `json:"status"`
	Disposition sql.NullString `json:"disposition"`
	RootCause   sql.NullString `json:"root_cause"`
	Escalated   bool           `json:"escalated"`
	EscalatedTo sql.NullString `json:"escalated_to"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
}

func (q *Queries) UpdateDeviationStatus(ctx context.Context, arg UpdateDeviationStatusParams) error {
	_, err := q.exec(ctx, q.updateDeviationStatusStmt, updateDeviationStatus,
		arg.Status,
		arg.Disposition,
		arg.RootCause,
		arg.Escalated,
		arg.EscalatedTo,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const verifyCAPAEffectiveness = `-- name: VerifyCAPAEffectiveness :exec
UPDATE capa_actions SET
    effectiveness_verified = true,
    effectiveness_verified_by = $1,
    verified_at = now(),
    status = 'closed',
    closed_by = $1,
    closed_at = now(),
    updated_by = $1,
    updated_at = now()
WHERE id = $2 AND org_id = $3
`

type VerifyCAPAEffectivenessParams struct {
	EffectivenessVerifiedBy sql.NullString `json:"effectiveness_verified_by"`
	ID                      string         `json:"id"`
	OrgID                   string         `json:"org_id"`
}

func (q *Queries) VerifyCAPAEffectiveness(ctx context.Context, arg VerifyCAPAEffectivenessParams) error {
	_, err := q.exec(ctx, q.verifyCAPAEffectivenessStmt, verifyCAPAEffectiveness, arg.EffectivenessVerifiedBy, arg.ID, arg.OrgID)
	return err
}
