// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: procurement.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addPOLineItem = `-- name: AddPOLineItem :one
INSERT INTO po_line_items (po_id, product_id, line_number, quantity_ordered, quantity_received, unit_price, line_total, discount_percent, tax_percent, scheduled_date, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, po_id, product_id, line_number, quantity_ordered, quantity_received, unit_price, line_total, discount_percent, tax_percent, scheduled_date, status, notes
`

type AddPOLineItemParams struct {
	PoID             string         `json:"po_id"`
	ProductID        string         `json:"product_id"`
	LineNumber       int32          `json:"line_number"`
	QuantityOrdered  string         `json:"quantity_ordered"`
	QuantityReceived string         `json:"quantity_received"`
	UnitPrice        string         `json:"unit_price"`
	LineTotal        sql.NullString `json:"line_total"`
	DiscountPercent  string         `json:"discount_percent"`
	TaxPercent       string         `json:"tax_percent"`
	ScheduledDate    sql.NullTime   `json:"scheduled_date"`
	Status           EntityStatus   `json:"status"`
	Notes            sql.NullString `json:"notes"`
}

func (q *Queries) AddPOLineItem(ctx context.Context, arg AddPOLineItemParams) (PoLineItem, error) {
	row := q.queryRow(ctx, q.addPOLineItemStmt, addPOLineItem,
		arg.PoID,
		arg.ProductID,
		arg.LineNumber,
		arg.QuantityOrdered,
		arg.QuantityReceived,
		arg.UnitPrice,
		arg.LineTotal,
		arg.DiscountPercent,
		arg.TaxPercent,
		arg.ScheduledDate,
		arg.Status,
		arg.Notes,
	)
	var i PoLineItem
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.ProductID,
		&i.LineNumber,
		&i.QuantityOrdered,
		&i.QuantityReceived,
		&i.UnitPrice,
		&i.LineTotal,
		&i.DiscountPercent,
		&i.TaxPercent,
		&i.ScheduledDate,
		&i.Status,
		&i.Notes,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (org_id, po_number, supplier_id, warehouse_id, program_id, department_id, order_date, expected_delivery_date, delivery_address, currency, subtotal, tax_amount, total_amount, status, approval_status, notes, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, org_id, po_number, supplier_id, warehouse_id, program_id, department_id, order_date, expected_delivery_date, delivery_address, currency, subtotal, tax_amount, total_amount, status, approval_status, approved_by, approved_at, notes, created_by, updated_by, created_at, updated_at
`

type CreatePurchaseOrderParams struct {
	OrgID                string         `json:"org_id"`
	PoNumber             string         `json:"po_number"`
	SupplierID           uuid.NullUUID  `json:"supplier_id"`
	WarehouseID          uuid.NullUUID  `json:"warehouse_id"`
	ProgramID            uuid.NullUUID  `json:"program_id"`
	DepartmentID         uuid.NullUUID  `json:"department_id"`
	OrderDate            time.Time      `json:"order_date"`
	ExpectedDeliveryDate sql.NullTime   `json:"expected_delivery_date"`
	DeliveryAddress      sql.NullString `json:"delivery_address"`
	Currency             string         `json:"currency"`
	Subtotal             string         `json:"subtotal"`
	TaxAmount            string         `json:"tax_amount"`
	TotalAmount          string         `json:"total_amount"`
	Status               EntityStatus   `json:"status"`
	ApprovalStatus       string         `json:"approval_status"`
	Notes                sql.NullString `json:"notes"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.queryRow(ctx, q.createPurchaseOrderStmt, createPurchaseOrder,
		arg.OrgID,
		arg.PoNumber,
		arg.SupplierID,
		arg.WarehouseID,
		arg.ProgramID,
		arg.DepartmentID,
		arg.OrderDate,
		arg.ExpectedDeliveryDate,
		arg.DeliveryAddress,
		arg.Currency,
		arg.Subtotal,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Status,
		arg.ApprovalStatus,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PoNumber,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ProgramID,
		&i.DepartmentID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.DeliveryAddress,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (org_id, code, name, type, contact_person, email, phone, address, city, country, tax_id, payment_terms, is_active, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, org_id, code, name, type, contact_person, email, phone, address, city, country, tax_id, payment_terms, is_active, status, created_by, updated_by, created_at, updated_at
`

type CreateSupplierParams struct {
	OrgID         string         `json:"org_id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Type          sql.NullString `json:"type"`
	ContactPerson sql.NullString `json:"contact_person"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	City          sql.NullString `json:"city"`
	Country       sql.NullString `json:"country"`
	TaxID         sql.NullString `json:"tax_id"`
	PaymentTerms  sql.NullString `json:"payment_terms"`
	IsActive      bool           `json:"is_active"`
	Status        EntityStatus   `json:"status"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.queryRow(ctx, q.createSupplierStmt, createSupplier,
		arg.OrgID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.ContactPerson,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.Country,
		arg.TaxID,
		arg.PaymentTerms,
		arg.IsActive,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ContactPerson,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.TaxID,
		&i.PaymentTerms,
		&i.IsActive,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT po.id, po.org_id, po.po_number, po.supplier_id, po.warehouse_id, po.program_id, po.department_id, po.order_date, po.expected_delivery_date, po.delivery_address, po.currency, po.subtotal, po.tax_amount, po.total_amount, po.status, po.approval_status, po.approved_by, po.approved_at, po.notes, po.created_by, po.updated_by, po.created_at, po.updated_at, s.name as supplier_name
FROM purchase_orders po
LEFT JOIN suppliers s ON po.supplier_id = s.id
WHERE po.id = $1 AND po.org_id = $2
`

type GetPurchaseOrderParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetPurchaseOrderRow struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	PoNumber             string         `json:"po_number"`
	SupplierID           uuid.NullUUID  `json:"supplier_id"`
	WarehouseID          uuid.NullUUID  `json:"warehouse_id"`
	ProgramID            uuid.NullUUID  `json:"program_id"`
	DepartmentID         uuid.NullUUID  `json:"department_id"`
	OrderDate            time.Time      `json:"order_date"`
	ExpectedDeliveryDate sql.NullTime   `json:"expected_delivery_date"`
	DeliveryAddress      sql.NullString `json:"delivery_address"`
	Currency             string         `json:"currency"`
	Subtotal             string         `json:"subtotal"`
	TaxAmount            string         `json:"tax_amount"`
	TotalAmount          string         `json:"total_amount"`
	Status               EntityStatus   `json:"status"`
	ApprovalStatus       string         `json:"approval_status"`
	ApprovedBy           sql.NullString `json:"approved_by"`
	ApprovedAt           sql.NullTime   `json:"approved_at"`
	Notes                sql.NullString `json:"notes"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	SupplierName         sql.NullString `json:"supplier_name"`
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error) {
	row := q.queryRow(ctx, q.getPurchaseOrderStmt, getPurchaseOrder, arg.ID, arg.OrgID)
	var i GetPurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PoNumber,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ProgramID,
		&i.DepartmentID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.DeliveryAddress,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupplierName,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, org_id, code, name, type, contact_person, email, phone, address, city, country, tax_id, payment_terms, is_active, status, created_by, updated_by, created_at, updated_at FROM suppliers
WHERE id = $1 AND org_id = $2
`

type GetSupplierParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.queryRow(ctx, q.getSupplierStmt, getSupplier, arg.ID, arg.OrgID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ContactPerson,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.TaxID,
		&i.PaymentTerms,
		&i.IsActive,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPOLineItems = `-- name: ListPOLineItems :many
SELECT pli.id, pli.po_id, pli.product_id, pli.line_number, pli.quantity_ordered, pli.quantity_received, pli.unit_price, pli.line_total, pli.discount_percent, pli.tax_percent, pli.scheduled_date, pli.status, pli.notes, p.name as product_name, p.sku as product_sku
FROM po_line_items pli
JOIN products p ON pli.product_id = p.id
WHERE pli.po_id = $1
ORDER BY pli.line_number
`

type ListPOLineItemsRow struct {
	ID               string         `json:"id"`
	PoID             string         `json:"po_id"`
	ProductID        string         `json:"product_id"`
	LineNumber       int32          `json:"line_number"`
	QuantityOrdered  string         `json:"quantity_ordered"`
	QuantityReceived string         `json:"quantity_received"`
	UnitPrice        string         `json:"unit_price"`
	LineTotal        sql.NullString `json:"line_total"`
	DiscountPercent  string         `json:"discount_percent"`
	TaxPercent       string         `json:"tax_percent"`
	ScheduledDate    sql.NullTime   `json:"scheduled_date"`
	Status           EntityStatus   `json:"status"`
	Notes            sql.NullString `json:"notes"`
	ProductName      string         `json:"product_name"`
	ProductSku       string         `json:"product_sku"`
}

func (q *Queries) ListPOLineItems(ctx context.Context, poID string) ([]ListPOLineItemsRow, error) {
	rows, err := q.query(ctx, q.listPOLineItemsStmt, listPOLineItems, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPOLineItemsRow{}
	for rows.Next() {
		var i ListPOLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ProductID,
			&i.LineNumber,
			&i.QuantityOrdered,
			&i.QuantityReceived,
			&i.UnitPrice,
			&i.LineTotal,
			&i.DiscountPercent,
			&i.TaxPercent,
			&i.ScheduledDate,
			&i.Status,
			&i.Notes,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT po.id, po.org_id, po.po_number, po.supplier_id, po.warehouse_id, po.program_id, po.department_id, po.order_date, po.expected_delivery_date, po.delivery_address, po.currency, po.subtotal, po.tax_amount, po.total_amount, po.status, po.approval_status, po.approved_by, po.approved_at, po.notes, po.created_by, po.updated_by, po.created_at, po.updated_at, s.name as supplier_name
FROM purchase_orders po
LEFT JOIN suppliers s ON po.supplier_id = s.id
WHERE po.org_id = $1
ORDER BY po.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseOrdersParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPurchaseOrdersRow struct {
	ID                   string         `json:"id"`
	OrgID                string         `json:"org_id"`
	PoNumber             string         `json:"po_number"`
	SupplierID           uuid.NullUUID  `json:"supplier_id"`
	WarehouseID          uuid.NullUUID  `json:"warehouse_id"`
	ProgramID            uuid.NullUUID  `json:"program_id"`
	DepartmentID         uuid.NullUUID  `json:"department_id"`
	OrderDate            time.Time      `json:"order_date"`
	ExpectedDeliveryDate sql.NullTime   `json:"expected_delivery_date"`
	DeliveryAddress      sql.NullString `json:"delivery_address"`
	Currency             string         `json:"currency"`
	Subtotal             string         `json:"subtotal"`
	TaxAmount            string         `json:"tax_amount"`
	TotalAmount          string         `json:"total_amount"`
	Status               EntityStatus   `json:"status"`
	ApprovalStatus       string         `json:"approval_status"`
	ApprovedBy           sql.NullString `json:"approved_by"`
	ApprovedAt           sql.NullTime   `json:"approved_at"`
	Notes                sql.NullString `json:"notes"`
	CreatedBy            sql.NullString `json:"created_by"`
	UpdatedBy            sql.NullString `json:"updated_by"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	SupplierName         sql.NullString `json:"supplier_name"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.query(ctx, q.listPurchaseOrdersStmt, listPurchaseOrders, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PoNumber,
			&i.SupplierID,
			&i.WarehouseID,
			&i.ProgramID,
			&i.DepartmentID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.DeliveryAddress,
			&i.Currency,
			&i.Subtotal,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.Status,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, org_id, code, name, type, contact_person, email, phone, address, city, country, tax_id, payment_terms, is_active, status, created_by, updated_by, created_at, updated_at FROM suppliers
WHERE org_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListSuppliersParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.query(ctx, q.listSuppliersStmt, listSuppliers, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ContactPerson,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.Country,
			&i.TaxID,
			&i.PaymentTerms,
			&i.IsActive,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :exec
UPDATE purchase_orders SET
    status = $1::entity_status,
    approval_status = $2,
    approved_by = $3,
    approved_at = CASE WHEN $2 = 'approved' THEN now() ELSE approved_at END,
    updated_by = $4
WHERE id = $5 AND org_id = $6
`

type UpdatePurchaseOrderStatusParams struct {
	Column1        EntityStatus   `json:"column_1"`
	ApprovalStatus string         `json:"approval_status"`
	ApprovedBy     sql.NullString `json:"approved_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
}

func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error {
	_, err := q.exec(ctx, q.updatePurchaseOrderStatusStmt, updatePurchaseOrderStatus,
		arg.Column1,
		arg.ApprovalStatus,
		arg.ApprovedBy,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :exec
UPDATE suppliers SET
    code = $1, name = $2, type = $3, contact_person = $4,
    email = $5, phone = $6, address = $7, city = $8, country = $9,
    tax_id = $10, payment_terms = $11, is_active = $12,
    status = $13::entity_status, updated_by = $14
WHERE id = $15 AND org_id = $16
`

type UpdateSupplierParams struct {
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Type          sql.NullString `json:"type"`
	ContactPerson sql.NullString `json:"contact_person"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	City          sql.NullString `json:"city"`
	Country       sql.NullString `json:"country"`
	TaxID         sql.NullString `json:"tax_id"`
	PaymentTerms  sql.NullString `json:"payment_terms"`
	IsActive      bool           `json:"is_active"`
	Column13      EntityStatus   `json:"column_13"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error {
	_, err := q.exec(ctx, q.updateSupplierStmt, updateSupplier,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.ContactPerson,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.Country,
		arg.TaxID,
		arg.PaymentTerms,
		arg.IsActive,
		arg.Column13,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
