// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE org_id = $1
  AND ($2 = '' OR status = $2::entity_status)
`

type CountProductsParams struct {
	OrgID   string      `json:"org_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.queryRow(ctx, q.countProductsStmt, countProducts, arg.OrgID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    org_id, category_id, uom_id, sku, name, description, item_type,
    gtin, alternative_code, brand, manufacturer,
    is_batch_tracked, is_serial_tracked, is_expiry_tracked,
    is_hazardous, is_cold_chain,
    min_stock, max_stock, reorder_point, lead_time_days, unit_cost,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16,
    $17, $18, $19, $20, $21,
    $22, $23, $24
) RETURNING id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at
`

type CreateProductParams struct {
	OrgID           string         `json:"org_id"`
	CategoryID      uuid.NullUUID  `json:"category_id"`
	UomID           uuid.NullUUID  `json:"uom_id"`
	Sku             string         `json:"sku"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	ItemType        ItemType       `json:"item_type"`
	Gtin            sql.NullString `json:"gtin"`
	AlternativeCode sql.NullString `json:"alternative_code"`
	Brand           sql.NullString `json:"brand"`
	Manufacturer    sql.NullString `json:"manufacturer"`
	IsBatchTracked  bool           `json:"is_batch_tracked"`
	IsSerialTracked bool           `json:"is_serial_tracked"`
	IsExpiryTracked bool           `json:"is_expiry_tracked"`
	IsHazardous     bool           `json:"is_hazardous"`
	IsColdChain     bool           `json:"is_cold_chain"`
	MinStock        string         `json:"min_stock"`
	MaxStock        string         `json:"max_stock"`
	ReorderPoint    string         `json:"reorder_point"`
	LeadTimeDays    int32          `json:"lead_time_days"`
	UnitCost        string         `json:"unit_cost"`
	Status          EntityStatus   `json:"status"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.OrgID,
		arg.CategoryID,
		arg.UomID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.ItemType,
		arg.Gtin,
		arg.AlternativeCode,
		arg.Brand,
		arg.Manufacturer,
		arg.IsBatchTracked,
		arg.IsSerialTracked,
		arg.IsExpiryTracked,
		arg.IsHazardous,
		arg.IsColdChain,
		arg.MinStock,
		arg.MaxStock,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.UnitCost,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.UomID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Gtin,
		&i.AlternativeCode,
		&i.Brand,
		&i.Manufacturer,
		&i.IsBatchTracked,
		&i.IsSerialTracked,
		&i.IsExpiryTracked,
		&i.IsHazardous,
		&i.IsColdChain,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.UnitCost,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET status = 'inactive', updated_by = $1
WHERE id = $2 AND org_id = $3
`

type DeleteProductParams struct {
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, arg.UpdatedBy, arg.ID, arg.OrgID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at FROM products
WHERE id = $1 AND org_id = $2
`

type GetProductParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.queryRow(ctx, q.getProductStmt, getProduct, arg.ID, arg.OrgID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.UomID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Gtin,
		&i.AlternativeCode,
		&i.Brand,
		&i.Manufacturer,
		&i.IsBatchTracked,
		&i.IsSerialTracked,
		&i.IsExpiryTracked,
		&i.IsHazardous,
		&i.IsColdChain,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.UnitCost,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at FROM products
WHERE org_id = $1 AND sku = $2
`

type GetProductBySKUParams struct {
	OrgID string `json:"org_id"`
	Sku   string `json:"sku"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error) {
	row := q.queryRow(ctx, q.getProductBySKUStmt, getProductBySKU, arg.OrgID, arg.Sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.UomID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.Gtin,
		&i.AlternativeCode,
		&i.Brand,
		&i.Manufacturer,
		&i.IsBatchTracked,
		&i.IsSerialTracked,
		&i.IsExpiryTracked,
		&i.IsHazardous,
		&i.IsColdChain,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.UnitCost,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at FROM products
WHERE org_id = $1 AND status = 'active'
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CategoryID,
			&i.UomID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.Gtin,
			&i.AlternativeCode,
			&i.Brand,
			&i.Manufacturer,
			&i.IsBatchTracked,
			&i.IsSerialTracked,
			&i.IsExpiryTracked,
			&i.IsHazardous,
			&i.IsColdChain,
			&i.MinStock,
			&i.MaxStock,
			&i.ReorderPoint,
			&i.LeadTimeDays,
			&i.UnitCost,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at FROM products
WHERE org_id = $1 AND category_id = $2
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListProductsByCategoryParams struct {
	OrgID      string        `json:"org_id"`
	CategoryID uuid.NullUUID `json:"category_id"`
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.query(ctx, q.listProductsByCategoryStmt, listProductsByCategory,
		arg.OrgID,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CategoryID,
			&i.UomID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.Gtin,
			&i.AlternativeCode,
			&i.Brand,
			&i.Manufacturer,
			&i.IsBatchTracked,
			&i.IsSerialTracked,
			&i.IsExpiryTracked,
			&i.IsHazardous,
			&i.IsColdChain,
			&i.MinStock,
			&i.MaxStock,
			&i.ReorderPoint,
			&i.LeadTimeDays,
			&i.UnitCost,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, org_id, category_id, uom_id, sku, name, description, item_type, gtin, alternative_code, brand, manufacturer, is_batch_tracked, is_serial_tracked, is_expiry_tracked, is_hazardous, is_cold_chain, min_stock, max_stock, reorder_point, lead_time_days, unit_cost, status, created_by, updated_by, created_at, updated_at FROM products
WHERE org_id = $1
  AND (to_tsvector('simple', name || ' ' || sku || ' ' || COALESCE(description, '')) @@ plainto_tsquery('simple', $2) OR $2 = '')
ORDER BY name
LIMIT $3 OFFSET $4
`

type SearchProductsParams struct {
	OrgID          string `json:"org_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.query(ctx, q.searchProductsStmt, searchProducts,
		arg.OrgID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CategoryID,
			&i.UomID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.Gtin,
			&i.AlternativeCode,
			&i.Brand,
			&i.Manufacturer,
			&i.IsBatchTracked,
			&i.IsSerialTracked,
			&i.IsExpiryTracked,
			&i.IsHazardous,
			&i.IsColdChain,
			&i.MinStock,
			&i.MaxStock,
			&i.ReorderPoint,
			&i.LeadTimeDays,
			&i.UnitCost,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET
    name = $1, description = $2, category_id = $3, uom_id = $4,
    gtin = $5, brand = $6, manufacturer = $7,
    is_batch_tracked = $8, is_serial_tracked = $9, is_expiry_tracked = $10,
    is_hazardous = $11, is_cold_chain = $12,
    min_stock = $13, max_stock = $14, reorder_point = $15,
    lead_time_days = $16, unit_cost = $17,
    status = $18, updated_by = $19
WHERE id = $20 AND org_id = $21
`

type UpdateProductParams struct {
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	CategoryID      uuid.NullUUID  `json:"category_id"`
	UomID           uuid.NullUUID  `json:"uom_id"`
	Gtin            sql.NullString `json:"gtin"`
	Brand           sql.NullString `json:"brand"`
	Manufacturer    sql.NullString `json:"manufacturer"`
	IsBatchTracked  bool           `json:"is_batch_tracked"`
	IsSerialTracked bool           `json:"is_serial_tracked"`
	IsExpiryTracked bool           `json:"is_expiry_tracked"`
	IsHazardous     bool           `json:"is_hazardous"`
	IsColdChain     bool           `json:"is_cold_chain"`
	MinStock        string         `json:"min_stock"`
	MaxStock        string         `json:"max_stock"`
	ReorderPoint    string         `json:"reorder_point"`
	LeadTimeDays    int32          `json:"lead_time_days"`
	UnitCost        string         `json:"unit_cost"`
	Status          EntityStatus   `json:"status"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	ID              string         `json:"id"`
	OrgID           string         `json:"org_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.exec(ctx, q.updateProductStmt, updateProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.UomID,
		arg.Gtin,
		arg.Brand,
		arg.Manufacturer,
		arg.IsBatchTracked,
		arg.IsSerialTracked,
		arg.IsExpiryTracked,
		arg.IsHazardous,
		arg.IsColdChain,
		arg.MinStock,
		arg.MaxStock,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.UnitCost,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateProductStockParams = `-- name: UpdateProductStockParams :exec
UPDATE products SET
    min_stock = $1, max_stock = $2, reorder_point = $3,
    lead_time_days = $4, unit_cost = $5, updated_by = $6
WHERE id = $7 AND org_id = $8
`

type UpdateProductStockParamsParams struct {
	MinStock     string         `json:"min_stock"`
	MaxStock     string         `json:"max_stock"`
	ReorderPoint string         `json:"reorder_point"`
	LeadTimeDays int32          `json:"lead_time_days"`
	UnitCost     string         `json:"unit_cost"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
}

func (q *Queries) UpdateProductStockParams(ctx context.Context, arg UpdateProductStockParamsParams) error {
	_, err := q.exec(ctx, q.updateProductStockParamsStmt, updateProductStockParams,
		arg.MinStock,
		arg.MaxStock,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.UnitCost,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
