// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: qa.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createQAChecklistItem = `-- name: CreateQAChecklistItem :one
INSERT INTO qa_checklist_items (template_id, item_order, question, expected_answer, is_critical, weight)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, template_id, item_order, question, expected_answer, is_critical, weight
`

type CreateQAChecklistItemParams struct {
	TemplateID     string `json:"template_id"`
	ItemOrder      int32  `json:"item_order"`
	Question       string `json:"question"`
	ExpectedAnswer string `json:"expected_answer"`
	IsCritical     bool   `json:"is_critical"`
	Weight         string `json:"weight"`
}

func (q *Queries) CreateQAChecklistItem(ctx context.Context, arg CreateQAChecklistItemParams) (QaChecklistItem, error) {
	row := q.queryRow(ctx, q.createQAChecklistItemStmt, createQAChecklistItem,
		arg.TemplateID,
		arg.ItemOrder,
		arg.Question,
		arg.ExpectedAnswer,
		arg.IsCritical,
		arg.Weight,
	)
	var i QaChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ItemOrder,
		&i.Question,
		&i.ExpectedAnswer,
		&i.IsCritical,
		&i.Weight,
	)
	return i, err
}

const createQAChecklistTemplate = `-- name: CreateQAChecklistTemplate :one
INSERT INTO qa_checklist_templates (org_id, code, name, description, category, is_mandatory, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, code, name, description, category, is_mandatory, status, created_by, updated_by, created_at, updated_at
`

type CreateQAChecklistTemplateParams struct {
	OrgID       string         `json:"org_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	IsMandatory bool           `json:"is_mandatory"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateQAChecklistTemplate(ctx context.Context, arg CreateQAChecklistTemplateParams) (QaChecklistTemplate, error) {
	row := q.queryRow(ctx, q.createQAChecklistTemplateStmt, createQAChecklistTemplate,
		arg.OrgID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.IsMandatory,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i QaChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsMandatory,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQAInspection = `-- name: CreateQAInspection :one
INSERT INTO qa_inspections (org_id, grn_id, product_id, batch_id, inspection_date, inspector, result, notes, disposition, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, grn_id, product_id, batch_id, inspection_date, inspector, result, notes, disposition, created_by, updated_by, created_at, updated_at
`

type CreateQAInspectionParams struct {
	OrgID          string         `json:"org_id"`
	GrnID          uuid.NullUUID  `json:"grn_id"`
	ProductID      string         `json:"product_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	InspectionDate time.Time      `json:"inspection_date"`
	Inspector      sql.NullString `json:"inspector"`
	Result         string         `json:"result"`
	Notes          sql.NullString `json:"notes"`
	Disposition    sql.NullString `json:"disposition"`
	CreatedBy      sql.NullString `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateQAInspection(ctx context.Context, arg CreateQAInspectionParams) (QaInspection, error) {
	row := q.queryRow(ctx, q.createQAInspectionStmt, createQAInspection,
		arg.OrgID,
		arg.GrnID,
		arg.ProductID,
		arg.BatchID,
		arg.InspectionDate,
		arg.Inspector,
		arg.Result,
		arg.Notes,
		arg.Disposition,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i QaInspection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GrnID,
		&i.ProductID,
		&i.BatchID,
		&i.InspectionDate,
		&i.Inspector,
		&i.Result,
		&i.Notes,
		&i.Disposition,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQAChecklistTemplate = `-- name: GetQAChecklistTemplate :one
SELECT id, org_id, code, name, description, category, is_mandatory, status, created_by, updated_by, created_at, updated_at FROM qa_checklist_templates
WHERE id = $1 AND org_id = $2
`

type GetQAChecklistTemplateParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetQAChecklistTemplate(ctx context.Context, arg GetQAChecklistTemplateParams) (QaChecklistTemplate, error) {
	row := q.queryRow(ctx, q.getQAChecklistTemplateStmt, getQAChecklistTemplate, arg.ID, arg.OrgID)
	var i QaChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsMandatory,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQAInspection = `-- name: GetQAInspection :one
SELECT q.id, q.org_id, q.grn_id, q.product_id, q.batch_id, q.inspection_date, q.inspector, q.result, q.notes, q.disposition, q.created_by, q.updated_by, q.created_at, q.updated_at, p.name as product_name, p.sku as product_sku
FROM qa_inspections q
JOIN products p ON q.product_id = p.id
WHERE q.id = $1 AND q.org_id = $2
`

type GetQAInspectionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetQAInspectionRow struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	GrnID          uuid.NullUUID  `json:"grn_id"`
	ProductID      string         `json:"product_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	InspectionDate time.Time      `json:"inspection_date"`
	Inspector      sql.NullString `json:"inspector"`
	Result         string         `json:"result"`
	Notes          sql.NullString `json:"notes"`
	Disposition    sql.NullString `json:"disposition"`
	CreatedBy      sql.NullString `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ProductName    string         `json:"product_name"`
	ProductSku     string         `json:"product_sku"`
}

func (q *Queries) GetQAInspection(ctx context.Context, arg GetQAInspectionParams) (GetQAInspectionRow, error) {
	row := q.queryRow(ctx, q.getQAInspectionStmt, getQAInspection, arg.ID, arg.OrgID)
	var i GetQAInspectionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GrnID,
		&i.ProductID,
		&i.BatchID,
		&i.InspectionDate,
		&i.Inspector,
		&i.Result,
		&i.Notes,
		&i.Disposition,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
		&i.ProductSku,
	)
	return i, err
}

const listQAChecklistItems = `-- name: ListQAChecklistItems :many
SELECT id, template_id, item_order, question, expected_answer, is_critical, weight FROM qa_checklist_items
WHERE template_id = $1
ORDER BY item_order
`

func (q *Queries) ListQAChecklistItems(ctx context.Context, templateID string) ([]QaChecklistItem, error) {
	rows, err := q.query(ctx, q.listQAChecklistItemsStmt, listQAChecklistItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QaChecklistItem{}
	for rows.Next() {
		var i QaChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ItemOrder,
			&i.Question,
			&i.ExpectedAnswer,
			&i.IsCritical,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQAChecklistTemplates = `-- name: ListQAChecklistTemplates :many
SELECT id, org_id, code, name, description, category, is_mandatory, status, created_by, updated_by, created_at, updated_at FROM qa_checklist_templates
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListQAChecklistTemplates(ctx context.Context, orgID string) ([]QaChecklistTemplate, error) {
	rows, err := q.query(ctx, q.listQAChecklistTemplatesStmt, listQAChecklistTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QaChecklistTemplate{}
	for rows.Next() {
		var i QaChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.IsMandatory,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQAInspections = `-- name: ListQAInspections :many
SELECT q.id, q.org_id, q.grn_id, q.product_id, q.batch_id, q.inspection_date, q.inspector, q.result, q.notes, q.disposition, q.created_by, q.updated_by, q.created_at, q.updated_at, p.name as product_name, p.sku as product_sku
FROM qa_inspections q
JOIN products p ON q.product_id = p.id
WHERE q.org_id = $1
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type ListQAInspectionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListQAInspectionsRow struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	GrnID          uuid.NullUUID  `json:"grn_id"`
	ProductID      string         `json:"product_id"`
	BatchID        uuid.NullUUID  `json:"batch_id"`
	InspectionDate time.Time      `json:"inspection_date"`
	Inspector      sql.NullString `json:"inspector"`
	Result         string         `json:"result"`
	Notes          sql.NullString `json:"notes"`
	Disposition    sql.NullString `json:"disposition"`
	CreatedBy      sql.NullString `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ProductName    string         `json:"product_name"`
	ProductSku     string         `json:"product_sku"`
}

func (q *Queries) ListQAInspections(ctx context.Context, arg ListQAInspectionsParams) ([]ListQAInspectionsRow, error) {
	rows, err := q.query(ctx, q.listQAInspectionsStmt, listQAInspections, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQAInspectionsRow{}
	for rows.Next() {
		var i ListQAInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GrnID,
			&i.ProductID,
			&i.BatchID,
			&i.InspectionDate,
			&i.Inspector,
			&i.Result,
			&i.Notes,
			&i.Disposition,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQAInspectionResult = `-- name: UpdateQAInspectionResult :exec
UPDATE qa_inspections SET
    result = $1, notes = $2, disposition = $3, inspector = $4, updated_by = $5
WHERE id = $6 AND org_id = $7
`

type UpdateQAInspectionResultParams struct {
	Result      string         `json:"result"`
	Notes       sql.NullString `json:"notes"`
	Disposition sql.NullString `json:"disposition"`
	Inspector   sql.NullString `json:"inspector"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
}

func (q *Queries) UpdateQAInspectionResult(ctx context.Context, arg UpdateQAInspectionResultParams) error {
	_, err := q.exec(ctx, q.updateQAInspectionResultStmt, updateQAInspectionResult,
		arg.Result,
		arg.Notes,
		arg.Disposition,
		arg.Inspector,
		arg.UpdatedBy,
		arg.ID,
		arg.OrgID,
	)
	return err
}
