// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) error
	AddCustodyChange(ctx context.Context, arg AddCustodyChangeParams) (AssetCustodyChange, error)
	AddDistributionLineItem(ctx context.Context, arg AddDistributionLineItemParams) (DistributionLineItem, error)
	AddMaintenanceRecord(ctx context.Context, arg AddMaintenanceRecordParams) (AssetMaintenance, error)
	AddPOLineItem(ctx context.Context, arg AddPOLineItemParams) (PoLineItem, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CreateAMCCalculation(ctx context.Context, arg CreateAMCCalculationParams) (AmcCalculation, error)
	CreateAdjustment(ctx context.Context, arg CreateAdjustmentParams) (StockAdjustment, error)
	CreateAdjustmentLineItem(ctx context.Context, arg CreateAdjustmentLineItemParams) error
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAlertConfiguration(ctx context.Context, arg CreateAlertConfigurationParams) (AlertConfiguration, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (ProductCategory, error)
	CreateDataChangeLog(ctx context.Context, arg CreateDataChangeLogParams) error
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateDistribution(ctx context.Context, arg CreateDistributionParams) (Distribution, error)
	CreateForecastResult(ctx context.Context, arg CreateForecastResultParams) (ForecastResult, error)
	CreateGRN(ctx context.Context, arg CreateGRNParams) (GoodsReceipt, error)
	CreateGRNLineItem(ctx context.Context, arg CreateGRNLineItemParams) error
	CreateIssueLineItem(ctx context.Context, arg CreateIssueLineItemParams) error
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOrgLevel(ctx context.Context, arg CreateOrgLevelParams) (OrgLevel, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateQAChecklistItem(ctx context.Context, arg CreateQAChecklistItemParams) (QaChecklistItem, error)
	CreateQAChecklistTemplate(ctx context.Context, arg CreateQAChecklistTemplateParams) (QaChecklistTemplate, error)
	CreateQAInspection(ctx context.Context, arg CreateQAInspectionParams) (QaInspection, error)
	CreateReorderRecommendation(ctx context.Context, arg CreateReorderRecommendationParams) (ReorderRecommendation, error)
	CreateReportDefinition(ctx context.Context, arg CreateReportDefinitionParams) (ReportDefinition, error)
	CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateStockIssue(ctx context.Context, arg CreateStockIssueParams) (StockIssue, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) error
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateSyncConflict(ctx context.Context, arg CreateSyncConflictParams) (SyncConflict, error)
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (StockTransfer, error)
	CreateTransferLineItem(ctx context.Context, arg CreateTransferLineItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	GetActiveAlerts(ctx context.Context, orgID string) ([]GetActiveAlertsRow, error)
	GetAdjustment(ctx context.Context, arg GetAdjustmentParams) (GetAdjustmentRow, error)
	GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error)
	GetBatchesByProduct(ctx context.Context, arg GetBatchesByProductParams) ([]Batch, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (ProductCategory, error)
	GetDistribution(ctx context.Context, arg GetDistributionParams) (GetDistributionRow, error)
	GetExpiringBatches(ctx context.Context, arg GetExpiringBatchesParams) ([]Batch, error)
	GetGRN(ctx context.Context, arg GetGRNParams) (GetGRNRow, error)
	GetLatestAMC(ctx context.Context, arg GetLatestAMCParams) (AmcCalculation, error)
	GetOrgTree(ctx context.Context, orgID string) ([]GetOrgTreeRow, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetPendingConflicts(ctx context.Context, orgID string) ([]SyncConflict, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error)
	GetQAChecklistTemplate(ctx context.Context, arg GetQAChecklistTemplateParams) (QaChecklistTemplate, error)
	GetQAInspection(ctx context.Context, arg GetQAInspectionParams) (GetQAInspectionRow, error)
	GetReportDefinition(ctx context.Context, arg GetReportDefinitionParams) (ReportDefinition, error)
	GetStockIssue(ctx context.Context, arg GetStockIssueParams) (GetStockIssueRow, error)
	GetStockLevel(ctx context.Context, arg GetStockLevelParams) (StockLevel, error)
	GetStockLevels(ctx context.Context, orgID string) ([]StockLevel, error)
	GetStockMovements(ctx context.Context, arg GetStockMovementsParams) ([]StockMovement, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	GetTransfer(ctx context.Context, arg GetTransferParams) (GetTransferRow, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserPermissions(ctx context.Context, userID string) ([]Permission, error)
	GetWarehouse(ctx context.Context, arg GetWarehouseParams) (Warehouse, error)
	GetWarehouseWithLocations(ctx context.Context, arg GetWarehouseWithLocationsParams) ([]GetWarehouseWithLocationsRow, error)
	ListAMCCalculations(ctx context.Context, arg ListAMCCalculationsParams) ([]AmcCalculation, error)
	ListAdjustmentReasonCodes(ctx context.Context) ([]AdjustmentReasonCode, error)
	ListAdjustments(ctx context.Context, arg ListAdjustmentsParams) ([]ListAdjustmentsRow, error)
	ListAlertConfigurations(ctx context.Context, orgID string) ([]AlertConfiguration, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error)
	ListAssetCustodyChanges(ctx context.Context, assetID string) ([]ListAssetCustodyChangesRow, error)
	ListAssetDepreciation(ctx context.Context, assetID string) ([]AssetDepreciationSchedule, error)
	ListAssetMaintenance(ctx context.Context, assetID string) ([]AssetMaintenance, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListCategories(ctx context.Context, orgID string) ([]ProductCategory, error)
	ListCategoryTree(ctx context.Context, orgID string) ([]ListCategoryTreeRow, error)
	ListDepartments(ctx context.Context, orgID string) ([]Department, error)
	ListDistributionLineItems(ctx context.Context, distributionID string) ([]ListDistributionLineItemsRow, error)
	ListDistributions(ctx context.Context, arg ListDistributionsParams) ([]ListDistributionsRow, error)
	ListForecastResults(ctx context.Context, arg ListForecastResultsParams) ([]ForecastResult, error)
	ListGRNLineItems(ctx context.Context, grnID string) ([]ListGRNLineItemsRow, error)
	ListGRNs(ctx context.Context, arg ListGRNsParams) ([]ListGRNsRow, error)
	ListIssueLineItems(ctx context.Context, issueID string) ([]ListIssueLineItemsRow, error)
	ListLocations(ctx context.Context, warehouseID string) ([]Location, error)
	ListOrgLevels(ctx context.Context, orgID string) ([]OrgLevel, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPOLineItems(ctx context.Context, poID string) ([]ListPOLineItemsRow, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListPrograms(ctx context.Context, orgID string) ([]Program, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error)
	ListQAChecklistItems(ctx context.Context, templateID string) ([]QaChecklistItem, error)
	ListQAChecklistTemplates(ctx context.Context, orgID string) ([]QaChecklistTemplate, error)
	ListQAInspections(ctx context.Context, arg ListQAInspectionsParams) ([]ListQAInspectionsRow, error)
	ListReorderRecommendations(ctx context.Context, arg ListReorderRecommendationsParams) ([]ListReorderRecommendationsRow, error)
	ListReportDefinitions(ctx context.Context, arg ListReportDefinitionsParams) ([]ReportDefinition, error)
	ListReportSchedules(ctx context.Context, orgID string) ([]ListReportSchedulesRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListStockIssues(ctx context.Context, arg ListStockIssuesParams) ([]ListStockIssuesRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListTransferLineItems(ctx context.Context, transferID string) ([]ListTransferLineItemsRow, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWarehouses(ctx context.Context, orgID string) ([]Warehouse, error)
	ListWarehousesByType(ctx context.Context, arg ListWarehousesByTypeParams) ([]Warehouse, error)
	MarkRecommendationReviewed(ctx context.Context, arg MarkRecommendationReviewedParams) error
	ResolveAlert(ctx context.Context, arg ResolveAlertParams) error
	ResolveSyncConflict(ctx context.Context, arg ResolveSyncConflictParams) error
	SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]SearchAuditLogsRow, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchStockMovements(ctx context.Context, arg SearchStockMovementsParams) ([]StockMovement, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateDistributionStatus(ctx context.Context, arg UpdateDistributionStatusParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductStockParams(ctx context.Context, arg UpdateProductStockParamsParams) error
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error
	UpdateQAInspectionResult(ctx context.Context, arg UpdateQAInspectionResultParams) error
	UpdateScheduleLastRun(ctx context.Context, arg UpdateScheduleLastRunParams) error
	UpdateStockLevel(ctx context.Context, arg UpdateStockLevelParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error
	UpdateSyncLog(ctx context.Context, arg UpdateSyncLogParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
