// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createReportDefinition = `-- name: CreateReportDefinition :one
INSERT INTO report_definitions (org_id, code, name, description, category, sql_query, parameters, output_formats, is_system, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, org_id, code, name, description, category, sql_query, parameters, output_formats, is_system, status, created_by, updated_by, created_at, updated_at
`

type CreateReportDefinitionParams struct {
	OrgID         string                `json:"org_id"`
	Code          string                `json:"code"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Category      string                `json:"category"`
	SqlQuery      sql.NullString        `json:"sql_query"`
	Parameters    pqtype.NullRawMessage `json:"parameters"`
	OutputFormats string                `json:"output_formats"`
	IsSystem      bool                  `json:"is_system"`
	Status        EntityStatus          `json:"status"`
	CreatedBy     sql.NullString        `json:"created_by"`
	UpdatedBy     sql.NullString        `json:"updated_by"`
}

func (q *Queries) CreateReportDefinition(ctx context.Context, arg CreateReportDefinitionParams) (ReportDefinition, error) {
	row := q.queryRow(ctx, q.createReportDefinitionStmt, createReportDefinition,
		arg.OrgID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.SqlQuery,
		arg.Parameters,
		arg.OutputFormats,
		arg.IsSystem,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ReportDefinition
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.SqlQuery,
		&i.Parameters,
		&i.OutputFormats,
		&i.IsSystem,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReportSchedule = `-- name: CreateReportSchedule :one
INSERT INTO report_schedules (report_id, schedule_cron, parameters, recipients, format, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, report_id, schedule_cron, parameters, recipients, format, is_active, last_run_at, next_run_at, created_by, updated_by, created_at, updated_at
`

type CreateReportScheduleParams struct {
	ReportID     string                `json:"report_id"`
	ScheduleCron string                `json:"schedule_cron"`
	Parameters   pqtype.NullRawMessage `json:"parameters"`
	Recipients   sql.NullString        `json:"recipients"`
	Format       string                `json:"format"`
	IsActive     bool                  `json:"is_active"`
	CreatedBy    sql.NullString        `json:"created_by"`
	UpdatedBy    sql.NullString        `json:"updated_by"`
}

func (q *Queries) CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error) {
	row := q.queryRow(ctx, q.createReportScheduleStmt, createReportSchedule,
		arg.ReportID,
		arg.ScheduleCron,
		arg.Parameters,
		arg.Recipients,
		arg.Format,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ScheduleCron,
		&i.Parameters,
		&i.Recipients,
		&i.Format,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportDefinition = `-- name: GetReportDefinition :one
SELECT id, org_id, code, name, description, category, sql_query, parameters, output_formats, is_system, status, created_by, updated_by, created_at, updated_at FROM report_definitions
WHERE id = $1 AND org_id = $2
`

type GetReportDefinitionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetReportDefinition(ctx context.Context, arg GetReportDefinitionParams) (ReportDefinition, error) {
	row := q.queryRow(ctx, q.getReportDefinitionStmt, getReportDefinition, arg.ID, arg.OrgID)
	var i ReportDefinition
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.SqlQuery,
		&i.Parameters,
		&i.OutputFormats,
		&i.IsSystem,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportDefinitions = `-- name: ListReportDefinitions :many
SELECT id, org_id, code, name, description, category, sql_query, parameters, output_formats, is_system, status, created_by, updated_by, created_at, updated_at FROM report_definitions
WHERE org_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListReportDefinitionsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListReportDefinitions(ctx context.Context, arg ListReportDefinitionsParams) ([]ReportDefinition, error) {
	rows, err := q.query(ctx, q.listReportDefinitionsStmt, listReportDefinitions, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDefinition{}
	for rows.Next() {
		var i ReportDefinition
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.SqlQuery,
			&i.Parameters,
			&i.OutputFormats,
			&i.IsSystem,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportSchedules = `-- name: ListReportSchedules :many
SELECT rs.id, rs.report_id, rs.schedule_cron, rs.parameters, rs.recipients, rs.format, rs.is_active, rs.last_run_at, rs.next_run_at, rs.created_by, rs.updated_by, rs.created_at, rs.updated_at, rd.name as report_name
FROM report_schedules rs
JOIN report_definitions rd ON rs.report_id = rd.id
WHERE rd.org_id = $1
ORDER BY rs.next_run_at
`

type ListReportSchedulesRow struct {
	ID           string                `json:"id"`
	ReportID     string                `json:"report_id"`
	ScheduleCron string                `json:"schedule_cron"`
	Parameters   pqtype.NullRawMessage `json:"parameters"`
	Recipients   sql.NullString        `json:"recipients"`
	Format       string                `json:"format"`
	IsActive     bool                  `json:"is_active"`
	LastRunAt    sql.NullTime          `json:"last_run_at"`
	NextRunAt    sql.NullTime          `json:"next_run_at"`
	CreatedBy    sql.NullString        `json:"created_by"`
	UpdatedBy    sql.NullString        `json:"updated_by"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	ReportName   string                `json:"report_name"`
}

func (q *Queries) ListReportSchedules(ctx context.Context, orgID string) ([]ListReportSchedulesRow, error) {
	rows, err := q.query(ctx, q.listReportSchedulesStmt, listReportSchedules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportSchedulesRow{}
	for rows.Next() {
		var i ListReportSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ScheduleCron,
			&i.Parameters,
			&i.Recipients,
			&i.Format,
			&i.IsActive,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleLastRun = `-- name: UpdateScheduleLastRun :exec
UPDATE report_schedules SET
    last_run_at = now(),
    next_run_at = $1,
    updated_by = $2
WHERE id = $3
`

type UpdateScheduleLastRunParams struct {
	NextRunAt sql.NullTime   `json:"next_run_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateScheduleLastRun(ctx context.Context, arg UpdateScheduleLastRunParams) error {
	_, err := q.exec(ctx, q.updateScheduleLastRunStmt, updateScheduleLastRun, arg.NextRunAt, arg.UpdatedBy, arg.ID)
	return err
}
