// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stock.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (org_id, product_id, batch_number, serial_number, expiry_date, manufacturer)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, product_id, batch_number, serial_number, expiry_date, manufacturer, created_at
`

type CreateBatchParams struct {
	OrgID        string         `json:"org_id"`
	ProductID    string         `json:"product_id"`
	BatchNumber  string         `json:"batch_number"`
	SerialNumber sql.NullString `json:"serial_number"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	Manufacturer sql.NullString `json:"manufacturer"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.queryRow(ctx, q.createBatchStmt, createBatch,
		arg.OrgID,
		arg.ProductID,
		arg.BatchNumber,
		arg.SerialNumber,
		arg.ExpiryDate,
		arg.Manufacturer,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProductID,
		&i.BatchNumber,
		&i.SerialNumber,
		&i.ExpiryDate,
		&i.Manufacturer,
		&i.CreatedAt,
	)
	return i, err
}

const createGRN = `-- name: CreateGRN :one
INSERT INTO goods_receipts (org_id, warehouse_id, grn_number, supplier, po_number, received_by, status, notes, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, warehouse_id, grn_number, supplier, po_number, received_by, status, notes, created_by, updated_by, created_at, updated_at
`

type CreateGRNParams struct {
	OrgID       string         `json:"org_id"`
	WarehouseID string         `json:"warehouse_id"`
	GrnNumber   string         `json:"grn_number"`
	Supplier    sql.NullString `json:"supplier"`
	PoNumber    sql.NullString `json:"po_number"`
	ReceivedBy  sql.NullString `json:"received_by"`
	Status      EntityStatus   `json:"status"`
	Notes       sql.NullString `json:"notes"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateGRN(ctx context.Context, arg CreateGRNParams) (GoodsReceipt, error) {
	row := q.queryRow(ctx, q.createGRNStmt, createGRN,
		arg.OrgID,
		arg.WarehouseID,
		arg.GrnNumber,
		arg.Supplier,
		arg.PoNumber,
		arg.ReceivedBy,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.GrnNumber,
		&i.Supplier,
		&i.PoNumber,
		&i.ReceivedBy,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGRNLineItem = `-- name: CreateGRNLineItem :exec
INSERT INTO grn_line_items (grn_id, product_id, batch_number, serial_number, expiry_date, quantity, unit_cost, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateGRNLineItemParams struct {
	GrnID        string         `json:"grn_id"`
	ProductID    string         `json:"product_id"`
	BatchNumber  sql.NullString `json:"batch_number"`
	SerialNumber sql.NullString `json:"serial_number"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	Quantity     string         `json:"quantity"`
	UnitCost     sql.NullString `json:"unit_cost"`
	Status       EntityStatus   `json:"status"`
}

func (q *Queries) CreateGRNLineItem(ctx context.Context, arg CreateGRNLineItemParams) error {
	_, err := q.exec(ctx, q.createGRNLineItemStmt, createGRNLineItem,
		arg.GrnID,
		arg.ProductID,
		arg.BatchNumber,
		arg.SerialNumber,
		arg.ExpiryDate,
		arg.Quantity,
		arg.UnitCost,
		arg.Status,
	)
	return err
}

const createStockMovement = `-- name: CreateStockMovement :exec
INSERT INTO stock_movements (org_id, product_id, warehouse_id, location_id, batch_id, movement_type, quantity, ref_doc_type, ref_doc_id, reason_code, reference, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateStockMovementParams struct {
	OrgID        string         `json:"org_id"`
	ProductID    string         `json:"product_id"`
	WarehouseID  string         `json:"warehouse_id"`
	LocationID   uuid.NullUUID  `json:"location_id"`
	BatchID      uuid.NullUUID  `json:"batch_id"`
	MovementType MovementType   `json:"movement_type"`
	Quantity     string         `json:"quantity"`
	RefDocType   NullDocType    `json:"ref_doc_type"`
	RefDocID     sql.NullString `json:"ref_doc_id"`
	ReasonCode   sql.NullString `json:"reason_code"`
	Reference    sql.NullString `json:"reference"`
	CreatedBy    string         `json:"created_by"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) error {
	_, err := q.exec(ctx, q.createStockMovementStmt, createStockMovement,
		arg.OrgID,
		arg.ProductID,
		arg.WarehouseID,
		arg.LocationID,
		arg.BatchID,
		arg.MovementType,
		arg.Quantity,
		arg.RefDocType,
		arg.RefDocID,
		arg.ReasonCode,
		arg.Reference,
		arg.CreatedBy,
	)
	return err
}

const getBatchesByProduct = `-- name: GetBatchesByProduct :many
SELECT id, org_id, product_id, batch_number, serial_number, expiry_date, manufacturer, created_at FROM batches
WHERE product_id = $1 AND org_id = $2
ORDER BY created_at DESC
`

type GetBatchesByProductParams struct {
	ProductID string `json:"product_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) GetBatchesByProduct(ctx context.Context, arg GetBatchesByProductParams) ([]Batch, error) {
	rows, err := q.query(ctx, q.getBatchesByProductStmt, getBatchesByProduct, arg.ProductID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.ExpiryDate,
			&i.Manufacturer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiringBatches = `-- name: GetExpiringBatches :many
SELECT id, org_id, product_id, batch_number, serial_number, expiry_date, manufacturer, created_at FROM batches
WHERE expiry_date BETWEEN $1 AND $2 AND org_id = $3
ORDER BY expiry_date
`

type GetExpiringBatchesParams struct {
	ExpiryDate   sql.NullTime `json:"expiry_date"`
	ExpiryDate_2 sql.NullTime `json:"expiry_date_2"`
	OrgID        string       `json:"org_id"`
}

func (q *Queries) GetExpiringBatches(ctx context.Context, arg GetExpiringBatchesParams) ([]Batch, error) {
	rows, err := q.query(ctx, q.getExpiringBatchesStmt, getExpiringBatches, arg.ExpiryDate, arg.ExpiryDate_2, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.ExpiryDate,
			&i.Manufacturer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockLevel = `-- name: GetStockLevel :one
SELECT id, org_id, product_id, warehouse_id, location_id, batch_id, quantity, reserved_qty, status, updated_at FROM stock_levels
WHERE product_id = $1 AND warehouse_id = $2 AND location_id = $3 AND batch_id = $4
`

type GetStockLevelParams struct {
	ProductID   string        `json:"product_id"`
	WarehouseID string        `json:"warehouse_id"`
	LocationID  uuid.NullUUID `json:"location_id"`
	BatchID     uuid.NullUUID `json:"batch_id"`
}

func (q *Queries) GetStockLevel(ctx context.Context, arg GetStockLevelParams) (StockLevel, error) {
	row := q.queryRow(ctx, q.getStockLevelStmt, getStockLevel,
		arg.ProductID,
		arg.WarehouseID,
		arg.LocationID,
		arg.BatchID,
	)
	var i StockLevel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProductID,
		&i.WarehouseID,
		&i.LocationID,
		&i.BatchID,
		&i.Quantity,
		&i.ReservedQty,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockLevels = `-- name: GetStockLevels :many
SELECT id, org_id, product_id, warehouse_id, location_id, batch_id, quantity, reserved_qty, status, updated_at FROM stock_levels
WHERE org_id = $1
ORDER BY product_id
`

func (q *Queries) GetStockLevels(ctx context.Context, orgID string) ([]StockLevel, error) {
	rows, err := q.query(ctx, q.getStockLevelsStmt, getStockLevels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockLevel{}
	for rows.Next() {
		var i StockLevel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.WarehouseID,
			&i.LocationID,
			&i.BatchID,
			&i.Quantity,
			&i.ReservedQty,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockMovements = `-- name: GetStockMovements :many
SELECT id, org_id, product_id, warehouse_id, location_id, batch_id, movement_type, quantity, ref_doc_type, ref_doc_id, reason_code, reference, created_by, created_at FROM stock_movements
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetStockMovementsParams struct {
	OrgID string `json:"org_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) GetStockMovements(ctx context.Context, arg GetStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.query(ctx, q.getStockMovementsStmt, getStockMovements, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.WarehouseID,
			&i.LocationID,
			&i.BatchID,
			&i.MovementType,
			&i.Quantity,
			&i.RefDocType,
			&i.RefDocID,
			&i.ReasonCode,
			&i.Reference,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStockMovements = `-- name: SearchStockMovements :many
SELECT id, org_id, product_id, warehouse_id, location_id, batch_id, movement_type, quantity, ref_doc_type, ref_doc_id, reason_code, reference, created_by, created_at FROM stock_movements
WHERE org_id = $1
  AND ($2 = '' OR movement_type = $2::movement_type)
  AND ($3::date IS NULL OR created_at >= $3::date)
  AND ($4::date IS NULL OR created_at <= $4::date + interval '1 day')
  AND ($5 = '' OR product_id = $5::uuid)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type SearchStockMovementsParams struct {
	OrgID   string      `json:"org_id"`
	Column2 interface{} `json:"column_2"`
	Column3 time.Time   `json:"column_3"`
	Column4 time.Time   `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchStockMovements(ctx context.Context, arg SearchStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.query(ctx, q.searchStockMovementsStmt, searchStockMovements,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.WarehouseID,
			&i.LocationID,
			&i.BatchID,
			&i.MovementType,
			&i.Quantity,
			&i.RefDocType,
			&i.RefDocID,
			&i.ReasonCode,
			&i.Reference,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockLevel = `-- name: UpdateStockLevel :exec
UPDATE stock_levels SET
    quantity = $1, reserved_qty = $2
WHERE product_id = $3 AND warehouse_id = $4 AND location_id = $5 AND batch_id = $6
`

type UpdateStockLevelParams struct {
	Quantity    string        `json:"quantity"`
	ReservedQty string        `json:"reserved_qty"`
	ProductID   string        `json:"product_id"`
	WarehouseID string        `json:"warehouse_id"`
	LocationID  uuid.NullUUID `json:"location_id"`
	BatchID     uuid.NullUUID `json:"batch_id"`
}

func (q *Queries) UpdateStockLevel(ctx context.Context, arg UpdateStockLevelParams) error {
	_, err := q.exec(ctx, q.updateStockLevelStmt, updateStockLevel,
		arg.Quantity,
		arg.ReservedQty,
		arg.ProductID,
		arg.WarehouseID,
		arg.LocationID,
		arg.BatchID,
	)
	return err
}
