// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSyncConflict = `-- name: CreateSyncConflict :one
INSERT INTO sync_conflicts (org_id, table_name, record_id, device_id, server_version, client_version, conflict_type, resolution)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, table_name, record_id, device_id, server_version, client_version, conflict_type, resolution, resolved_by, resolved_at, created_at
`

type CreateSyncConflictParams struct {
	OrgID         string                `json:"org_id"`
	TableName     string                `json:"table_name"`
	RecordID      string                `json:"record_id"`
	DeviceID      string                `json:"device_id"`
	ServerVersion pqtype.NullRawMessage `json:"server_version"`
	ClientVersion pqtype.NullRawMessage `json:"client_version"`
	ConflictType  sql.NullString        `json:"conflict_type"`
	Resolution    string                `json:"resolution"`
}

func (q *Queries) CreateSyncConflict(ctx context.Context, arg CreateSyncConflictParams) (SyncConflict, error) {
	row := q.queryRow(ctx, q.createSyncConflictStmt, createSyncConflict,
		arg.OrgID,
		arg.TableName,
		arg.RecordID,
		arg.DeviceID,
		arg.ServerVersion,
		arg.ClientVersion,
		arg.ConflictType,
		arg.Resolution,
	)
	var i SyncConflict
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TableName,
		&i.RecordID,
		&i.DeviceID,
		&i.ServerVersion,
		&i.ClientVersion,
		&i.ConflictType,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_log (org_id, device_id, user_id, sync_type, started_at, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, device_id, user_id, sync_type, started_at, completed_at, status, records_pushed, records_pulled, errors_count, error_message
`

type CreateSyncLogParams struct {
	OrgID     string         `json:"org_id"`
	DeviceID  string         `json:"device_id"`
	UserID    uuid.NullUUID  `json:"user_id"`
	SyncType  sql.NullString `json:"sync_type"`
	StartedAt time.Time      `json:"started_at"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.queryRow(ctx, q.createSyncLogStmt, createSyncLog,
		arg.OrgID,
		arg.DeviceID,
		arg.UserID,
		arg.SyncType,
		arg.StartedAt,
		arg.Status,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeviceID,
		&i.UserID,
		&i.SyncType,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.RecordsPushed,
		&i.RecordsPulled,
		&i.ErrorsCount,
		&i.ErrorMessage,
	)
	return i, err
}

const getPendingConflicts = `-- name: GetPendingConflicts :many
SELECT id, org_id, table_name, record_id, device_id, server_version, client_version, conflict_type, resolution, resolved_by, resolved_at, created_at FROM sync_conflicts
WHERE org_id = $1 AND resolution = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingConflicts(ctx context.Context, orgID string) ([]SyncConflict, error) {
	rows, err := q.query(ctx, q.getPendingConflictsStmt, getPendingConflicts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncConflict{}
	for rows.Next() {
		var i SyncConflict
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TableName,
			&i.RecordID,
			&i.DeviceID,
			&i.ServerVersion,
			&i.ClientVersion,
			&i.ConflictType,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSyncConflict = `-- name: ResolveSyncConflict :exec
UPDATE sync_conflicts SET
    resolution = $1, resolved_by = $2, resolved_at = now()
WHERE id = $3
`

type ResolveSyncConflictParams struct {
	Resolution string         `json:"resolution"`
	ResolvedBy sql.NullString `json:"resolved_by"`
	ID         string         `json:"id"`
}

func (q *Queries) ResolveSyncConflict(ctx context.Context, arg ResolveSyncConflictParams) error {
	_, err := q.exec(ctx, q.resolveSyncConflictStmt, resolveSyncConflict, arg.Resolution, arg.ResolvedBy, arg.ID)
	return err
}

const updateSyncLog = `-- name: UpdateSyncLog :exec
UPDATE sync_log SET
    completed_at = $1, status = $2,
    records_pushed = $3, records_pulled = $4,
    errors_count = $5, error_message = $6
WHERE id = $7
`

type UpdateSyncLogParams struct {
	CompletedAt   sql.NullTime   `json:"completed_at"`
	Status        sql.NullString `json:"status"`
	RecordsPushed int32          `json:"records_pushed"`
	RecordsPulled int32          `json:"records_pulled"`
	ErrorsCount   int32          `json:"errors_count"`
	ErrorMessage  sql.NullString `json:"error_message"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateSyncLog(ctx context.Context, arg UpdateSyncLogParams) error {
	_, err := q.exec(ctx, q.updateSyncLogStmt, updateSyncLog,
		arg.CompletedAt,
		arg.Status,
		arg.RecordsPushed,
		arg.RecordsPulled,
		arg.ErrorsCount,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
