// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAdjustment = `-- name: CreateAdjustment :one
INSERT INTO stock_adjustments (org_id, warehouse_id, reason_code, description, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, warehouse_id, reason_code, description, status, created_by, updated_by, created_at, updated_at
`

type CreateAdjustmentParams struct {
	OrgID       string         `json:"org_id"`
	WarehouseID string         `json:"warehouse_id"`
	ReasonCode  string         `json:"reason_code"`
	Description sql.NullString `json:"description"`
	Status      EntityStatus   `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateAdjustment(ctx context.Context, arg CreateAdjustmentParams) (StockAdjustment, error) {
	row := q.queryRow(ctx, q.createAdjustmentStmt, createAdjustment,
		arg.OrgID,
		arg.WarehouseID,
		arg.ReasonCode,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.ReasonCode,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdjustmentLineItem = `-- name: CreateAdjustmentLineItem :exec
INSERT INTO adjustment_line_items (adjustment_id, product_id, batch_id, location_id, expected_quantity, actual_quantity, difference, reason_code, unit_cost, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAdjustmentLineItemParams struct {
	AdjustmentID     string         `json:"adjustment_id"`
	ProductID        string         `json:"product_id"`
	BatchID          uuid.NullUUID  `json:"batch_id"`
	LocationID       uuid.NullUUID  `json:"location_id"`
	ExpectedQuantity string         `json:"expected_quantity"`
	ActualQuantity   string         `json:"actual_quantity"`
	Difference       string         `json:"difference"`
	ReasonCode       sql.NullString `json:"reason_code"`
	UnitCost         sql.NullString `json:"unit_cost"`
	Notes            sql.NullString `json:"notes"`
}

func (q *Queries) CreateAdjustmentLineItem(ctx context.Context, arg CreateAdjustmentLineItemParams) error {
	_, err := q.exec(ctx, q.createAdjustmentLineItemStmt, createAdjustmentLineItem,
		arg.AdjustmentID,
		arg.ProductID,
		arg.BatchID,
		arg.LocationID,
		arg.ExpectedQuantity,
		arg.ActualQuantity,
		arg.Difference,
		arg.ReasonCode,
		arg.UnitCost,
		arg.Notes,
	)
	return err
}

const createIssueLineItem = `-- name: CreateIssueLineItem :exec
INSERT INTO issue_line_items (issue_id, product_id, batch_id, quantity, unit_cost)
VALUES ($1, $2, $3, $4, $5)
`

type CreateIssueLineItemParams struct {
	IssueID   string         `json:"issue_id"`
	ProductID string         `json:"product_id"`
	BatchID   uuid.NullUUID  `json:"batch_id"`
	Quantity  string         `json:"quantity"`
	UnitCost  sql.NullString `json:"unit_cost"`
}

func (q *Queries) CreateIssueLineItem(ctx context.Context, arg CreateIssueLineItemParams) error {
	_, err := q.exec(ctx, q.createIssueLineItemStmt, createIssueLineItem,
		arg.IssueID,
		arg.ProductID,
		arg.BatchID,
		arg.Quantity,
		arg.UnitCost,
	)
	return err
}

const createStockIssue = `-- name: CreateStockIssue :one
INSERT INTO stock_issues (org_id, warehouse_id, issue_number, requested_by, approved_by, program_id, department_id, status, notes, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, warehouse_id, issue_number, requested_by, approved_by, program_id, department_id, status, notes, created_by, updated_by, created_at, updated_at
`

type CreateStockIssueParams struct {
	OrgID        string         `json:"org_id"`
	WarehouseID  string         `json:"warehouse_id"`
	IssueNumber  string         `json:"issue_number"`
	RequestedBy  sql.NullString `json:"requested_by"`
	ApprovedBy   sql.NullString `json:"approved_by"`
	ProgramID    uuid.NullUUID  `json:"program_id"`
	DepartmentID uuid.NullUUID  `json:"department_id"`
	Status       EntityStatus   `json:"status"`
	Notes        sql.NullString `json:"notes"`
	CreatedBy    sql.NullString `json:"created_by"`
	UpdatedBy    sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateStockIssue(ctx context.Context, arg CreateStockIssueParams) (StockIssue, error) {
	row := q.queryRow(ctx, q.createStockIssueStmt, createStockIssue,
		arg.OrgID,
		arg.WarehouseID,
		arg.IssueNumber,
		arg.RequestedBy,
		arg.ApprovedBy,
		arg.ProgramID,
		arg.DepartmentID,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i StockIssue
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.IssueNumber,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProgramID,
		&i.DepartmentID,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO stock_transfers (org_id, from_warehouse_id, to_warehouse_id, transfer_number, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, from_warehouse_id, to_warehouse_id, transfer_number, status, created_by, updated_by, created_at, updated_at
`

type CreateTransferParams struct {
	OrgID           string         `json:"org_id"`
	FromWarehouseID string         `json:"from_warehouse_id"`
	ToWarehouseID   string         `json:"to_warehouse_id"`
	TransferNumber  string         `json:"transfer_number"`
	Status          EntityStatus   `json:"status"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (StockTransfer, error) {
	row := q.queryRow(ctx, q.createTransferStmt, createTransfer,
		arg.OrgID,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.TransferNumber,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransferNumber,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransferLineItem = `-- name: CreateTransferLineItem :exec
INSERT INTO transfer_line_items (transfer_id, product_id, batch_id, quantity, unit_cost, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTransferLineItemParams struct {
	TransferID string         `json:"transfer_id"`
	ProductID  string         `json:"product_id"`
	BatchID    uuid.NullUUID  `json:"batch_id"`
	Quantity   string         `json:"quantity"`
	UnitCost   sql.NullString `json:"unit_cost"`
	Status     EntityStatus   `json:"status"`
}

func (q *Queries) CreateTransferLineItem(ctx context.Context, arg CreateTransferLineItemParams) error {
	_, err := q.exec(ctx, q.createTransferLineItemStmt, createTransferLineItem,
		arg.TransferID,
		arg.ProductID,
		arg.BatchID,
		arg.Quantity,
		arg.UnitCost,
		arg.Status,
	)
	return err
}

const getAdjustment = `-- name: GetAdjustment :one
SELECT sa.id, sa.org_id, sa.warehouse_id, sa.reason_code, sa.description, sa.status, sa.created_by, sa.updated_by, sa.created_at, sa.updated_at, w.name as warehouse_name
FROM stock_adjustments sa
LEFT JOIN warehouses w ON sa.warehouse_id = w.id
WHERE sa.id = $1 AND sa.org_id = $2
`

type GetAdjustmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetAdjustmentRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	ReasonCode    string         `json:"reason_code"`
	Description   sql.NullString `json:"description"`
	Status        EntityStatus   `json:"status"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) GetAdjustment(ctx context.Context, arg GetAdjustmentParams) (GetAdjustmentRow, error) {
	row := q.queryRow(ctx, q.getAdjustmentStmt, getAdjustment, arg.ID, arg.OrgID)
	var i GetAdjustmentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.ReasonCode,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarehouseName,
	)
	return i, err
}

const getGRN = `-- name: GetGRN :one
SELECT g.id, g.org_id, g.warehouse_id, g.grn_number, g.supplier, g.po_number, g.received_by, g.status, g.notes, g.created_by, g.updated_by, g.created_at, g.updated_at, w.name as warehouse_name
FROM goods_receipts g
LEFT JOIN warehouses w ON g.warehouse_id = w.id
WHERE g.id = $1 AND g.org_id = $2
`

type GetGRNParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetGRNRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	GrnNumber     string         `json:"grn_number"`
	Supplier      sql.NullString `json:"supplier"`
	PoNumber      sql.NullString `json:"po_number"`
	ReceivedBy    sql.NullString `json:"received_by"`
	Status        EntityStatus   `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) GetGRN(ctx context.Context, arg GetGRNParams) (GetGRNRow, error) {
	row := q.queryRow(ctx, q.getGRNStmt, getGRN, arg.ID, arg.OrgID)
	var i GetGRNRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.GrnNumber,
		&i.Supplier,
		&i.PoNumber,
		&i.ReceivedBy,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarehouseName,
	)
	return i, err
}

const getStockIssue = `-- name: GetStockIssue :one
SELECT si.id, si.org_id, si.warehouse_id, si.issue_number, si.requested_by, si.approved_by, si.program_id, si.department_id, si.status, si.notes, si.created_by, si.updated_by, si.created_at, si.updated_at, w.name as warehouse_name
FROM stock_issues si
LEFT JOIN warehouses w ON si.warehouse_id = w.id
WHERE si.id = $1 AND si.org_id = $2
`

type GetStockIssueParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetStockIssueRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	IssueNumber   string         `json:"issue_number"`
	RequestedBy   sql.NullString `json:"requested_by"`
	ApprovedBy    sql.NullString `json:"approved_by"`
	ProgramID     uuid.NullUUID  `json:"program_id"`
	DepartmentID  uuid.NullUUID  `json:"department_id"`
	Status        EntityStatus   `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) GetStockIssue(ctx context.Context, arg GetStockIssueParams) (GetStockIssueRow, error) {
	row := q.queryRow(ctx, q.getStockIssueStmt, getStockIssue, arg.ID, arg.OrgID)
	var i GetStockIssueRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WarehouseID,
		&i.IssueNumber,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProgramID,
		&i.DepartmentID,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarehouseName,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT t.id, t.org_id, t.from_warehouse_id, t.to_warehouse_id, t.transfer_number, t.status, t.created_by, t.updated_by, t.created_at, t.updated_at, fw.name as from_warehouse_name, tw.name as to_warehouse_name
FROM stock_transfers t
LEFT JOIN warehouses fw ON t.from_warehouse_id = fw.id
LEFT JOIN warehouses tw ON t.to_warehouse_id = tw.id
WHERE t.id = $1 AND t.org_id = $2
`

type GetTransferParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetTransferRow struct {
	ID                string         `json:"id"`
	OrgID             string         `json:"org_id"`
	FromWarehouseID   string         `json:"from_warehouse_id"`
	ToWarehouseID     string         `json:"to_warehouse_id"`
	TransferNumber    string         `json:"transfer_number"`
	Status            EntityStatus   `json:"status"`
	CreatedBy         sql.NullString `json:"created_by"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	FromWarehouseName sql.NullString `json:"from_warehouse_name"`
	ToWarehouseName   sql.NullString `json:"to_warehouse_name"`
}

func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) (GetTransferRow, error) {
	row := q.queryRow(ctx, q.getTransferStmt, getTransfer, arg.ID, arg.OrgID)
	var i GetTransferRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransferNumber,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FromWarehouseName,
		&i.ToWarehouseName,
	)
	return i, err
}

const listAdjustmentReasonCodes = `-- name: ListAdjustmentReasonCodes :many
SELECT code, category, description, requires_approval, is_active, created_at FROM adjustment_reason_codes
WHERE is_active = true
ORDER BY category, code
`

func (q *Queries) ListAdjustmentReasonCodes(ctx context.Context) ([]AdjustmentReasonCode, error) {
	rows, err := q.query(ctx, q.listAdjustmentReasonCodesStmt, listAdjustmentReasonCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdjustmentReasonCode{}
	for rows.Next() {
		var i AdjustmentReasonCode
		if err := rows.Scan(
			&i.Code,
			&i.Category,
			&i.Description,
			&i.RequiresApproval,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdjustments = `-- name: ListAdjustments :many
SELECT sa.id, sa.org_id, sa.warehouse_id, sa.reason_code, sa.description, sa.status, sa.created_by, sa.updated_by, sa.created_at, sa.updated_at, w.name as warehouse_name
FROM stock_adjustments sa
LEFT JOIN warehouses w ON sa.warehouse_id = w.id
WHERE sa.org_id = $1
ORDER BY sa.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAdjustmentsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAdjustmentsRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	ReasonCode    string         `json:"reason_code"`
	Description   sql.NullString `json:"description"`
	Status        EntityStatus   `json:"status"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) ListAdjustments(ctx context.Context, arg ListAdjustmentsParams) ([]ListAdjustmentsRow, error) {
	rows, err := q.query(ctx, q.listAdjustmentsStmt, listAdjustments, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdjustmentsRow{}
	for rows.Next() {
		var i ListAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.ReasonCode,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNLineItems = `-- name: ListGRNLineItems :many
SELECT gli.id, gli.grn_id, gli.product_id, gli.batch_number, gli.serial_number, gli.expiry_date, gli.quantity, gli.unit_cost, gli.status, p.name as product_name, p.sku as product_sku
FROM grn_line_items gli
JOIN products p ON gli.product_id = p.id
WHERE gli.grn_id = $1
ORDER BY gli.id
`

type ListGRNLineItemsRow struct {
	ID           string         `json:"id"`
	GrnID        string         `json:"grn_id"`
	ProductID    string         `json:"product_id"`
	BatchNumber  sql.NullString `json:"batch_number"`
	SerialNumber sql.NullString `json:"serial_number"`
	ExpiryDate   sql.NullTime   `json:"expiry_date"`
	Quantity     string         `json:"quantity"`
	UnitCost     sql.NullString `json:"unit_cost"`
	Status       EntityStatus   `json:"status"`
	ProductName  string         `json:"product_name"`
	ProductSku   string         `json:"product_sku"`
}

func (q *Queries) ListGRNLineItems(ctx context.Context, grnID string) ([]ListGRNLineItemsRow, error) {
	rows, err := q.query(ctx, q.listGRNLineItemsStmt, listGRNLineItems, grnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGRNLineItemsRow{}
	for rows.Next() {
		var i ListGRNLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.GrnID,
			&i.ProductID,
			&i.BatchNumber,
			&i.SerialNumber,
			&i.ExpiryDate,
			&i.Quantity,
			&i.UnitCost,
			&i.Status,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNs = `-- name: ListGRNs :many
SELECT g.id, g.org_id, g.warehouse_id, g.grn_number, g.supplier, g.po_number, g.received_by, g.status, g.notes, g.created_by, g.updated_by, g.created_at, g.updated_at, w.name as warehouse_name
FROM goods_receipts g
LEFT JOIN warehouses w ON g.warehouse_id = w.id
WHERE g.org_id = $1
ORDER BY g.created_at DESC
LIMIT $2 OFFSET $3
`

type ListGRNsParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListGRNsRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	GrnNumber     string         `json:"grn_number"`
	Supplier      sql.NullString `json:"supplier"`
	PoNumber      sql.NullString `json:"po_number"`
	ReceivedBy    sql.NullString `json:"received_by"`
	Status        EntityStatus   `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) ListGRNs(ctx context.Context, arg ListGRNsParams) ([]ListGRNsRow, error) {
	rows, err := q.query(ctx, q.listGRNsStmt, listGRNs, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGRNsRow{}
	for rows.Next() {
		var i ListGRNsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.GrnNumber,
			&i.Supplier,
			&i.PoNumber,
			&i.ReceivedBy,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueLineItems = `-- name: ListIssueLineItems :many
SELECT ili.id, ili.issue_id, ili.product_id, ili.batch_id, ili.quantity, ili.unit_cost, p.name as product_name, p.sku as product_sku
FROM issue_line_items ili
JOIN products p ON ili.product_id = p.id
WHERE ili.issue_id = $1
ORDER BY ili.id
`

type ListIssueLineItemsRow struct {
	ID          string         `json:"id"`
	IssueID     string         `json:"issue_id"`
	ProductID   string         `json:"product_id"`
	BatchID     uuid.NullUUID  `json:"batch_id"`
	Quantity    string         `json:"quantity"`
	UnitCost    sql.NullString `json:"unit_cost"`
	ProductName string         `json:"product_name"`
	ProductSku  string         `json:"product_sku"`
}

func (q *Queries) ListIssueLineItems(ctx context.Context, issueID string) ([]ListIssueLineItemsRow, error) {
	rows, err := q.query(ctx, q.listIssueLineItemsStmt, listIssueLineItems, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueLineItemsRow{}
	for rows.Next() {
		var i ListIssueLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProductID,
			&i.BatchID,
			&i.Quantity,
			&i.UnitCost,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockIssues = `-- name: ListStockIssues :many
SELECT si.id, si.org_id, si.warehouse_id, si.issue_number, si.requested_by, si.approved_by, si.program_id, si.department_id, si.status, si.notes, si.created_by, si.updated_by, si.created_at, si.updated_at, w.name as warehouse_name
FROM stock_issues si
LEFT JOIN warehouses w ON si.warehouse_id = w.id
WHERE si.org_id = $1
ORDER BY si.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockIssuesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListStockIssuesRow struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	WarehouseID   string         `json:"warehouse_id"`
	IssueNumber   string         `json:"issue_number"`
	RequestedBy   sql.NullString `json:"requested_by"`
	ApprovedBy    sql.NullString `json:"approved_by"`
	ProgramID     uuid.NullUUID  `json:"program_id"`
	DepartmentID  uuid.NullUUID  `json:"department_id"`
	Status        EntityStatus   `json:"status"`
	Notes         sql.NullString `json:"notes"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	WarehouseName sql.NullString `json:"warehouse_name"`
}

func (q *Queries) ListStockIssues(ctx context.Context, arg ListStockIssuesParams) ([]ListStockIssuesRow, error) {
	rows, err := q.query(ctx, q.listStockIssuesStmt, listStockIssues, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockIssuesRow{}
	for rows.Next() {
		var i ListStockIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WarehouseID,
			&i.IssueNumber,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ProgramID,
			&i.DepartmentID,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferLineItems = `-- name: ListTransferLineItems :many
SELECT tli.id, tli.transfer_id, tli.product_id, tli.batch_id, tli.quantity, tli.unit_cost, tli.status, p.name as product_name, p.sku as product_sku
FROM transfer_line_items tli
JOIN products p ON tli.product_id = p.id
WHERE tli.transfer_id = $1
ORDER BY tli.id
`

type ListTransferLineItemsRow struct {
	ID          string         `json:"id"`
	TransferID  string         `json:"transfer_id"`
	ProductID   string         `json:"product_id"`
	BatchID     uuid.NullUUID  `json:"batch_id"`
	Quantity    string         `json:"quantity"`
	UnitCost    sql.NullString `json:"unit_cost"`
	Status      EntityStatus   `json:"status"`
	ProductName string         `json:"product_name"`
	ProductSku  string         `json:"product_sku"`
}

func (q *Queries) ListTransferLineItems(ctx context.Context, transferID string) ([]ListTransferLineItemsRow, error) {
	rows, err := q.query(ctx, q.listTransferLineItemsStmt, listTransferLineItems, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferLineItemsRow{}
	for rows.Next() {
		var i ListTransferLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.ProductID,
			&i.BatchID,
			&i.Quantity,
			&i.UnitCost,
			&i.Status,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT t.id, t.org_id, t.from_warehouse_id, t.to_warehouse_id, t.transfer_number, t.status, t.created_by, t.updated_by, t.created_at, t.updated_at, fw.name as from_warehouse_name, tw.name as to_warehouse_name
FROM stock_transfers t
LEFT JOIN warehouses fw ON t.from_warehouse_id = fw.id
LEFT JOIN warehouses tw ON t.to_warehouse_id = tw.id
WHERE t.org_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListTransfersRow struct {
	ID                string         `json:"id"`
	OrgID             string         `json:"org_id"`
	FromWarehouseID   string         `json:"from_warehouse_id"`
	ToWarehouseID     string         `json:"to_warehouse_id"`
	TransferNumber    string         `json:"transfer_number"`
	Status            EntityStatus   `json:"status"`
	CreatedBy         sql.NullString `json:"created_by"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	FromWarehouseName sql.NullString `json:"from_warehouse_name"`
	ToWarehouseName   sql.NullString `json:"to_warehouse_name"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error) {
	rows, err := q.query(ctx, q.listTransfersStmt, listTransfers, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.TransferNumber,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromWarehouseName,
			&i.ToWarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
