// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: warehouses.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (warehouse_id, parent_id, code, name, type, is_cold_chain, is_hazardous, is_secure, max_capacity, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, warehouse_id, parent_id, code, name, type, is_cold_chain, is_hazardous, is_secure, max_capacity, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	WarehouseID string         `json:"warehouse_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Type        LocationType   `json:"type"`
	IsColdChain bool           `json:"is_cold_chain"`
	IsHazardous bool           `json:"is_hazardous"`
	IsSecure    bool           `json:"is_secure"`
	MaxCapacity sql.NullString `json:"max_capacity"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.queryRow(ctx, q.createLocationStmt, createLocation,
		arg.WarehouseID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.IsColdChain,
		arg.IsHazardous,
		arg.IsSecure,
		arg.MaxCapacity,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsColdChain,
		&i.IsHazardous,
		&i.IsSecure,
		&i.MaxCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (org_id, name, code, type, address, city, country, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, code, type, address, city, country, is_active, created_by, updated_by, created_at, updated_at
`

type CreateWarehouseParams struct {
	OrgID     string         `json:"org_id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Type      WarehouseType  `json:"type"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
	IsActive  bool           `json:"is_active"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.queryRow(ctx, q.createWarehouseStmt, createWarehouse,
		arg.OrgID,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.Address,
		arg.City,
		arg.Country,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Address,
		&i.City,
		&i.Country,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehouse = `-- name: GetWarehouse :one
SELECT id, org_id, name, code, type, address, city, country, is_active, created_by, updated_by, created_at, updated_at FROM warehouses
WHERE id = $1 AND org_id = $2
`

type GetWarehouseParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetWarehouse(ctx context.Context, arg GetWarehouseParams) (Warehouse, error) {
	row := q.queryRow(ctx, q.getWarehouseStmt, getWarehouse, arg.ID, arg.OrgID)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Address,
		&i.City,
		&i.Country,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehouseWithLocations = `-- name: GetWarehouseWithLocations :many
SELECT w.id, w.org_id, w.name, w.code, w.type, w.address, w.city, w.country, w.is_active, w.created_by, w.updated_by, w.created_at, w.updated_at, l.id as location_id, l.code as location_code, l.name as location_name,
       l.type as location_type, l.is_cold_chain, l.is_hazardous, l.is_secure,
       l.max_capacity, l.is_active as location_active
FROM warehouses w
LEFT JOIN locations l ON l.warehouse_id = w.id
WHERE w.id = $1 AND w.org_id = $2
ORDER BY l.code
`

type GetWarehouseWithLocationsParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetWarehouseWithLocationsRow struct {
	ID             string           `json:"id"`
	OrgID          string           `json:"org_id"`
	Name           string           `json:"name"`
	Code           string           `json:"code"`
	Type           WarehouseType    `json:"type"`
	Address        sql.NullString   `json:"address"`
	City           sql.NullString   `json:"city"`
	Country        sql.NullString   `json:"country"`
	IsActive       bool             `json:"is_active"`
	CreatedBy      sql.NullString   `json:"created_by"`
	UpdatedBy      sql.NullString   `json:"updated_by"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
	LocationID     uuid.NullUUID    `json:"location_id"`
	LocationCode   sql.NullString   `json:"location_code"`
	LocationName   sql.NullString   `json:"location_name"`
	LocationType   NullLocationType `json:"location_type"`
	IsColdChain    sql.NullBool     `json:"is_cold_chain"`
	IsHazardous    sql.NullBool     `json:"is_hazardous"`
	IsSecure       sql.NullBool     `json:"is_secure"`
	MaxCapacity    sql.NullString   `json:"max_capacity"`
	LocationActive sql.NullBool     `json:"location_active"`
}

func (q *Queries) GetWarehouseWithLocations(ctx context.Context, arg GetWarehouseWithLocationsParams) ([]GetWarehouseWithLocationsRow, error) {
	rows, err := q.query(ctx, q.getWarehouseWithLocationsStmt, getWarehouseWithLocations, arg.ID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWarehouseWithLocationsRow{}
	for rows.Next() {
		var i GetWarehouseWithLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Address,
			&i.City,
			&i.Country,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationID,
			&i.LocationCode,
			&i.LocationName,
			&i.LocationType,
			&i.IsColdChain,
			&i.IsHazardous,
			&i.IsSecure,
			&i.MaxCapacity,
			&i.LocationActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, warehouse_id, parent_id, code, name, type, is_cold_chain, is_hazardous, is_secure, max_capacity, is_active, created_at, updated_at FROM locations
WHERE warehouse_id = $1
ORDER BY code
`

func (q *Queries) ListLocations(ctx context.Context, warehouseID string) ([]Location, error) {
	rows, err := q.query(ctx, q.listLocationsStmt, listLocations, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.IsColdChain,
			&i.IsHazardous,
			&i.IsSecure,
			&i.MaxCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, org_id, name, code, type, address, city, country, is_active, created_by, updated_by, created_at, updated_at FROM warehouses
WHERE org_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListWarehouses(ctx context.Context, orgID string) ([]Warehouse, error) {
	rows, err := q.query(ctx, q.listWarehousesStmt, listWarehouses, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Address,
			&i.City,
			&i.Country,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehousesByType = `-- name: ListWarehousesByType :many
SELECT id, org_id, name, code, type, address, city, country, is_active, created_by, updated_by, created_at, updated_at FROM warehouses
WHERE org_id = $1 AND type = $2::warehouse_type
ORDER BY name
`

type ListWarehousesByTypeParams struct {
	OrgID   string        `json:"org_id"`
	Column2 WarehouseType `json:"column_2"`
}

func (q *Queries) ListWarehousesByType(ctx context.Context, arg ListWarehousesByTypeParams) ([]Warehouse, error) {
	rows, err := q.query(ctx, q.listWarehousesByTypeStmt, listWarehousesByType, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Address,
			&i.City,
			&i.Country,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :exec
UPDATE locations SET
    code = $1, name = $2, type = $3::location_type,
    is_cold_chain = $4, is_hazardous = $5, is_secure = $6,
    max_capacity = $7, is_active = $8
WHERE id = $9
`

type UpdateLocationParams struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Column3     LocationType   `json:"column_3"`
	IsColdChain bool           `json:"is_cold_chain"`
	IsHazardous bool           `json:"is_hazardous"`
	IsSecure    bool           `json:"is_secure"`
	MaxCapacity sql.NullString `json:"max_capacity"`
	IsActive    bool           `json:"is_active"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) error {
	_, err := q.exec(ctx, q.updateLocationStmt, updateLocation,
		arg.Code,
		arg.Name,
		arg.Column3,
		arg.IsColdChain,
		arg.IsHazardous,
		arg.IsSecure,
		arg.MaxCapacity,
		arg.IsActive,
		arg.ID,
	)
	return err
}
